// Code generated by ent, DO NOT EDIT.

package emailplan

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/bengobox/subscription-service/internal/ent/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.EmailPlan {
	return predicate.EmailPlan(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.EmailPlan {
	return predicate.EmailPlan(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.EmailPlan {
	return predicate.EmailPlan(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.EmailPlan {
	return predicate.EmailPlan(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.EmailPlan {
	return predicate.EmailPlan(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.EmailPlan {
	return predicate.EmailPlan(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.EmailPlan {
	return predicate.EmailPlan(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.EmailPlan {
	return predicate.EmailPlan(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.EmailPlan {
	return predicate.EmailPlan(sql.FieldLTE(FieldID, id))
}

// Code applies equality check predicate on the "code" field. It's identical to CodeEQ.
func Code(v string) predicate.EmailPlan {
	return predicate.EmailPlan(sql.FieldEQ(FieldCode, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.EmailPlan {
	return predicate.EmailPlan(sql.FieldEQ(FieldName, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.EmailPlan {
	return predicate.EmailPlan(sql.FieldEQ(FieldDescription, v))
}

// PricePerUserMonthly applies equality check predicate on the "price_per_user_monthly" field. It's identical to PricePerUserMonthlyEQ.
func PricePerUserMonthly(v float64) predicate.EmailPlan {
	return predicate.EmailPlan(sql.FieldEQ(FieldPricePerUserMonthly, v))
}

// PricePerUserYearly applies equality check predicate on the "price_per_user_yearly" field. It's identical to PricePerUserYearlyEQ.
func PricePerUserYearly(v float64) predicate.EmailPlan {
	return predicate.EmailPlan(sql.FieldEQ(FieldPricePerUserYearly, v))
}

// StoragePerUserGB applies equality check predicate on the "storage_per_user_gb" field. It's identical to StoragePerUserGBEQ.
func StoragePerUserGB(v int) predicate.EmailPlan {
	return predicate.EmailPlan(sql.FieldEQ(FieldStoragePerUserGB, v))
}

// MaxAliases applies equality check predicate on the "max_aliases" field. It's identical to MaxAliasesEQ.
func MaxAliases(v int) predicate.EmailPlan {
	return predicate.EmailPlan(sql.FieldEQ(FieldMaxAliases, v))
}

// MaxEmailSizeMB applies equality check predicate on the "max_email_size_mb" field. It's identical to MaxEmailSizeMBEQ.
func MaxEmailSizeMB(v int) predicate.EmailPlan {
	return predicate.EmailPlan(sql.FieldEQ(FieldMaxEmailSizeMB, v))
}

// IsActive applies equality check predicate on the "is_active" field. It's identical to IsActiveEQ.
func IsActive(v bool) predicate.EmailPlan {
	return predicate.EmailPlan(sql.FieldEQ(FieldIsActive, v))
}

// IsPublic applies equality check predicate on the "is_public" field. It's identical to IsPublicEQ.
func IsPublic(v bool) predicate.EmailPlan {
	return predicate.EmailPlan(sql.FieldEQ(FieldIsPublic, v))
}

// SortOrder applies equality check predicate on the "sort_order" field. It's identical to SortOrderEQ.
func SortOrder(v int) predicate.EmailPlan {
	return predicate.EmailPlan(sql.FieldEQ(FieldSortOrder, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.EmailPlan {
	return predicate.EmailPlan(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.EmailPlan {
	return predicate.EmailPlan(sql.FieldEQ(FieldUpdatedAt, v))
}

// CodeEQ applies the EQ predicate on the "code" field.
func CodeEQ(v string) predicate.EmailPlan {
	return predicate.EmailPlan(sql.FieldEQ(FieldCode, v))
}

// CodeNEQ applies the NEQ predicate on the "code" field.
func CodeNEQ(v string) predicate.EmailPlan {
	return predicate.EmailPlan(sql.FieldNEQ(FieldCode, v))
}

// CodeIn applies the In predicate on the "code" field.
func CodeIn(vs ...string) predicate.EmailPlan {
	return predicate.EmailPlan(sql.FieldIn(FieldCode, vs...))
}

// CodeNotIn applies the NotIn predicate on the "code" field.
func CodeNotIn(vs ...string) predicate.EmailPlan {
	return predicate.EmailPlan(sql.FieldNotIn(FieldCode, vs...))
}

// CodeGT applies the GT predicate on the "code" field.
func CodeGT(v string) predicate.EmailPlan {
	return predicate.EmailPlan(sql.FieldGT(FieldCode, v))
}

// CodeGTE applies the GTE predicate on the "code" field.
func CodeGTE(v string) predicate.EmailPlan {
	return predicate.EmailPlan(sql.FieldGTE(FieldCode, v))
}

// CodeLT applies the LT predicate on the "code" field.
func CodeLT(v string) predicate.EmailPlan {
	return predicate.EmailPlan(sql.FieldLT(FieldCode, v))
}

// CodeLTE applies the LTE predicate on the "code" field.
func CodeLTE(v string) predicate.EmailPlan {
	return predicate.EmailPlan(sql.FieldLTE(FieldCode, v))
}

// CodeContains applies the Contains predicate on the "code" field.
func CodeContains(v string) predicate.EmailPlan {
	return predicate.EmailPlan(sql.FieldContains(FieldCode, v))
}

// CodeHasPrefix applies the HasPrefix predicate on the "code" field.
func CodeHasPrefix(v string) predicate.EmailPlan {
	return predicate.EmailPlan(sql.FieldHasPrefix(FieldCode, v))
}

// CodeHasSuffix applies the HasSuffix predicate on the "code" field.
func CodeHasSuffix(v string) predicate.EmailPlan {
	return predicate.EmailPlan(sql.FieldHasSuffix(FieldCode, v))
}

// CodeEqualFold applies the EqualFold predicate on the "code" field.
func CodeEqualFold(v string) predicate.EmailPlan {
	return predicate.EmailPlan(sql.FieldEqualFold(FieldCode, v))
}

// CodeContainsFold applies the ContainsFold predicate on the "code" field.
func CodeContainsFold(v string) predicate.EmailPlan {
	return predicate.EmailPlan(sql.FieldContainsFold(FieldCode, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.EmailPlan {
	return predicate.EmailPlan(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.EmailPlan {
	return predicate.EmailPlan(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.EmailPlan {
	return predicate.EmailPlan(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.EmailPlan {
	return predicate.EmailPlan(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.EmailPlan {
	return predicate.EmailPlan(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.EmailPlan {
	return predicate.EmailPlan(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.EmailPlan {
	return predicate.EmailPlan(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.EmailPlan {
	return predicate.EmailPlan(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.EmailPlan {
	return predicate.EmailPlan(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.EmailPlan {
	return predicate.EmailPlan(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.EmailPlan {
	return predicate.EmailPlan(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.EmailPlan {
	return predicate.EmailPlan(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.EmailPlan {
	return predicate.EmailPlan(sql.FieldContainsFold(FieldName, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.EmailPlan {
	return predicate.EmailPlan(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.EmailPlan {
	return predicate.EmailPlan(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.EmailPlan {
	return predicate.EmailPlan(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.EmailPlan {
	return predicate.EmailPlan(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.EmailPlan {
	return predicate.EmailPlan(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.EmailPlan {
	return predicate.EmailPlan(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.EmailPlan {
	return predicate.EmailPlan(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.EmailPlan {
	return predicate.EmailPlan(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.EmailPlan {
	return predicate.EmailPlan(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.EmailPlan {
	return predicate.EmailPlan(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.EmailPlan {
	return predicate.EmailPlan(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionIsNil applies the IsNil predicate on the "description" field.
func DescriptionIsNil() predicate.EmailPlan {
	return predicate.EmailPlan(sql.FieldIsNull(FieldDescription))
}

// DescriptionNotNil applies the NotNil predicate on the "description" field.
func DescriptionNotNil() predicate.EmailPlan {
	return predicate.EmailPlan(sql.FieldNotNull(FieldDescription))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.EmailPlan {
	return predicate.EmailPlan(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.EmailPlan {
	return predicate.EmailPlan(sql.FieldContainsFold(FieldDescription, v))
}

// PricePerUserMonthlyEQ applies the EQ predicate on the "price_per_user_monthly" field.
func PricePerUserMonthlyEQ(v float64) predicate.EmailPlan {
	return predicate.EmailPlan(sql.FieldEQ(FieldPricePerUserMonthly, v))
}

// PricePerUserMonthlyNEQ applies the NEQ predicate on the "price_per_user_monthly" field.
func PricePerUserMonthlyNEQ(v float64) predicate.EmailPlan {
	return predicate.EmailPlan(sql.FieldNEQ(FieldPricePerUserMonthly, v))
}

// PricePerUserMonthlyIn applies the In predicate on the "price_per_user_monthly" field.
func PricePerUserMonthlyIn(vs ...float64) predicate.EmailPlan {
	return predicate.EmailPlan(sql.FieldIn(FieldPricePerUserMonthly, vs...))
}

// PricePerUserMonthlyNotIn applies the NotIn predicate on the "price_per_user_monthly" field.
func PricePerUserMonthlyNotIn(vs ...float64) predicate.EmailPlan {
	return predicate.EmailPlan(sql.FieldNotIn(FieldPricePerUserMonthly, vs...))
}

// PricePerUserMonthlyGT applies the GT predicate on the "price_per_user_monthly" field.
func PricePerUserMonthlyGT(v float64) predicate.EmailPlan {
	return predicate.EmailPlan(sql.FieldGT(FieldPricePerUserMonthly, v))
}

// PricePerUserMonthlyGTE applies the GTE predicate on the "price_per_user_monthly" field.
func PricePerUserMonthlyGTE(v float64) predicate.EmailPlan {
	return predicate.EmailPlan(sql.FieldGTE(FieldPricePerUserMonthly, v))
}

// PricePerUserMonthlyLT applies the LT predicate on the "price_per_user_monthly" field.
func PricePerUserMonthlyLT(v float64) predicate.EmailPlan {
	return predicate.EmailPlan(sql.FieldLT(FieldPricePerUserMonthly, v))
}

// PricePerUserMonthlyLTE applies the LTE predicate on the "price_per_user_monthly" field.
func PricePerUserMonthlyLTE(v float64) predicate.EmailPlan {
	return predicate.EmailPlan(sql.FieldLTE(FieldPricePerUserMonthly, v))
}

// PricePerUserYearlyEQ applies the EQ predicate on the "price_per_user_yearly" field.
func PricePerUserYearlyEQ(v float64) predicate.EmailPlan {
	return predicate.EmailPlan(sql.FieldEQ(FieldPricePerUserYearly, v))
}

// PricePerUserYearlyNEQ applies the NEQ predicate on the "price_per_user_yearly" field.
func PricePerUserYearlyNEQ(v float64) predicate.EmailPlan {
	return predicate.EmailPlan(sql.FieldNEQ(FieldPricePerUserYearly, v))
}

// PricePerUserYearlyIn applies the In predicate on the "price_per_user_yearly" field.
func PricePerUserYearlyIn(vs ...float64) predicate.EmailPlan {
	return predicate.EmailPlan(sql.FieldIn(FieldPricePerUserYearly, vs...))
}

// PricePerUserYearlyNotIn applies the NotIn predicate on the "price_per_user_yearly" field.
func PricePerUserYearlyNotIn(vs ...float64) predicate.EmailPlan {
	return predicate.EmailPlan(sql.FieldNotIn(FieldPricePerUserYearly, vs...))
}

// PricePerUserYearlyGT applies the GT predicate on the "price_per_user_yearly" field.
func PricePerUserYearlyGT(v float64) predicate.EmailPlan {
	return predicate.EmailPlan(sql.FieldGT(FieldPricePerUserYearly, v))
}

// PricePerUserYearlyGTE applies the GTE predicate on the "price_per_user_yearly" field.
func PricePerUserYearlyGTE(v float64) predicate.EmailPlan {
	return predicate.EmailPlan(sql.FieldGTE(FieldPricePerUserYearly, v))
}

// PricePerUserYearlyLT applies the LT predicate on the "price_per_user_yearly" field.
func PricePerUserYearlyLT(v float64) predicate.EmailPlan {
	return predicate.EmailPlan(sql.FieldLT(FieldPricePerUserYearly, v))
}

// PricePerUserYearlyLTE applies the LTE predicate on the "price_per_user_yearly" field.
func PricePerUserYearlyLTE(v float64) predicate.EmailPlan {
	return predicate.EmailPlan(sql.FieldLTE(FieldPricePerUserYearly, v))
}

// PricePerUserYearlyIsNil applies the IsNil predicate on the "price_per_user_yearly" field.
func PricePerUserYearlyIsNil() predicate.EmailPlan {
	return predicate.EmailPlan(sql.FieldIsNull(FieldPricePerUserYearly))
}

// PricePerUserYearlyNotNil applies the NotNil predicate on the "price_per_user_yearly" field.
func PricePerUserYearlyNotNil() predicate.EmailPlan {
	return predicate.EmailPlan(sql.FieldNotNull(FieldPricePerUserYearly))
}

// StoragePerUserGBEQ applies the EQ predicate on the "storage_per_user_gb" field.
func StoragePerUserGBEQ(v int) predicate.EmailPlan {
	return predicate.EmailPlan(sql.FieldEQ(FieldStoragePerUserGB, v))
}

// StoragePerUserGBNEQ applies the NEQ predicate on the "storage_per_user_gb" field.
func StoragePerUserGBNEQ(v int) predicate.EmailPlan {
	return predicate.EmailPlan(sql.FieldNEQ(FieldStoragePerUserGB, v))
}

// StoragePerUserGBIn applies the In predicate on the "storage_per_user_gb" field.
func StoragePerUserGBIn(vs ...int) predicate.EmailPlan {
	return predicate.EmailPlan(sql.FieldIn(FieldStoragePerUserGB, vs...))
}

// StoragePerUserGBNotIn applies the NotIn predicate on the "storage_per_user_gb" field.
func StoragePerUserGBNotIn(vs ...int) predicate.EmailPlan {
	return predicate.EmailPlan(sql.FieldNotIn(FieldStoragePerUserGB, vs...))
}

// StoragePerUserGBGT applies the GT predicate on the "storage_per_user_gb" field.
func StoragePerUserGBGT(v int) predicate.EmailPlan {
	return predicate.EmailPlan(sql.FieldGT(FieldStoragePerUserGB, v))
}

// StoragePerUserGBGTE applies the GTE predicate on the "storage_per_user_gb" field.
func StoragePerUserGBGTE(v int) predicate.EmailPlan {
	return predicate.EmailPlan(sql.FieldGTE(FieldStoragePerUserGB, v))
}

// StoragePerUserGBLT applies the LT predicate on the "storage_per_user_gb" field.
func StoragePerUserGBLT(v int) predicate.EmailPlan {
	return predicate.EmailPlan(sql.FieldLT(FieldStoragePerUserGB, v))
}

// StoragePerUserGBLTE applies the LTE predicate on the "storage_per_user_gb" field.
func StoragePerUserGBLTE(v int) predicate.EmailPlan {
	return predicate.EmailPlan(sql.FieldLTE(FieldStoragePerUserGB, v))
}

// MaxAliasesEQ applies the EQ predicate on the "max_aliases" field.
func MaxAliasesEQ(v int) predicate.EmailPlan {
	return predicate.EmailPlan(sql.FieldEQ(FieldMaxAliases, v))
}

// MaxAliasesNEQ applies the NEQ predicate on the "max_aliases" field.
func MaxAliasesNEQ(v int) predicate.EmailPlan {
	return predicate.EmailPlan(sql.FieldNEQ(FieldMaxAliases, v))
}

// MaxAliasesIn applies the In predicate on the "max_aliases" field.
func MaxAliasesIn(vs ...int) predicate.EmailPlan {
	return predicate.EmailPlan(sql.FieldIn(FieldMaxAliases, vs...))
}

// MaxAliasesNotIn applies the NotIn predicate on the "max_aliases" field.
func MaxAliasesNotIn(vs ...int) predicate.EmailPlan {
	return predicate.EmailPlan(sql.FieldNotIn(FieldMaxAliases, vs...))
}

// MaxAliasesGT applies the GT predicate on the "max_aliases" field.
func MaxAliasesGT(v int) predicate.EmailPlan {
	return predicate.EmailPlan(sql.FieldGT(FieldMaxAliases, v))
}

// MaxAliasesGTE applies the GTE predicate on the "max_aliases" field.
func MaxAliasesGTE(v int) predicate.EmailPlan {
	return predicate.EmailPlan(sql.FieldGTE(FieldMaxAliases, v))
}

// MaxAliasesLT applies the LT predicate on the "max_aliases" field.
func MaxAliasesLT(v int) predicate.EmailPlan {
	return predicate.EmailPlan(sql.FieldLT(FieldMaxAliases, v))
}

// MaxAliasesLTE applies the LTE predicate on the "max_aliases" field.
func MaxAliasesLTE(v int) predicate.EmailPlan {
	return predicate.EmailPlan(sql.FieldLTE(FieldMaxAliases, v))
}

// MaxEmailSizeMBEQ applies the EQ predicate on the "max_email_size_mb" field.
func MaxEmailSizeMBEQ(v int) predicate.EmailPlan {
	return predicate.EmailPlan(sql.FieldEQ(FieldMaxEmailSizeMB, v))
}

// MaxEmailSizeMBNEQ applies the NEQ predicate on the "max_email_size_mb" field.
func MaxEmailSizeMBNEQ(v int) predicate.EmailPlan {
	return predicate.EmailPlan(sql.FieldNEQ(FieldMaxEmailSizeMB, v))
}

// MaxEmailSizeMBIn applies the In predicate on the "max_email_size_mb" field.
func MaxEmailSizeMBIn(vs ...int) predicate.EmailPlan {
	return predicate.EmailPlan(sql.FieldIn(FieldMaxEmailSizeMB, vs...))
}

// MaxEmailSizeMBNotIn applies the NotIn predicate on the "max_email_size_mb" field.
func MaxEmailSizeMBNotIn(vs ...int) predicate.EmailPlan {
	return predicate.EmailPlan(sql.FieldNotIn(FieldMaxEmailSizeMB, vs...))
}

// MaxEmailSizeMBGT applies the GT predicate on the "max_email_size_mb" field.
func MaxEmailSizeMBGT(v int) predicate.EmailPlan {
	return predicate.EmailPlan(sql.FieldGT(FieldMaxEmailSizeMB, v))
}

// MaxEmailSizeMBGTE applies the GTE predicate on the "max_email_size_mb" field.
func MaxEmailSizeMBGTE(v int) predicate.EmailPlan {
	return predicate.EmailPlan(sql.FieldGTE(FieldMaxEmailSizeMB, v))
}

// MaxEmailSizeMBLT applies the LT predicate on the "max_email_size_mb" field.
func MaxEmailSizeMBLT(v int) predicate.EmailPlan {
	return predicate.EmailPlan(sql.FieldLT(FieldMaxEmailSizeMB, v))
}

// MaxEmailSizeMBLTE applies the LTE predicate on the "max_email_size_mb" field.
func MaxEmailSizeMBLTE(v int) predicate.EmailPlan {
	return predicate.EmailPlan(sql.FieldLTE(FieldMaxEmailSizeMB, v))
}

// IsActiveEQ applies the EQ predicate on the "is_active" field.
func IsActiveEQ(v bool) predicate.EmailPlan {
	return predicate.EmailPlan(sql.FieldEQ(FieldIsActive, v))
}

// IsActiveNEQ applies the NEQ predicate on the "is_active" field.
func IsActiveNEQ(v bool) predicate.EmailPlan {
	return predicate.EmailPlan(sql.FieldNEQ(FieldIsActive, v))
}

// IsPublicEQ applies the EQ predicate on the "is_public" field.
func IsPublicEQ(v bool) predicate.EmailPlan {
	return predicate.EmailPlan(sql.FieldEQ(FieldIsPublic, v))
}

// IsPublicNEQ applies the NEQ predicate on the "is_public" field.
func IsPublicNEQ(v bool) predicate.EmailPlan {
	return predicate.EmailPlan(sql.FieldNEQ(FieldIsPublic, v))
}

// SortOrderEQ applies the EQ predicate on the "sort_order" field.
func SortOrderEQ(v int) predicate.EmailPlan {
	return predicate.EmailPlan(sql.FieldEQ(FieldSortOrder, v))
}

// SortOrderNEQ applies the NEQ predicate on the "sort_order" field.
func SortOrderNEQ(v int) predicate.EmailPlan {
	return predicate.EmailPlan(sql.FieldNEQ(FieldSortOrder, v))
}

// SortOrderIn applies the In predicate on the "sort_order" field.
func SortOrderIn(vs ...int) predicate.EmailPlan {
	return predicate.EmailPlan(sql.FieldIn(FieldSortOrder, vs...))
}

// SortOrderNotIn applies the NotIn predicate on the "sort_order" field.
func SortOrderNotIn(vs ...int) predicate.EmailPlan {
	return predicate.EmailPlan(sql.FieldNotIn(FieldSortOrder, vs...))
}

// SortOrderGT applies the GT predicate on the "sort_order" field.
func SortOrderGT(v int) predicate.EmailPlan {
	return predicate.EmailPlan(sql.FieldGT(FieldSortOrder, v))
}

// SortOrderGTE applies the GTE predicate on the "sort_order" field.
func SortOrderGTE(v int) predicate.EmailPlan {
	return predicate.EmailPlan(sql.FieldGTE(FieldSortOrder, v))
}

// SortOrderLT applies the LT predicate on the "sort_order" field.
func SortOrderLT(v int) predicate.EmailPlan {
	return predicate.EmailPlan(sql.FieldLT(FieldSortOrder, v))
}

// SortOrderLTE applies the LTE predicate on the "sort_order" field.
func SortOrderLTE(v int) predicate.EmailPlan {
	return predicate.EmailPlan(sql.FieldLTE(FieldSortOrder, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.EmailPlan {
	return predicate.EmailPlan(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.EmailPlan {
	return predicate.EmailPlan(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.EmailPlan {
	return predicate.EmailPlan(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.EmailPlan {
	return predicate.EmailPlan(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.EmailPlan {
	return predicate.EmailPlan(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.EmailPlan {
	return predicate.EmailPlan(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.EmailPlan {
	return predicate.EmailPlan(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.EmailPlan {
	return predicate.EmailPlan(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.EmailPlan {
	return predicate.EmailPlan(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.EmailPlan {
	return predicate.EmailPlan(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.EmailPlan {
	return predicate.EmailPlan(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.EmailPlan {
	return predicate.EmailPlan(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.EmailPlan {
	return predicate.EmailPlan(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.EmailPlan {
	return predicate.EmailPlan(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.EmailPlan {
	return predicate.EmailPlan(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.EmailPlan {
	return predicate.EmailPlan(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasLicenses applies the HasEdge predicate on the "licenses" edge.
func HasLicenses() predicate.EmailPlan {
	return predicate.EmailPlan(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, LicensesTable, LicensesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasLicensesWith applies the HasEdge predicate on the "licenses" edge with a given conditions (other predicates).
func HasLicensesWith(preds ...predicate.EmailLicense) predicate.EmailPlan {
	return predicate.EmailPlan(func(s *sql.Selector) {
		step := newLicensesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.EmailPlan) predicate.EmailPlan {
	return predicate.EmailPlan(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.EmailPlan) predicate.EmailPlan {
	return predicate.EmailPlan(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.EmailPlan) predicate.EmailPlan {
	return predicate.EmailPlan(sql.NotPredicates(p))
}
