-- Create "rate_limit_configs" table
CREATE TABLE "rate_limit_configs" ("id" uuid NOT NULL, "service_name" character varying NOT NULL, "key_type" character varying NOT NULL, "endpoint_pattern" character varying NOT NULL DEFAULT '*', "requests_per_window" bigint NOT NULL DEFAULT 60, "window_seconds" bigint NOT NULL DEFAULT 60, "burst_multiplier" double precision NOT NULL DEFAULT 1.5, "is_active" boolean NOT NULL DEFAULT true, "description" character varying NULL, "created_at" timestamptz NOT NULL, "updated_at" timestamptz NOT NULL, PRIMARY KEY ("id"));
-- Create index "ratelimitconfig_is_active" to table: "rate_limit_configs"
CREATE INDEX "ratelimitconfig_is_active" ON "rate_limit_configs" ("is_active");
-- Create index "ratelimitconfig_service_name" to table: "rate_limit_configs"
CREATE INDEX "ratelimitconfig_service_name" ON "rate_limit_configs" ("service_name");
-- Create index "ratelimitconfig_service_name_key_type_endpoint_pattern" to table: "rate_limit_configs"
CREATE UNIQUE INDEX "ratelimitconfig_service_name_key_type_endpoint_pattern" ON "rate_limit_configs" ("service_name", "key_type", "endpoint_pattern");
-- Create "service_configs" table
CREATE TABLE "service_configs" ("id" uuid NOT NULL, "tenant_id" uuid NULL, "config_key" character varying NOT NULL, "config_value" text NOT NULL, "config_type" character varying NOT NULL DEFAULT 'string', "description" character varying NULL, "is_secret" boolean NOT NULL DEFAULT false, "created_at" timestamptz NOT NULL, "updated_at" timestamptz NOT NULL, PRIMARY KEY ("id"));
-- Create index "serviceconfig_config_key" to table: "service_configs"
CREATE INDEX "serviceconfig_config_key" ON "service_configs" ("config_key");
-- Create index "serviceconfig_tenant_id_config_key" to table: "service_configs"
CREATE UNIQUE INDEX "serviceconfig_tenant_id_config_key" ON "service_configs" ("tenant_id", "config_key");
-- Create "subscriptions_permissions" table
CREATE TABLE "subscriptions_permissions" ("id" uuid NOT NULL, "permission_code" character varying NOT NULL, "name" character varying NOT NULL, "module" character varying NOT NULL, "action" character varying NOT NULL, "resource" character varying NULL, "description" text NULL, "created_at" timestamptz NOT NULL, PRIMARY KEY ("id"));
-- Create index "subscriptions_permissions_permission_code_key" to table: "subscriptions_permissions"
CREATE UNIQUE INDEX "subscriptions_permissions_permission_code_key" ON "subscriptions_permissions" ("permission_code");
-- Create index "subscriptionspermission_action" to table: "subscriptions_permissions"
CREATE INDEX "subscriptionspermission_action" ON "subscriptions_permissions" ("action");
-- Create index "subscriptionspermission_module" to table: "subscriptions_permissions"
CREATE INDEX "subscriptionspermission_module" ON "subscriptions_permissions" ("module");
-- Create index "subscriptionspermission_module_action" to table: "subscriptions_permissions"
CREATE INDEX "subscriptionspermission_module_action" ON "subscriptions_permissions" ("module", "action");
-- Create index "subscriptionspermission_permission_code" to table: "subscriptions_permissions"
CREATE UNIQUE INDEX "subscriptionspermission_permission_code" ON "subscriptions_permissions" ("permission_code");
-- Create "subscriptions_roles" table
CREATE TABLE "subscriptions_roles" ("id" uuid NOT NULL, "tenant_id" uuid NOT NULL, "role_code" character varying NOT NULL, "name" character varying NOT NULL, "description" text NULL, "is_system_role" boolean NOT NULL DEFAULT false, "created_at" timestamptz NOT NULL, "updated_at" timestamptz NOT NULL, PRIMARY KEY ("id"));
-- Create index "subscriptionsrole_is_system_role" to table: "subscriptions_roles"
CREATE INDEX "subscriptionsrole_is_system_role" ON "subscriptions_roles" ("is_system_role");
-- Create index "subscriptionsrole_tenant_id" to table: "subscriptions_roles"
CREATE INDEX "subscriptionsrole_tenant_id" ON "subscriptions_roles" ("tenant_id");
-- Create index "subscriptionsrole_tenant_id_role_code" to table: "subscriptions_roles"
CREATE UNIQUE INDEX "subscriptionsrole_tenant_id_role_code" ON "subscriptions_roles" ("tenant_id", "role_code");
-- Create "role_permissions" table
CREATE TABLE "role_permissions" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "role_id" uuid NOT NULL, "permission_id" uuid NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "role_permissions_subscriptions_permissions_permission" FOREIGN KEY ("permission_id") REFERENCES "subscriptions_permissions" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION, CONSTRAINT "role_permissions_subscriptions_roles_role" FOREIGN KEY ("role_id") REFERENCES "subscriptions_roles" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION);
-- Create index "rolepermission_permission_id" to table: "role_permissions"
CREATE INDEX "rolepermission_permission_id" ON "role_permissions" ("permission_id");
-- Create index "rolepermission_role_id" to table: "role_permissions"
CREATE INDEX "rolepermission_role_id" ON "role_permissions" ("role_id");
-- Create index "rolepermission_role_id_permission_id" to table: "role_permissions"
CREATE UNIQUE INDEX "rolepermission_role_id_permission_id" ON "role_permissions" ("role_id", "permission_id");
-- Create "subscriptions_users" table
CREATE TABLE "subscriptions_users" ("id" uuid NOT NULL, "tenant_id" uuid NOT NULL, "auth_service_user_id" uuid NOT NULL, "email" character varying NOT NULL, "status" character varying NOT NULL DEFAULT 'active', "sync_status" character varying NOT NULL DEFAULT 'synced', "last_sync_at" timestamptz NULL, "created_at" timestamptz NOT NULL, "updated_at" timestamptz NOT NULL, PRIMARY KEY ("id"));
-- Create index "subscriptions_users_auth_service_user_id_key" to table: "subscriptions_users"
CREATE UNIQUE INDEX "subscriptions_users_auth_service_user_id_key" ON "subscriptions_users" ("auth_service_user_id");
-- Create index "subscriptionsuser_auth_service_user_id" to table: "subscriptions_users"
CREATE UNIQUE INDEX "subscriptionsuser_auth_service_user_id" ON "subscriptions_users" ("auth_service_user_id");
-- Create index "subscriptionsuser_status" to table: "subscriptions_users"
CREATE INDEX "subscriptionsuser_status" ON "subscriptions_users" ("status");
-- Create index "subscriptionsuser_sync_status" to table: "subscriptions_users"
CREATE INDEX "subscriptionsuser_sync_status" ON "subscriptions_users" ("sync_status");
-- Create index "subscriptionsuser_tenant_id" to table: "subscriptions_users"
CREATE INDEX "subscriptionsuser_tenant_id" ON "subscriptions_users" ("tenant_id");
-- Create index "subscriptionsuser_tenant_id_auth_service_user_id" to table: "subscriptions_users"
CREATE UNIQUE INDEX "subscriptionsuser_tenant_id_auth_service_user_id" ON "subscriptions_users" ("tenant_id", "auth_service_user_id");
-- Create "user_role_assignments" table
CREATE TABLE "user_role_assignments" ("id" uuid NOT NULL, "tenant_id" uuid NOT NULL, "assigned_by" uuid NOT NULL, "assigned_at" timestamptz NOT NULL, "expires_at" timestamptz NULL, "subscriptions_role_user_assignments" uuid NULL, "user_id" uuid NOT NULL, "role_id" uuid NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "user_role_assignments_subscriptions_roles_role" FOREIGN KEY ("role_id") REFERENCES "subscriptions_roles" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION, CONSTRAINT "user_role_assignments_subscriptions_roles_user_assignments" FOREIGN KEY ("subscriptions_role_user_assignments") REFERENCES "subscriptions_roles" ("id") ON UPDATE NO ACTION ON DELETE SET NULL, CONSTRAINT "user_role_assignments_subscriptions_users_user" FOREIGN KEY ("user_id") REFERENCES "subscriptions_users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION);
-- Create index "userroleassignment_expires_at" to table: "user_role_assignments"
CREATE INDEX "userroleassignment_expires_at" ON "user_role_assignments" ("expires_at");
-- Create index "userroleassignment_role_id" to table: "user_role_assignments"
CREATE INDEX "userroleassignment_role_id" ON "user_role_assignments" ("role_id");
-- Create index "userroleassignment_tenant_id" to table: "user_role_assignments"
CREATE INDEX "userroleassignment_tenant_id" ON "user_role_assignments" ("tenant_id");
-- Create index "userroleassignment_tenant_id_user_id_role_id" to table: "user_role_assignments"
CREATE UNIQUE INDEX "userroleassignment_tenant_id_user_id_role_id" ON "user_role_assignments" ("tenant_id", "user_id", "role_id");
-- Create index "userroleassignment_user_id" to table: "user_role_assignments"
CREATE INDEX "userroleassignment_user_id" ON "user_role_assignments" ("user_id");
