// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/bengobox/subscription-service/internal/ent/apitokenwallet"
	"github.com/google/uuid"
)

// ApiTokenWallet is the model entity for the ApiTokenWallet schema.
type ApiTokenWallet struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// One wallet per (tenant, service_tag)
	TenantID uuid.UUID `json:"tenant_id,omitempty"`
	// Which external API product this wallet meters, e.g. etims_api
	ServiceTag string `json:"service_tag,omitempty"`
	// Current spendable token balance
	Balance int64 `json:"balance,omitempty"`
	// Cumulative tokens ever granted or purchased (for display/analytics only)
	LifetimeGranted int64 `json:"lifetime_granted,omitempty"`
	// Balance at/below which a low-balance warning is surfaced to the tenant
	LowBalanceThreshold int64 `json:"low_balance_threshold,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ApiTokenWalletQuery when eager-loading is set.
	Edges        ApiTokenWalletEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ApiTokenWalletEdges holds the relations/edges for other nodes in the graph.
type ApiTokenWalletEdges struct {
	// Transactions holds the value of the transactions edge.
	Transactions []*ApiTokenTransaction `json:"transactions,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// TransactionsOrErr returns the Transactions value or an error if the edge
// was not loaded in eager-loading.
func (e ApiTokenWalletEdges) TransactionsOrErr() ([]*ApiTokenTransaction, error) {
	if e.loadedTypes[0] {
		return e.Transactions, nil
	}
	return nil, &NotLoadedError{edge: "transactions"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ApiTokenWallet) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case apitokenwallet.FieldBalance, apitokenwallet.FieldLifetimeGranted, apitokenwallet.FieldLowBalanceThreshold:
			values[i] = new(sql.NullInt64)
		case apitokenwallet.FieldServiceTag:
			values[i] = new(sql.NullString)
		case apitokenwallet.FieldCreatedAt, apitokenwallet.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case apitokenwallet.FieldID, apitokenwallet.FieldTenantID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ApiTokenWallet fields.
func (_m *ApiTokenWallet) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case apitokenwallet.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case apitokenwallet.FieldTenantID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field tenant_id", values[i])
			} else if value != nil {
				_m.TenantID = *value
			}
		case apitokenwallet.FieldServiceTag:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field service_tag", values[i])
			} else if value.Valid {
				_m.ServiceTag = value.String
			}
		case apitokenwallet.FieldBalance:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field balance", values[i])
			} else if value.Valid {
				_m.Balance = value.Int64
			}
		case apitokenwallet.FieldLifetimeGranted:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field lifetime_granted", values[i])
			} else if value.Valid {
				_m.LifetimeGranted = value.Int64
			}
		case apitokenwallet.FieldLowBalanceThreshold:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field low_balance_threshold", values[i])
			} else if value.Valid {
				_m.LowBalanceThreshold = value.Int64
			}
		case apitokenwallet.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case apitokenwallet.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ApiTokenWallet.
// This includes values selected through modifiers, order, etc.
func (_m *ApiTokenWallet) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryTransactions queries the "transactions" edge of the ApiTokenWallet entity.
func (_m *ApiTokenWallet) QueryTransactions() *ApiTokenTransactionQuery {
	return NewApiTokenWalletClient(_m.config).QueryTransactions(_m)
}

// Update returns a builder for updating this ApiTokenWallet.
// Note that you need to call ApiTokenWallet.Unwrap() before calling this method if this ApiTokenWallet
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ApiTokenWallet) Update() *ApiTokenWalletUpdateOne {
	return NewApiTokenWalletClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ApiTokenWallet entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ApiTokenWallet) Unwrap() *ApiTokenWallet {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ApiTokenWallet is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ApiTokenWallet) String() string {
	var builder strings.Builder
	builder.WriteString("ApiTokenWallet(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("tenant_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.TenantID))
	builder.WriteString(", ")
	builder.WriteString("service_tag=")
	builder.WriteString(_m.ServiceTag)
	builder.WriteString(", ")
	builder.WriteString("balance=")
	builder.WriteString(fmt.Sprintf("%v", _m.Balance))
	builder.WriteString(", ")
	builder.WriteString("lifetime_granted=")
	builder.WriteString(fmt.Sprintf("%v", _m.LifetimeGranted))
	builder.WriteString(", ")
	builder.WriteString("low_balance_threshold=")
	builder.WriteString(fmt.Sprintf("%v", _m.LowBalanceThreshold))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// ApiTokenWallets is a parsable slice of ApiTokenWallet.
type ApiTokenWallets []*ApiTokenWallet
