// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/bengobox/subscription-service/internal/ent/bundle"
	"github.com/bengobox/subscription-service/internal/ent/schema"
	"github.com/google/uuid"
)

// Bundle is the model entity for the Bundle schema.
type Bundle struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// Unique bundle code (delivery, pos-suite, complete)
	Code string `json:"code,omitempty"`
	// Display name
	Name string `json:"name,omitempty"`
	// Description holds the value of the "description" field.
	Description string `json:"description,omitempty"`
	// Products included in this bundle
	Products []schema.BundleProduct `json:"products,omitempty"`
	// Pricing per tier for this bundle
	Tiers []schema.BundleTier `json:"tiers,omitempty"`
	// How bundle discount is calculated vs individual product prices
	DiscountType bundle.DiscountType `json:"discount_type,omitempty"`
	// Discount amount (percentage or fixed KES)
	DiscountValue float64 `json:"discount_value,omitempty"`
	// IsActive holds the value of the "is_active" field.
	IsActive bool `json:"is_active,omitempty"`
	// Default bundle assigned to new tenants on signup
	IsDefault bool `json:"is_default,omitempty"`
	// SortOrder holds the value of the "sort_order" field.
	SortOrder int `json:"sort_order,omitempty"`
	// Metadata holds the value of the "metadata" field.
	Metadata map[string]interface{} `json:"metadata,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Bundle) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case bundle.FieldProducts, bundle.FieldTiers, bundle.FieldMetadata:
			values[i] = new([]byte)
		case bundle.FieldIsActive, bundle.FieldIsDefault:
			values[i] = new(sql.NullBool)
		case bundle.FieldDiscountValue:
			values[i] = new(sql.NullFloat64)
		case bundle.FieldSortOrder:
			values[i] = new(sql.NullInt64)
		case bundle.FieldCode, bundle.FieldName, bundle.FieldDescription, bundle.FieldDiscountType:
			values[i] = new(sql.NullString)
		case bundle.FieldCreatedAt, bundle.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case bundle.FieldID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Bundle fields.
func (b *Bundle) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case bundle.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				b.ID = *value
			}
		case bundle.FieldCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field code", values[i])
			} else if value.Valid {
				b.Code = value.String
			}
		case bundle.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				b.Name = value.String
			}
		case bundle.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				b.Description = value.String
			}
		case bundle.FieldProducts:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field products", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &b.Products); err != nil {
					return fmt.Errorf("unmarshal field products: %w", err)
				}
			}
		case bundle.FieldTiers:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field tiers", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &b.Tiers); err != nil {
					return fmt.Errorf("unmarshal field tiers: %w", err)
				}
			}
		case bundle.FieldDiscountType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field discount_type", values[i])
			} else if value.Valid {
				b.DiscountType = bundle.DiscountType(value.String)
			}
		case bundle.FieldDiscountValue:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field discount_value", values[i])
			} else if value.Valid {
				b.DiscountValue = value.Float64
			}
		case bundle.FieldIsActive:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_active", values[i])
			} else if value.Valid {
				b.IsActive = value.Bool
			}
		case bundle.FieldIsDefault:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_default", values[i])
			} else if value.Valid {
				b.IsDefault = value.Bool
			}
		case bundle.FieldSortOrder:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field sort_order", values[i])
			} else if value.Valid {
				b.SortOrder = int(value.Int64)
			}
		case bundle.FieldMetadata:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field metadata", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &b.Metadata); err != nil {
					return fmt.Errorf("unmarshal field metadata: %w", err)
				}
			}
		case bundle.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				b.CreatedAt = value.Time
			}
		case bundle.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				b.UpdatedAt = value.Time
			}
		default:
			b.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Bundle.
// This includes values selected through modifiers, order, etc.
func (b *Bundle) Value(name string) (ent.Value, error) {
	return b.selectValues.Get(name)
}

// Update returns a builder for updating this Bundle.
// Note that you need to call Bundle.Unwrap() before calling this method if this Bundle
// was returned from a transaction, and the transaction was committed or rolled back.
func (b *Bundle) Update() *BundleUpdateOne {
	return NewBundleClient(b.config).UpdateOne(b)
}

// Unwrap unwraps the Bundle entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (b *Bundle) Unwrap() *Bundle {
	_tx, ok := b.config.driver.(*txDriver)
	if !ok {
		panic("ent: Bundle is not a transactional entity")
	}
	b.config.driver = _tx.drv
	return b
}

// String implements the fmt.Stringer.
func (b *Bundle) String() string {
	var builder strings.Builder
	builder.WriteString("Bundle(")
	builder.WriteString(fmt.Sprintf("id=%v, ", b.ID))
	builder.WriteString("code=")
	builder.WriteString(b.Code)
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(b.Name)
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(b.Description)
	builder.WriteString(", ")
	builder.WriteString("products=")
	builder.WriteString(fmt.Sprintf("%v", b.Products))
	builder.WriteString(", ")
	builder.WriteString("tiers=")
	builder.WriteString(fmt.Sprintf("%v", b.Tiers))
	builder.WriteString(", ")
	builder.WriteString("discount_type=")
	builder.WriteString(fmt.Sprintf("%v", b.DiscountType))
	builder.WriteString(", ")
	builder.WriteString("discount_value=")
	builder.WriteString(fmt.Sprintf("%v", b.DiscountValue))
	builder.WriteString(", ")
	builder.WriteString("is_active=")
	builder.WriteString(fmt.Sprintf("%v", b.IsActive))
	builder.WriteString(", ")
	builder.WriteString("is_default=")
	builder.WriteString(fmt.Sprintf("%v", b.IsDefault))
	builder.WriteString(", ")
	builder.WriteString("sort_order=")
	builder.WriteString(fmt.Sprintf("%v", b.SortOrder))
	builder.WriteString(", ")
	builder.WriteString("metadata=")
	builder.WriteString(fmt.Sprintf("%v", b.Metadata))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(b.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(b.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Bundles is a parsable slice of Bundle.
type Bundles []*Bundle
