// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/bengobox/subscription-service/internal/ent/bundle"
	"github.com/bengobox/subscription-service/internal/ent/predicate"
	"github.com/bengobox/subscription-service/internal/ent/schema"
)

// BundleUpdate is the builder for updating Bundle entities.
type BundleUpdate struct {
	config
	hooks    []Hook
	mutation *BundleMutation
}

// Where appends a list predicates to the BundleUpdate builder.
func (bu *BundleUpdate) Where(ps ...predicate.Bundle) *BundleUpdate {
	bu.mutation.Where(ps...)
	return bu
}

// SetCode sets the "code" field.
func (bu *BundleUpdate) SetCode(s string) *BundleUpdate {
	bu.mutation.SetCode(s)
	return bu
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (bu *BundleUpdate) SetNillableCode(s *string) *BundleUpdate {
	if s != nil {
		bu.SetCode(*s)
	}
	return bu
}

// SetName sets the "name" field.
func (bu *BundleUpdate) SetName(s string) *BundleUpdate {
	bu.mutation.SetName(s)
	return bu
}

// SetNillableName sets the "name" field if the given value is not nil.
func (bu *BundleUpdate) SetNillableName(s *string) *BundleUpdate {
	if s != nil {
		bu.SetName(*s)
	}
	return bu
}

// SetDescription sets the "description" field.
func (bu *BundleUpdate) SetDescription(s string) *BundleUpdate {
	bu.mutation.SetDescription(s)
	return bu
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (bu *BundleUpdate) SetNillableDescription(s *string) *BundleUpdate {
	if s != nil {
		bu.SetDescription(*s)
	}
	return bu
}

// ClearDescription clears the value of the "description" field.
func (bu *BundleUpdate) ClearDescription() *BundleUpdate {
	bu.mutation.ClearDescription()
	return bu
}

// SetProducts sets the "products" field.
func (bu *BundleUpdate) SetProducts(sp []schema.BundleProduct) *BundleUpdate {
	bu.mutation.SetProducts(sp)
	return bu
}

// AppendProducts appends sp to the "products" field.
func (bu *BundleUpdate) AppendProducts(sp []schema.BundleProduct) *BundleUpdate {
	bu.mutation.AppendProducts(sp)
	return bu
}

// SetTiers sets the "tiers" field.
func (bu *BundleUpdate) SetTiers(st []schema.BundleTier) *BundleUpdate {
	bu.mutation.SetTiers(st)
	return bu
}

// AppendTiers appends st to the "tiers" field.
func (bu *BundleUpdate) AppendTiers(st []schema.BundleTier) *BundleUpdate {
	bu.mutation.AppendTiers(st)
	return bu
}

// SetDiscountType sets the "discount_type" field.
func (bu *BundleUpdate) SetDiscountType(bt bundle.DiscountType) *BundleUpdate {
	bu.mutation.SetDiscountType(bt)
	return bu
}

// SetNillableDiscountType sets the "discount_type" field if the given value is not nil.
func (bu *BundleUpdate) SetNillableDiscountType(bt *bundle.DiscountType) *BundleUpdate {
	if bt != nil {
		bu.SetDiscountType(*bt)
	}
	return bu
}

// SetDiscountValue sets the "discount_value" field.
func (bu *BundleUpdate) SetDiscountValue(f float64) *BundleUpdate {
	bu.mutation.ResetDiscountValue()
	bu.mutation.SetDiscountValue(f)
	return bu
}

// SetNillableDiscountValue sets the "discount_value" field if the given value is not nil.
func (bu *BundleUpdate) SetNillableDiscountValue(f *float64) *BundleUpdate {
	if f != nil {
		bu.SetDiscountValue(*f)
	}
	return bu
}

// AddDiscountValue adds f to the "discount_value" field.
func (bu *BundleUpdate) AddDiscountValue(f float64) *BundleUpdate {
	bu.mutation.AddDiscountValue(f)
	return bu
}

// SetIsActive sets the "is_active" field.
func (bu *BundleUpdate) SetIsActive(b bool) *BundleUpdate {
	bu.mutation.SetIsActive(b)
	return bu
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (bu *BundleUpdate) SetNillableIsActive(b *bool) *BundleUpdate {
	if b != nil {
		bu.SetIsActive(*b)
	}
	return bu
}

// SetIsDefault sets the "is_default" field.
func (bu *BundleUpdate) SetIsDefault(b bool) *BundleUpdate {
	bu.mutation.SetIsDefault(b)
	return bu
}

// SetNillableIsDefault sets the "is_default" field if the given value is not nil.
func (bu *BundleUpdate) SetNillableIsDefault(b *bool) *BundleUpdate {
	if b != nil {
		bu.SetIsDefault(*b)
	}
	return bu
}

// SetSortOrder sets the "sort_order" field.
func (bu *BundleUpdate) SetSortOrder(i int) *BundleUpdate {
	bu.mutation.ResetSortOrder()
	bu.mutation.SetSortOrder(i)
	return bu
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (bu *BundleUpdate) SetNillableSortOrder(i *int) *BundleUpdate {
	if i != nil {
		bu.SetSortOrder(*i)
	}
	return bu
}

// AddSortOrder adds i to the "sort_order" field.
func (bu *BundleUpdate) AddSortOrder(i int) *BundleUpdate {
	bu.mutation.AddSortOrder(i)
	return bu
}

// SetMetadata sets the "metadata" field.
func (bu *BundleUpdate) SetMetadata(m map[string]interface{}) *BundleUpdate {
	bu.mutation.SetMetadata(m)
	return bu
}

// SetUpdatedAt sets the "updated_at" field.
func (bu *BundleUpdate) SetUpdatedAt(t time.Time) *BundleUpdate {
	bu.mutation.SetUpdatedAt(t)
	return bu
}

// Mutation returns the BundleMutation object of the builder.
func (bu *BundleUpdate) Mutation() *BundleMutation {
	return bu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (bu *BundleUpdate) Save(ctx context.Context) (int, error) {
	bu.defaults()
	return withHooks(ctx, bu.sqlSave, bu.mutation, bu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (bu *BundleUpdate) SaveX(ctx context.Context) int {
	affected, err := bu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (bu *BundleUpdate) Exec(ctx context.Context) error {
	_, err := bu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (bu *BundleUpdate) ExecX(ctx context.Context) {
	if err := bu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (bu *BundleUpdate) defaults() {
	if _, ok := bu.mutation.UpdatedAt(); !ok {
		v := bundle.UpdateDefaultUpdatedAt()
		bu.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (bu *BundleUpdate) check() error {
	if v, ok := bu.mutation.Code(); ok {
		if err := bundle.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "Bundle.code": %w`, err)}
		}
	}
	if v, ok := bu.mutation.Name(); ok {
		if err := bundle.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Bundle.name": %w`, err)}
		}
	}
	if v, ok := bu.mutation.DiscountType(); ok {
		if err := bundle.DiscountTypeValidator(v); err != nil {
			return &ValidationError{Name: "discount_type", err: fmt.Errorf(`ent: validator failed for field "Bundle.discount_type": %w`, err)}
		}
	}
	return nil
}

func (bu *BundleUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := bu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(bundle.Table, bundle.Columns, sqlgraph.NewFieldSpec(bundle.FieldID, field.TypeUUID))
	if ps := bu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := bu.mutation.Code(); ok {
		_spec.SetField(bundle.FieldCode, field.TypeString, value)
	}
	if value, ok := bu.mutation.Name(); ok {
		_spec.SetField(bundle.FieldName, field.TypeString, value)
	}
	if value, ok := bu.mutation.Description(); ok {
		_spec.SetField(bundle.FieldDescription, field.TypeString, value)
	}
	if bu.mutation.DescriptionCleared() {
		_spec.ClearField(bundle.FieldDescription, field.TypeString)
	}
	if value, ok := bu.mutation.Products(); ok {
		_spec.SetField(bundle.FieldProducts, field.TypeJSON, value)
	}
	if value, ok := bu.mutation.AppendedProducts(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, bundle.FieldProducts, value)
		})
	}
	if value, ok := bu.mutation.Tiers(); ok {
		_spec.SetField(bundle.FieldTiers, field.TypeJSON, value)
	}
	if value, ok := bu.mutation.AppendedTiers(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, bundle.FieldTiers, value)
		})
	}
	if value, ok := bu.mutation.DiscountType(); ok {
		_spec.SetField(bundle.FieldDiscountType, field.TypeEnum, value)
	}
	if value, ok := bu.mutation.DiscountValue(); ok {
		_spec.SetField(bundle.FieldDiscountValue, field.TypeFloat64, value)
	}
	if value, ok := bu.mutation.AddedDiscountValue(); ok {
		_spec.AddField(bundle.FieldDiscountValue, field.TypeFloat64, value)
	}
	if value, ok := bu.mutation.IsActive(); ok {
		_spec.SetField(bundle.FieldIsActive, field.TypeBool, value)
	}
	if value, ok := bu.mutation.IsDefault(); ok {
		_spec.SetField(bundle.FieldIsDefault, field.TypeBool, value)
	}
	if value, ok := bu.mutation.SortOrder(); ok {
		_spec.SetField(bundle.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := bu.mutation.AddedSortOrder(); ok {
		_spec.AddField(bundle.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := bu.mutation.Metadata(); ok {
		_spec.SetField(bundle.FieldMetadata, field.TypeJSON, value)
	}
	if value, ok := bu.mutation.UpdatedAt(); ok {
		_spec.SetField(bundle.FieldUpdatedAt, field.TypeTime, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, bu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{bundle.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	bu.mutation.done = true
	return n, nil
}

// BundleUpdateOne is the builder for updating a single Bundle entity.
type BundleUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *BundleMutation
}

// SetCode sets the "code" field.
func (buo *BundleUpdateOne) SetCode(s string) *BundleUpdateOne {
	buo.mutation.SetCode(s)
	return buo
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (buo *BundleUpdateOne) SetNillableCode(s *string) *BundleUpdateOne {
	if s != nil {
		buo.SetCode(*s)
	}
	return buo
}

// SetName sets the "name" field.
func (buo *BundleUpdateOne) SetName(s string) *BundleUpdateOne {
	buo.mutation.SetName(s)
	return buo
}

// SetNillableName sets the "name" field if the given value is not nil.
func (buo *BundleUpdateOne) SetNillableName(s *string) *BundleUpdateOne {
	if s != nil {
		buo.SetName(*s)
	}
	return buo
}

// SetDescription sets the "description" field.
func (buo *BundleUpdateOne) SetDescription(s string) *BundleUpdateOne {
	buo.mutation.SetDescription(s)
	return buo
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (buo *BundleUpdateOne) SetNillableDescription(s *string) *BundleUpdateOne {
	if s != nil {
		buo.SetDescription(*s)
	}
	return buo
}

// ClearDescription clears the value of the "description" field.
func (buo *BundleUpdateOne) ClearDescription() *BundleUpdateOne {
	buo.mutation.ClearDescription()
	return buo
}

// SetProducts sets the "products" field.
func (buo *BundleUpdateOne) SetProducts(sp []schema.BundleProduct) *BundleUpdateOne {
	buo.mutation.SetProducts(sp)
	return buo
}

// AppendProducts appends sp to the "products" field.
func (buo *BundleUpdateOne) AppendProducts(sp []schema.BundleProduct) *BundleUpdateOne {
	buo.mutation.AppendProducts(sp)
	return buo
}

// SetTiers sets the "tiers" field.
func (buo *BundleUpdateOne) SetTiers(st []schema.BundleTier) *BundleUpdateOne {
	buo.mutation.SetTiers(st)
	return buo
}

// AppendTiers appends st to the "tiers" field.
func (buo *BundleUpdateOne) AppendTiers(st []schema.BundleTier) *BundleUpdateOne {
	buo.mutation.AppendTiers(st)
	return buo
}

// SetDiscountType sets the "discount_type" field.
func (buo *BundleUpdateOne) SetDiscountType(bt bundle.DiscountType) *BundleUpdateOne {
	buo.mutation.SetDiscountType(bt)
	return buo
}

// SetNillableDiscountType sets the "discount_type" field if the given value is not nil.
func (buo *BundleUpdateOne) SetNillableDiscountType(bt *bundle.DiscountType) *BundleUpdateOne {
	if bt != nil {
		buo.SetDiscountType(*bt)
	}
	return buo
}

// SetDiscountValue sets the "discount_value" field.
func (buo *BundleUpdateOne) SetDiscountValue(f float64) *BundleUpdateOne {
	buo.mutation.ResetDiscountValue()
	buo.mutation.SetDiscountValue(f)
	return buo
}

// SetNillableDiscountValue sets the "discount_value" field if the given value is not nil.
func (buo *BundleUpdateOne) SetNillableDiscountValue(f *float64) *BundleUpdateOne {
	if f != nil {
		buo.SetDiscountValue(*f)
	}
	return buo
}

// AddDiscountValue adds f to the "discount_value" field.
func (buo *BundleUpdateOne) AddDiscountValue(f float64) *BundleUpdateOne {
	buo.mutation.AddDiscountValue(f)
	return buo
}

// SetIsActive sets the "is_active" field.
func (buo *BundleUpdateOne) SetIsActive(b bool) *BundleUpdateOne {
	buo.mutation.SetIsActive(b)
	return buo
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (buo *BundleUpdateOne) SetNillableIsActive(b *bool) *BundleUpdateOne {
	if b != nil {
		buo.SetIsActive(*b)
	}
	return buo
}

// SetIsDefault sets the "is_default" field.
func (buo *BundleUpdateOne) SetIsDefault(b bool) *BundleUpdateOne {
	buo.mutation.SetIsDefault(b)
	return buo
}

// SetNillableIsDefault sets the "is_default" field if the given value is not nil.
func (buo *BundleUpdateOne) SetNillableIsDefault(b *bool) *BundleUpdateOne {
	if b != nil {
		buo.SetIsDefault(*b)
	}
	return buo
}

// SetSortOrder sets the "sort_order" field.
func (buo *BundleUpdateOne) SetSortOrder(i int) *BundleUpdateOne {
	buo.mutation.ResetSortOrder()
	buo.mutation.SetSortOrder(i)
	return buo
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (buo *BundleUpdateOne) SetNillableSortOrder(i *int) *BundleUpdateOne {
	if i != nil {
		buo.SetSortOrder(*i)
	}
	return buo
}

// AddSortOrder adds i to the "sort_order" field.
func (buo *BundleUpdateOne) AddSortOrder(i int) *BundleUpdateOne {
	buo.mutation.AddSortOrder(i)
	return buo
}

// SetMetadata sets the "metadata" field.
func (buo *BundleUpdateOne) SetMetadata(m map[string]interface{}) *BundleUpdateOne {
	buo.mutation.SetMetadata(m)
	return buo
}

// SetUpdatedAt sets the "updated_at" field.
func (buo *BundleUpdateOne) SetUpdatedAt(t time.Time) *BundleUpdateOne {
	buo.mutation.SetUpdatedAt(t)
	return buo
}

// Mutation returns the BundleMutation object of the builder.
func (buo *BundleUpdateOne) Mutation() *BundleMutation {
	return buo.mutation
}

// Where appends a list predicates to the BundleUpdate builder.
func (buo *BundleUpdateOne) Where(ps ...predicate.Bundle) *BundleUpdateOne {
	buo.mutation.Where(ps...)
	return buo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (buo *BundleUpdateOne) Select(field string, fields ...string) *BundleUpdateOne {
	buo.fields = append([]string{field}, fields...)
	return buo
}

// Save executes the query and returns the updated Bundle entity.
func (buo *BundleUpdateOne) Save(ctx context.Context) (*Bundle, error) {
	buo.defaults()
	return withHooks(ctx, buo.sqlSave, buo.mutation, buo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (buo *BundleUpdateOne) SaveX(ctx context.Context) *Bundle {
	node, err := buo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (buo *BundleUpdateOne) Exec(ctx context.Context) error {
	_, err := buo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (buo *BundleUpdateOne) ExecX(ctx context.Context) {
	if err := buo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (buo *BundleUpdateOne) defaults() {
	if _, ok := buo.mutation.UpdatedAt(); !ok {
		v := bundle.UpdateDefaultUpdatedAt()
		buo.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (buo *BundleUpdateOne) check() error {
	if v, ok := buo.mutation.Code(); ok {
		if err := bundle.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "Bundle.code": %w`, err)}
		}
	}
	if v, ok := buo.mutation.Name(); ok {
		if err := bundle.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Bundle.name": %w`, err)}
		}
	}
	if v, ok := buo.mutation.DiscountType(); ok {
		if err := bundle.DiscountTypeValidator(v); err != nil {
			return &ValidationError{Name: "discount_type", err: fmt.Errorf(`ent: validator failed for field "Bundle.discount_type": %w`, err)}
		}
	}
	return nil
}

func (buo *BundleUpdateOne) sqlSave(ctx context.Context) (_node *Bundle, err error) {
	if err := buo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(bundle.Table, bundle.Columns, sqlgraph.NewFieldSpec(bundle.FieldID, field.TypeUUID))
	id, ok := buo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Bundle.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := buo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, bundle.FieldID)
		for _, f := range fields {
			if !bundle.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != bundle.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := buo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := buo.mutation.Code(); ok {
		_spec.SetField(bundle.FieldCode, field.TypeString, value)
	}
	if value, ok := buo.mutation.Name(); ok {
		_spec.SetField(bundle.FieldName, field.TypeString, value)
	}
	if value, ok := buo.mutation.Description(); ok {
		_spec.SetField(bundle.FieldDescription, field.TypeString, value)
	}
	if buo.mutation.DescriptionCleared() {
		_spec.ClearField(bundle.FieldDescription, field.TypeString)
	}
	if value, ok := buo.mutation.Products(); ok {
		_spec.SetField(bundle.FieldProducts, field.TypeJSON, value)
	}
	if value, ok := buo.mutation.AppendedProducts(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, bundle.FieldProducts, value)
		})
	}
	if value, ok := buo.mutation.Tiers(); ok {
		_spec.SetField(bundle.FieldTiers, field.TypeJSON, value)
	}
	if value, ok := buo.mutation.AppendedTiers(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, bundle.FieldTiers, value)
		})
	}
	if value, ok := buo.mutation.DiscountType(); ok {
		_spec.SetField(bundle.FieldDiscountType, field.TypeEnum, value)
	}
	if value, ok := buo.mutation.DiscountValue(); ok {
		_spec.SetField(bundle.FieldDiscountValue, field.TypeFloat64, value)
	}
	if value, ok := buo.mutation.AddedDiscountValue(); ok {
		_spec.AddField(bundle.FieldDiscountValue, field.TypeFloat64, value)
	}
	if value, ok := buo.mutation.IsActive(); ok {
		_spec.SetField(bundle.FieldIsActive, field.TypeBool, value)
	}
	if value, ok := buo.mutation.IsDefault(); ok {
		_spec.SetField(bundle.FieldIsDefault, field.TypeBool, value)
	}
	if value, ok := buo.mutation.SortOrder(); ok {
		_spec.SetField(bundle.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := buo.mutation.AddedSortOrder(); ok {
		_spec.AddField(bundle.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := buo.mutation.Metadata(); ok {
		_spec.SetField(bundle.FieldMetadata, field.TypeJSON, value)
	}
	if value, ok := buo.mutation.UpdatedAt(); ok {
		_spec.SetField(bundle.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &Bundle{config: buo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, buo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{bundle.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	buo.mutation.done = true
	return _node, nil
}
