// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/bengobox/subscription-service/internal/ent/featuredefinition"
	"github.com/google/uuid"
)

// FeatureDefinitionCreate is the builder for creating a FeatureDefinition entity.
type FeatureDefinitionCreate struct {
	config
	mutation *FeatureDefinitionMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetFeatureCode sets the "feature_code" field.
func (_c *FeatureDefinitionCreate) SetFeatureCode(v string) *FeatureDefinitionCreate {
	_c.mutation.SetFeatureCode(v)
	return _c
}

// SetServiceTag sets the "service_tag" field.
func (_c *FeatureDefinitionCreate) SetServiceTag(v string) *FeatureDefinitionCreate {
	_c.mutation.SetServiceTag(v)
	return _c
}

// SetCategory sets the "category" field.
func (_c *FeatureDefinitionCreate) SetCategory(v string) *FeatureDefinitionCreate {
	_c.mutation.SetCategory(v)
	return _c
}

// SetNillableCategory sets the "category" field if the given value is not nil.
func (_c *FeatureDefinitionCreate) SetNillableCategory(v *string) *FeatureDefinitionCreate {
	if v != nil {
		_c.SetCategory(*v)
	}
	return _c
}

// SetLabel sets the "label" field.
func (_c *FeatureDefinitionCreate) SetLabel(v string) *FeatureDefinitionCreate {
	_c.mutation.SetLabel(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *FeatureDefinitionCreate) SetDescription(v string) *FeatureDefinitionCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *FeatureDefinitionCreate) SetNillableDescription(v *string) *FeatureDefinitionCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetKind sets the "kind" field.
func (_c *FeatureDefinitionCreate) SetKind(v featuredefinition.Kind) *FeatureDefinitionCreate {
	_c.mutation.SetKind(v)
	return _c
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_c *FeatureDefinitionCreate) SetNillableKind(v *featuredefinition.Kind) *FeatureDefinitionCreate {
	if v != nil {
		_c.SetKind(*v)
	}
	return _c
}

// SetValueType sets the "value_type" field.
func (_c *FeatureDefinitionCreate) SetValueType(v featuredefinition.ValueType) *FeatureDefinitionCreate {
	_c.mutation.SetValueType(v)
	return _c
}

// SetNillableValueType sets the "value_type" field if the given value is not nil.
func (_c *FeatureDefinitionCreate) SetNillableValueType(v *featuredefinition.ValueType) *FeatureDefinitionCreate {
	if v != nil {
		_c.SetValueType(*v)
	}
	return _c
}

// SetDefaultLimit sets the "default_limit" field.
func (_c *FeatureDefinitionCreate) SetDefaultLimit(v int) *FeatureDefinitionCreate {
	_c.mutation.SetDefaultLimit(v)
	return _c
}

// SetNillableDefaultLimit sets the "default_limit" field if the given value is not nil.
func (_c *FeatureDefinitionCreate) SetNillableDefaultLimit(v *int) *FeatureDefinitionCreate {
	if v != nil {
		_c.SetDefaultLimit(*v)
	}
	return _c
}

// SetIsRateLimited sets the "is_rate_limited" field.
func (_c *FeatureDefinitionCreate) SetIsRateLimited(v bool) *FeatureDefinitionCreate {
	_c.mutation.SetIsRateLimited(v)
	return _c
}

// SetNillableIsRateLimited sets the "is_rate_limited" field if the given value is not nil.
func (_c *FeatureDefinitionCreate) SetNillableIsRateLimited(v *bool) *FeatureDefinitionCreate {
	if v != nil {
		_c.SetIsRateLimited(*v)
	}
	return _c
}

// SetUnit sets the "unit" field.
func (_c *FeatureDefinitionCreate) SetUnit(v string) *FeatureDefinitionCreate {
	_c.mutation.SetUnit(v)
	return _c
}

// SetNillableUnit sets the "unit" field if the given value is not nil.
func (_c *FeatureDefinitionCreate) SetNillableUnit(v *string) *FeatureDefinitionCreate {
	if v != nil {
		_c.SetUnit(*v)
	}
	return _c
}

// SetNatsEvent sets the "nats_event" field.
func (_c *FeatureDefinitionCreate) SetNatsEvent(v string) *FeatureDefinitionCreate {
	_c.mutation.SetNatsEvent(v)
	return _c
}

// SetNillableNatsEvent sets the "nats_event" field if the given value is not nil.
func (_c *FeatureDefinitionCreate) SetNillableNatsEvent(v *string) *FeatureDefinitionCreate {
	if v != nil {
		_c.SetNatsEvent(*v)
	}
	return _c
}

// SetSortOrder sets the "sort_order" field.
func (_c *FeatureDefinitionCreate) SetSortOrder(v int) *FeatureDefinitionCreate {
	_c.mutation.SetSortOrder(v)
	return _c
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_c *FeatureDefinitionCreate) SetNillableSortOrder(v *int) *FeatureDefinitionCreate {
	if v != nil {
		_c.SetSortOrder(*v)
	}
	return _c
}

// SetIsActive sets the "is_active" field.
func (_c *FeatureDefinitionCreate) SetIsActive(v bool) *FeatureDefinitionCreate {
	_c.mutation.SetIsActive(v)
	return _c
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_c *FeatureDefinitionCreate) SetNillableIsActive(v *bool) *FeatureDefinitionCreate {
	if v != nil {
		_c.SetIsActive(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *FeatureDefinitionCreate) SetCreatedAt(v time.Time) *FeatureDefinitionCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *FeatureDefinitionCreate) SetNillableCreatedAt(v *time.Time) *FeatureDefinitionCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *FeatureDefinitionCreate) SetUpdatedAt(v time.Time) *FeatureDefinitionCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *FeatureDefinitionCreate) SetNillableUpdatedAt(v *time.Time) *FeatureDefinitionCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *FeatureDefinitionCreate) SetID(v uuid.UUID) *FeatureDefinitionCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *FeatureDefinitionCreate) SetNillableID(v *uuid.UUID) *FeatureDefinitionCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the FeatureDefinitionMutation object of the builder.
func (_c *FeatureDefinitionCreate) Mutation() *FeatureDefinitionMutation {
	return _c.mutation
}

// Save creates the FeatureDefinition in the database.
func (_c *FeatureDefinitionCreate) Save(ctx context.Context) (*FeatureDefinition, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *FeatureDefinitionCreate) SaveX(ctx context.Context) *FeatureDefinition {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *FeatureDefinitionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *FeatureDefinitionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *FeatureDefinitionCreate) defaults() {
	if _, ok := _c.mutation.Category(); !ok {
		v := featuredefinition.DefaultCategory
		_c.mutation.SetCategory(v)
	}
	if _, ok := _c.mutation.Kind(); !ok {
		v := featuredefinition.DefaultKind
		_c.mutation.SetKind(v)
	}
	if _, ok := _c.mutation.ValueType(); !ok {
		v := featuredefinition.DefaultValueType
		_c.mutation.SetValueType(v)
	}
	if _, ok := _c.mutation.IsRateLimited(); !ok {
		v := featuredefinition.DefaultIsRateLimited
		_c.mutation.SetIsRateLimited(v)
	}
	if _, ok := _c.mutation.SortOrder(); !ok {
		v := featuredefinition.DefaultSortOrder
		_c.mutation.SetSortOrder(v)
	}
	if _, ok := _c.mutation.IsActive(); !ok {
		v := featuredefinition.DefaultIsActive
		_c.mutation.SetIsActive(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := featuredefinition.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := featuredefinition.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := featuredefinition.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *FeatureDefinitionCreate) check() error {
	if _, ok := _c.mutation.FeatureCode(); !ok {
		return &ValidationError{Name: "feature_code", err: errors.New(`ent: missing required field "FeatureDefinition.feature_code"`)}
	}
	if v, ok := _c.mutation.FeatureCode(); ok {
		if err := featuredefinition.FeatureCodeValidator(v); err != nil {
			return &ValidationError{Name: "feature_code", err: fmt.Errorf(`ent: validator failed for field "FeatureDefinition.feature_code": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ServiceTag(); !ok {
		return &ValidationError{Name: "service_tag", err: errors.New(`ent: missing required field "FeatureDefinition.service_tag"`)}
	}
	if v, ok := _c.mutation.ServiceTag(); ok {
		if err := featuredefinition.ServiceTagValidator(v); err != nil {
			return &ValidationError{Name: "service_tag", err: fmt.Errorf(`ent: validator failed for field "FeatureDefinition.service_tag": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Category(); !ok {
		return &ValidationError{Name: "category", err: errors.New(`ent: missing required field "FeatureDefinition.category"`)}
	}
	if _, ok := _c.mutation.Label(); !ok {
		return &ValidationError{Name: "label", err: errors.New(`ent: missing required field "FeatureDefinition.label"`)}
	}
	if v, ok := _c.mutation.Label(); ok {
		if err := featuredefinition.LabelValidator(v); err != nil {
			return &ValidationError{Name: "label", err: fmt.Errorf(`ent: validator failed for field "FeatureDefinition.label": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Kind(); !ok {
		return &ValidationError{Name: "kind", err: errors.New(`ent: missing required field "FeatureDefinition.kind"`)}
	}
	if v, ok := _c.mutation.Kind(); ok {
		if err := featuredefinition.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "FeatureDefinition.kind": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ValueType(); !ok {
		return &ValidationError{Name: "value_type", err: errors.New(`ent: missing required field "FeatureDefinition.value_type"`)}
	}
	if v, ok := _c.mutation.ValueType(); ok {
		if err := featuredefinition.ValueTypeValidator(v); err != nil {
			return &ValidationError{Name: "value_type", err: fmt.Errorf(`ent: validator failed for field "FeatureDefinition.value_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.IsRateLimited(); !ok {
		return &ValidationError{Name: "is_rate_limited", err: errors.New(`ent: missing required field "FeatureDefinition.is_rate_limited"`)}
	}
	if _, ok := _c.mutation.SortOrder(); !ok {
		return &ValidationError{Name: "sort_order", err: errors.New(`ent: missing required field "FeatureDefinition.sort_order"`)}
	}
	if _, ok := _c.mutation.IsActive(); !ok {
		return &ValidationError{Name: "is_active", err: errors.New(`ent: missing required field "FeatureDefinition.is_active"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "FeatureDefinition.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "FeatureDefinition.updated_at"`)}
	}
	return nil
}

func (_c *FeatureDefinitionCreate) sqlSave(ctx context.Context) (*FeatureDefinition, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *FeatureDefinitionCreate) createSpec() (*FeatureDefinition, *sqlgraph.CreateSpec) {
	var (
		_node = &FeatureDefinition{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(featuredefinition.Table, sqlgraph.NewFieldSpec(featuredefinition.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.FeatureCode(); ok {
		_spec.SetField(featuredefinition.FieldFeatureCode, field.TypeString, value)
		_node.FeatureCode = value
	}
	if value, ok := _c.mutation.ServiceTag(); ok {
		_spec.SetField(featuredefinition.FieldServiceTag, field.TypeString, value)
		_node.ServiceTag = value
	}
	if value, ok := _c.mutation.Category(); ok {
		_spec.SetField(featuredefinition.FieldCategory, field.TypeString, value)
		_node.Category = value
	}
	if value, ok := _c.mutation.Label(); ok {
		_spec.SetField(featuredefinition.FieldLabel, field.TypeString, value)
		_node.Label = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(featuredefinition.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.Kind(); ok {
		_spec.SetField(featuredefinition.FieldKind, field.TypeEnum, value)
		_node.Kind = value
	}
	if value, ok := _c.mutation.ValueType(); ok {
		_spec.SetField(featuredefinition.FieldValueType, field.TypeEnum, value)
		_node.ValueType = value
	}
	if value, ok := _c.mutation.DefaultLimit(); ok {
		_spec.SetField(featuredefinition.FieldDefaultLimit, field.TypeInt, value)
		_node.DefaultLimit = &value
	}
	if value, ok := _c.mutation.IsRateLimited(); ok {
		_spec.SetField(featuredefinition.FieldIsRateLimited, field.TypeBool, value)
		_node.IsRateLimited = value
	}
	if value, ok := _c.mutation.Unit(); ok {
		_spec.SetField(featuredefinition.FieldUnit, field.TypeString, value)
		_node.Unit = value
	}
	if value, ok := _c.mutation.NatsEvent(); ok {
		_spec.SetField(featuredefinition.FieldNatsEvent, field.TypeString, value)
		_node.NatsEvent = value
	}
	if value, ok := _c.mutation.SortOrder(); ok {
		_spec.SetField(featuredefinition.FieldSortOrder, field.TypeInt, value)
		_node.SortOrder = value
	}
	if value, ok := _c.mutation.IsActive(); ok {
		_spec.SetField(featuredefinition.FieldIsActive, field.TypeBool, value)
		_node.IsActive = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(featuredefinition.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(featuredefinition.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.FeatureDefinition.Create().
//		SetFeatureCode(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.FeatureDefinitionUpsert) {
//			SetFeatureCode(v+v).
//		}).
//		Exec(ctx)
func (_c *FeatureDefinitionCreate) OnConflict(opts ...sql.ConflictOption) *FeatureDefinitionUpsertOne {
	_c.conflict = opts
	return &FeatureDefinitionUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.FeatureDefinition.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *FeatureDefinitionCreate) OnConflictColumns(columns ...string) *FeatureDefinitionUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &FeatureDefinitionUpsertOne{
		create: _c,
	}
}

type (
	// FeatureDefinitionUpsertOne is the builder for "upsert"-ing
	//  one FeatureDefinition node.
	FeatureDefinitionUpsertOne struct {
		create *FeatureDefinitionCreate
	}

	// FeatureDefinitionUpsert is the "OnConflict" setter.
	FeatureDefinitionUpsert struct {
		*sql.UpdateSet
	}
)

// SetFeatureCode sets the "feature_code" field.
func (u *FeatureDefinitionUpsert) SetFeatureCode(v string) *FeatureDefinitionUpsert {
	u.Set(featuredefinition.FieldFeatureCode, v)
	return u
}

// UpdateFeatureCode sets the "feature_code" field to the value that was provided on create.
func (u *FeatureDefinitionUpsert) UpdateFeatureCode() *FeatureDefinitionUpsert {
	u.SetExcluded(featuredefinition.FieldFeatureCode)
	return u
}

// SetServiceTag sets the "service_tag" field.
func (u *FeatureDefinitionUpsert) SetServiceTag(v string) *FeatureDefinitionUpsert {
	u.Set(featuredefinition.FieldServiceTag, v)
	return u
}

// UpdateServiceTag sets the "service_tag" field to the value that was provided on create.
func (u *FeatureDefinitionUpsert) UpdateServiceTag() *FeatureDefinitionUpsert {
	u.SetExcluded(featuredefinition.FieldServiceTag)
	return u
}

// SetCategory sets the "category" field.
func (u *FeatureDefinitionUpsert) SetCategory(v string) *FeatureDefinitionUpsert {
	u.Set(featuredefinition.FieldCategory, v)
	return u
}

// UpdateCategory sets the "category" field to the value that was provided on create.
func (u *FeatureDefinitionUpsert) UpdateCategory() *FeatureDefinitionUpsert {
	u.SetExcluded(featuredefinition.FieldCategory)
	return u
}

// SetLabel sets the "label" field.
func (u *FeatureDefinitionUpsert) SetLabel(v string) *FeatureDefinitionUpsert {
	u.Set(featuredefinition.FieldLabel, v)
	return u
}

// UpdateLabel sets the "label" field to the value that was provided on create.
func (u *FeatureDefinitionUpsert) UpdateLabel() *FeatureDefinitionUpsert {
	u.SetExcluded(featuredefinition.FieldLabel)
	return u
}

// SetDescription sets the "description" field.
func (u *FeatureDefinitionUpsert) SetDescription(v string) *FeatureDefinitionUpsert {
	u.Set(featuredefinition.FieldDescription, v)
	return u
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *FeatureDefinitionUpsert) UpdateDescription() *FeatureDefinitionUpsert {
	u.SetExcluded(featuredefinition.FieldDescription)
	return u
}

// ClearDescription clears the value of the "description" field.
func (u *FeatureDefinitionUpsert) ClearDescription() *FeatureDefinitionUpsert {
	u.SetNull(featuredefinition.FieldDescription)
	return u
}

// SetKind sets the "kind" field.
func (u *FeatureDefinitionUpsert) SetKind(v featuredefinition.Kind) *FeatureDefinitionUpsert {
	u.Set(featuredefinition.FieldKind, v)
	return u
}

// UpdateKind sets the "kind" field to the value that was provided on create.
func (u *FeatureDefinitionUpsert) UpdateKind() *FeatureDefinitionUpsert {
	u.SetExcluded(featuredefinition.FieldKind)
	return u
}

// SetValueType sets the "value_type" field.
func (u *FeatureDefinitionUpsert) SetValueType(v featuredefinition.ValueType) *FeatureDefinitionUpsert {
	u.Set(featuredefinition.FieldValueType, v)
	return u
}

// UpdateValueType sets the "value_type" field to the value that was provided on create.
func (u *FeatureDefinitionUpsert) UpdateValueType() *FeatureDefinitionUpsert {
	u.SetExcluded(featuredefinition.FieldValueType)
	return u
}

// SetDefaultLimit sets the "default_limit" field.
func (u *FeatureDefinitionUpsert) SetDefaultLimit(v int) *FeatureDefinitionUpsert {
	u.Set(featuredefinition.FieldDefaultLimit, v)
	return u
}

// UpdateDefaultLimit sets the "default_limit" field to the value that was provided on create.
func (u *FeatureDefinitionUpsert) UpdateDefaultLimit() *FeatureDefinitionUpsert {
	u.SetExcluded(featuredefinition.FieldDefaultLimit)
	return u
}

// AddDefaultLimit adds v to the "default_limit" field.
func (u *FeatureDefinitionUpsert) AddDefaultLimit(v int) *FeatureDefinitionUpsert {
	u.Add(featuredefinition.FieldDefaultLimit, v)
	return u
}

// ClearDefaultLimit clears the value of the "default_limit" field.
func (u *FeatureDefinitionUpsert) ClearDefaultLimit() *FeatureDefinitionUpsert {
	u.SetNull(featuredefinition.FieldDefaultLimit)
	return u
}

// SetIsRateLimited sets the "is_rate_limited" field.
func (u *FeatureDefinitionUpsert) SetIsRateLimited(v bool) *FeatureDefinitionUpsert {
	u.Set(featuredefinition.FieldIsRateLimited, v)
	return u
}

// UpdateIsRateLimited sets the "is_rate_limited" field to the value that was provided on create.
func (u *FeatureDefinitionUpsert) UpdateIsRateLimited() *FeatureDefinitionUpsert {
	u.SetExcluded(featuredefinition.FieldIsRateLimited)
	return u
}

// SetUnit sets the "unit" field.
func (u *FeatureDefinitionUpsert) SetUnit(v string) *FeatureDefinitionUpsert {
	u.Set(featuredefinition.FieldUnit, v)
	return u
}

// UpdateUnit sets the "unit" field to the value that was provided on create.
func (u *FeatureDefinitionUpsert) UpdateUnit() *FeatureDefinitionUpsert {
	u.SetExcluded(featuredefinition.FieldUnit)
	return u
}

// ClearUnit clears the value of the "unit" field.
func (u *FeatureDefinitionUpsert) ClearUnit() *FeatureDefinitionUpsert {
	u.SetNull(featuredefinition.FieldUnit)
	return u
}

// SetNatsEvent sets the "nats_event" field.
func (u *FeatureDefinitionUpsert) SetNatsEvent(v string) *FeatureDefinitionUpsert {
	u.Set(featuredefinition.FieldNatsEvent, v)
	return u
}

// UpdateNatsEvent sets the "nats_event" field to the value that was provided on create.
func (u *FeatureDefinitionUpsert) UpdateNatsEvent() *FeatureDefinitionUpsert {
	u.SetExcluded(featuredefinition.FieldNatsEvent)
	return u
}

// ClearNatsEvent clears the value of the "nats_event" field.
func (u *FeatureDefinitionUpsert) ClearNatsEvent() *FeatureDefinitionUpsert {
	u.SetNull(featuredefinition.FieldNatsEvent)
	return u
}

// SetSortOrder sets the "sort_order" field.
func (u *FeatureDefinitionUpsert) SetSortOrder(v int) *FeatureDefinitionUpsert {
	u.Set(featuredefinition.FieldSortOrder, v)
	return u
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *FeatureDefinitionUpsert) UpdateSortOrder() *FeatureDefinitionUpsert {
	u.SetExcluded(featuredefinition.FieldSortOrder)
	return u
}

// AddSortOrder adds v to the "sort_order" field.
func (u *FeatureDefinitionUpsert) AddSortOrder(v int) *FeatureDefinitionUpsert {
	u.Add(featuredefinition.FieldSortOrder, v)
	return u
}

// SetIsActive sets the "is_active" field.
func (u *FeatureDefinitionUpsert) SetIsActive(v bool) *FeatureDefinitionUpsert {
	u.Set(featuredefinition.FieldIsActive, v)
	return u
}

// UpdateIsActive sets the "is_active" field to the value that was provided on create.
func (u *FeatureDefinitionUpsert) UpdateIsActive() *FeatureDefinitionUpsert {
	u.SetExcluded(featuredefinition.FieldIsActive)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *FeatureDefinitionUpsert) SetUpdatedAt(v time.Time) *FeatureDefinitionUpsert {
	u.Set(featuredefinition.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *FeatureDefinitionUpsert) UpdateUpdatedAt() *FeatureDefinitionUpsert {
	u.SetExcluded(featuredefinition.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.FeatureDefinition.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(featuredefinition.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *FeatureDefinitionUpsertOne) UpdateNewValues() *FeatureDefinitionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(featuredefinition.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(featuredefinition.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.FeatureDefinition.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *FeatureDefinitionUpsertOne) Ignore() *FeatureDefinitionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *FeatureDefinitionUpsertOne) DoNothing() *FeatureDefinitionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the FeatureDefinitionCreate.OnConflict
// documentation for more info.
func (u *FeatureDefinitionUpsertOne) Update(set func(*FeatureDefinitionUpsert)) *FeatureDefinitionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&FeatureDefinitionUpsert{UpdateSet: update})
	}))
	return u
}

// SetFeatureCode sets the "feature_code" field.
func (u *FeatureDefinitionUpsertOne) SetFeatureCode(v string) *FeatureDefinitionUpsertOne {
	return u.Update(func(s *FeatureDefinitionUpsert) {
		s.SetFeatureCode(v)
	})
}

// UpdateFeatureCode sets the "feature_code" field to the value that was provided on create.
func (u *FeatureDefinitionUpsertOne) UpdateFeatureCode() *FeatureDefinitionUpsertOne {
	return u.Update(func(s *FeatureDefinitionUpsert) {
		s.UpdateFeatureCode()
	})
}

// SetServiceTag sets the "service_tag" field.
func (u *FeatureDefinitionUpsertOne) SetServiceTag(v string) *FeatureDefinitionUpsertOne {
	return u.Update(func(s *FeatureDefinitionUpsert) {
		s.SetServiceTag(v)
	})
}

// UpdateServiceTag sets the "service_tag" field to the value that was provided on create.
func (u *FeatureDefinitionUpsertOne) UpdateServiceTag() *FeatureDefinitionUpsertOne {
	return u.Update(func(s *FeatureDefinitionUpsert) {
		s.UpdateServiceTag()
	})
}

// SetCategory sets the "category" field.
func (u *FeatureDefinitionUpsertOne) SetCategory(v string) *FeatureDefinitionUpsertOne {
	return u.Update(func(s *FeatureDefinitionUpsert) {
		s.SetCategory(v)
	})
}

// UpdateCategory sets the "category" field to the value that was provided on create.
func (u *FeatureDefinitionUpsertOne) UpdateCategory() *FeatureDefinitionUpsertOne {
	return u.Update(func(s *FeatureDefinitionUpsert) {
		s.UpdateCategory()
	})
}

// SetLabel sets the "label" field.
func (u *FeatureDefinitionUpsertOne) SetLabel(v string) *FeatureDefinitionUpsertOne {
	return u.Update(func(s *FeatureDefinitionUpsert) {
		s.SetLabel(v)
	})
}

// UpdateLabel sets the "label" field to the value that was provided on create.
func (u *FeatureDefinitionUpsertOne) UpdateLabel() *FeatureDefinitionUpsertOne {
	return u.Update(func(s *FeatureDefinitionUpsert) {
		s.UpdateLabel()
	})
}

// SetDescription sets the "description" field.
func (u *FeatureDefinitionUpsertOne) SetDescription(v string) *FeatureDefinitionUpsertOne {
	return u.Update(func(s *FeatureDefinitionUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *FeatureDefinitionUpsertOne) UpdateDescription() *FeatureDefinitionUpsertOne {
	return u.Update(func(s *FeatureDefinitionUpsert) {
		s.UpdateDescription()
	})
}

// ClearDescription clears the value of the "description" field.
func (u *FeatureDefinitionUpsertOne) ClearDescription() *FeatureDefinitionUpsertOne {
	return u.Update(func(s *FeatureDefinitionUpsert) {
		s.ClearDescription()
	})
}

// SetKind sets the "kind" field.
func (u *FeatureDefinitionUpsertOne) SetKind(v featuredefinition.Kind) *FeatureDefinitionUpsertOne {
	return u.Update(func(s *FeatureDefinitionUpsert) {
		s.SetKind(v)
	})
}

// UpdateKind sets the "kind" field to the value that was provided on create.
func (u *FeatureDefinitionUpsertOne) UpdateKind() *FeatureDefinitionUpsertOne {
	return u.Update(func(s *FeatureDefinitionUpsert) {
		s.UpdateKind()
	})
}

// SetValueType sets the "value_type" field.
func (u *FeatureDefinitionUpsertOne) SetValueType(v featuredefinition.ValueType) *FeatureDefinitionUpsertOne {
	return u.Update(func(s *FeatureDefinitionUpsert) {
		s.SetValueType(v)
	})
}

// UpdateValueType sets the "value_type" field to the value that was provided on create.
func (u *FeatureDefinitionUpsertOne) UpdateValueType() *FeatureDefinitionUpsertOne {
	return u.Update(func(s *FeatureDefinitionUpsert) {
		s.UpdateValueType()
	})
}

// SetDefaultLimit sets the "default_limit" field.
func (u *FeatureDefinitionUpsertOne) SetDefaultLimit(v int) *FeatureDefinitionUpsertOne {
	return u.Update(func(s *FeatureDefinitionUpsert) {
		s.SetDefaultLimit(v)
	})
}

// AddDefaultLimit adds v to the "default_limit" field.
func (u *FeatureDefinitionUpsertOne) AddDefaultLimit(v int) *FeatureDefinitionUpsertOne {
	return u.Update(func(s *FeatureDefinitionUpsert) {
		s.AddDefaultLimit(v)
	})
}

// UpdateDefaultLimit sets the "default_limit" field to the value that was provided on create.
func (u *FeatureDefinitionUpsertOne) UpdateDefaultLimit() *FeatureDefinitionUpsertOne {
	return u.Update(func(s *FeatureDefinitionUpsert) {
		s.UpdateDefaultLimit()
	})
}

// ClearDefaultLimit clears the value of the "default_limit" field.
func (u *FeatureDefinitionUpsertOne) ClearDefaultLimit() *FeatureDefinitionUpsertOne {
	return u.Update(func(s *FeatureDefinitionUpsert) {
		s.ClearDefaultLimit()
	})
}

// SetIsRateLimited sets the "is_rate_limited" field.
func (u *FeatureDefinitionUpsertOne) SetIsRateLimited(v bool) *FeatureDefinitionUpsertOne {
	return u.Update(func(s *FeatureDefinitionUpsert) {
		s.SetIsRateLimited(v)
	})
}

// UpdateIsRateLimited sets the "is_rate_limited" field to the value that was provided on create.
func (u *FeatureDefinitionUpsertOne) UpdateIsRateLimited() *FeatureDefinitionUpsertOne {
	return u.Update(func(s *FeatureDefinitionUpsert) {
		s.UpdateIsRateLimited()
	})
}

// SetUnit sets the "unit" field.
func (u *FeatureDefinitionUpsertOne) SetUnit(v string) *FeatureDefinitionUpsertOne {
	return u.Update(func(s *FeatureDefinitionUpsert) {
		s.SetUnit(v)
	})
}

// UpdateUnit sets the "unit" field to the value that was provided on create.
func (u *FeatureDefinitionUpsertOne) UpdateUnit() *FeatureDefinitionUpsertOne {
	return u.Update(func(s *FeatureDefinitionUpsert) {
		s.UpdateUnit()
	})
}

// ClearUnit clears the value of the "unit" field.
func (u *FeatureDefinitionUpsertOne) ClearUnit() *FeatureDefinitionUpsertOne {
	return u.Update(func(s *FeatureDefinitionUpsert) {
		s.ClearUnit()
	})
}

// SetNatsEvent sets the "nats_event" field.
func (u *FeatureDefinitionUpsertOne) SetNatsEvent(v string) *FeatureDefinitionUpsertOne {
	return u.Update(func(s *FeatureDefinitionUpsert) {
		s.SetNatsEvent(v)
	})
}

// UpdateNatsEvent sets the "nats_event" field to the value that was provided on create.
func (u *FeatureDefinitionUpsertOne) UpdateNatsEvent() *FeatureDefinitionUpsertOne {
	return u.Update(func(s *FeatureDefinitionUpsert) {
		s.UpdateNatsEvent()
	})
}

// ClearNatsEvent clears the value of the "nats_event" field.
func (u *FeatureDefinitionUpsertOne) ClearNatsEvent() *FeatureDefinitionUpsertOne {
	return u.Update(func(s *FeatureDefinitionUpsert) {
		s.ClearNatsEvent()
	})
}

// SetSortOrder sets the "sort_order" field.
func (u *FeatureDefinitionUpsertOne) SetSortOrder(v int) *FeatureDefinitionUpsertOne {
	return u.Update(func(s *FeatureDefinitionUpsert) {
		s.SetSortOrder(v)
	})
}

// AddSortOrder adds v to the "sort_order" field.
func (u *FeatureDefinitionUpsertOne) AddSortOrder(v int) *FeatureDefinitionUpsertOne {
	return u.Update(func(s *FeatureDefinitionUpsert) {
		s.AddSortOrder(v)
	})
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *FeatureDefinitionUpsertOne) UpdateSortOrder() *FeatureDefinitionUpsertOne {
	return u.Update(func(s *FeatureDefinitionUpsert) {
		s.UpdateSortOrder()
	})
}

// SetIsActive sets the "is_active" field.
func (u *FeatureDefinitionUpsertOne) SetIsActive(v bool) *FeatureDefinitionUpsertOne {
	return u.Update(func(s *FeatureDefinitionUpsert) {
		s.SetIsActive(v)
	})
}

// UpdateIsActive sets the "is_active" field to the value that was provided on create.
func (u *FeatureDefinitionUpsertOne) UpdateIsActive() *FeatureDefinitionUpsertOne {
	return u.Update(func(s *FeatureDefinitionUpsert) {
		s.UpdateIsActive()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *FeatureDefinitionUpsertOne) SetUpdatedAt(v time.Time) *FeatureDefinitionUpsertOne {
	return u.Update(func(s *FeatureDefinitionUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *FeatureDefinitionUpsertOne) UpdateUpdatedAt() *FeatureDefinitionUpsertOne {
	return u.Update(func(s *FeatureDefinitionUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *FeatureDefinitionUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for FeatureDefinitionCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *FeatureDefinitionUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *FeatureDefinitionUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: FeatureDefinitionUpsertOne.ID is not supported by MySQL driver. Use FeatureDefinitionUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *FeatureDefinitionUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// FeatureDefinitionCreateBulk is the builder for creating many FeatureDefinition entities in bulk.
type FeatureDefinitionCreateBulk struct {
	config
	err      error
	builders []*FeatureDefinitionCreate
	conflict []sql.ConflictOption
}

// Save creates the FeatureDefinition entities in the database.
func (_c *FeatureDefinitionCreateBulk) Save(ctx context.Context) ([]*FeatureDefinition, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*FeatureDefinition, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*FeatureDefinitionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *FeatureDefinitionCreateBulk) SaveX(ctx context.Context) []*FeatureDefinition {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *FeatureDefinitionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *FeatureDefinitionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.FeatureDefinition.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.FeatureDefinitionUpsert) {
//			SetFeatureCode(v+v).
//		}).
//		Exec(ctx)
func (_c *FeatureDefinitionCreateBulk) OnConflict(opts ...sql.ConflictOption) *FeatureDefinitionUpsertBulk {
	_c.conflict = opts
	return &FeatureDefinitionUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.FeatureDefinition.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *FeatureDefinitionCreateBulk) OnConflictColumns(columns ...string) *FeatureDefinitionUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &FeatureDefinitionUpsertBulk{
		create: _c,
	}
}

// FeatureDefinitionUpsertBulk is the builder for "upsert"-ing
// a bulk of FeatureDefinition nodes.
type FeatureDefinitionUpsertBulk struct {
	create *FeatureDefinitionCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.FeatureDefinition.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(featuredefinition.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *FeatureDefinitionUpsertBulk) UpdateNewValues() *FeatureDefinitionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(featuredefinition.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(featuredefinition.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.FeatureDefinition.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *FeatureDefinitionUpsertBulk) Ignore() *FeatureDefinitionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *FeatureDefinitionUpsertBulk) DoNothing() *FeatureDefinitionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the FeatureDefinitionCreateBulk.OnConflict
// documentation for more info.
func (u *FeatureDefinitionUpsertBulk) Update(set func(*FeatureDefinitionUpsert)) *FeatureDefinitionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&FeatureDefinitionUpsert{UpdateSet: update})
	}))
	return u
}

// SetFeatureCode sets the "feature_code" field.
func (u *FeatureDefinitionUpsertBulk) SetFeatureCode(v string) *FeatureDefinitionUpsertBulk {
	return u.Update(func(s *FeatureDefinitionUpsert) {
		s.SetFeatureCode(v)
	})
}

// UpdateFeatureCode sets the "feature_code" field to the value that was provided on create.
func (u *FeatureDefinitionUpsertBulk) UpdateFeatureCode() *FeatureDefinitionUpsertBulk {
	return u.Update(func(s *FeatureDefinitionUpsert) {
		s.UpdateFeatureCode()
	})
}

// SetServiceTag sets the "service_tag" field.
func (u *FeatureDefinitionUpsertBulk) SetServiceTag(v string) *FeatureDefinitionUpsertBulk {
	return u.Update(func(s *FeatureDefinitionUpsert) {
		s.SetServiceTag(v)
	})
}

// UpdateServiceTag sets the "service_tag" field to the value that was provided on create.
func (u *FeatureDefinitionUpsertBulk) UpdateServiceTag() *FeatureDefinitionUpsertBulk {
	return u.Update(func(s *FeatureDefinitionUpsert) {
		s.UpdateServiceTag()
	})
}

// SetCategory sets the "category" field.
func (u *FeatureDefinitionUpsertBulk) SetCategory(v string) *FeatureDefinitionUpsertBulk {
	return u.Update(func(s *FeatureDefinitionUpsert) {
		s.SetCategory(v)
	})
}

// UpdateCategory sets the "category" field to the value that was provided on create.
func (u *FeatureDefinitionUpsertBulk) UpdateCategory() *FeatureDefinitionUpsertBulk {
	return u.Update(func(s *FeatureDefinitionUpsert) {
		s.UpdateCategory()
	})
}

// SetLabel sets the "label" field.
func (u *FeatureDefinitionUpsertBulk) SetLabel(v string) *FeatureDefinitionUpsertBulk {
	return u.Update(func(s *FeatureDefinitionUpsert) {
		s.SetLabel(v)
	})
}

// UpdateLabel sets the "label" field to the value that was provided on create.
func (u *FeatureDefinitionUpsertBulk) UpdateLabel() *FeatureDefinitionUpsertBulk {
	return u.Update(func(s *FeatureDefinitionUpsert) {
		s.UpdateLabel()
	})
}

// SetDescription sets the "description" field.
func (u *FeatureDefinitionUpsertBulk) SetDescription(v string) *FeatureDefinitionUpsertBulk {
	return u.Update(func(s *FeatureDefinitionUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *FeatureDefinitionUpsertBulk) UpdateDescription() *FeatureDefinitionUpsertBulk {
	return u.Update(func(s *FeatureDefinitionUpsert) {
		s.UpdateDescription()
	})
}

// ClearDescription clears the value of the "description" field.
func (u *FeatureDefinitionUpsertBulk) ClearDescription() *FeatureDefinitionUpsertBulk {
	return u.Update(func(s *FeatureDefinitionUpsert) {
		s.ClearDescription()
	})
}

// SetKind sets the "kind" field.
func (u *FeatureDefinitionUpsertBulk) SetKind(v featuredefinition.Kind) *FeatureDefinitionUpsertBulk {
	return u.Update(func(s *FeatureDefinitionUpsert) {
		s.SetKind(v)
	})
}

// UpdateKind sets the "kind" field to the value that was provided on create.
func (u *FeatureDefinitionUpsertBulk) UpdateKind() *FeatureDefinitionUpsertBulk {
	return u.Update(func(s *FeatureDefinitionUpsert) {
		s.UpdateKind()
	})
}

// SetValueType sets the "value_type" field.
func (u *FeatureDefinitionUpsertBulk) SetValueType(v featuredefinition.ValueType) *FeatureDefinitionUpsertBulk {
	return u.Update(func(s *FeatureDefinitionUpsert) {
		s.SetValueType(v)
	})
}

// UpdateValueType sets the "value_type" field to the value that was provided on create.
func (u *FeatureDefinitionUpsertBulk) UpdateValueType() *FeatureDefinitionUpsertBulk {
	return u.Update(func(s *FeatureDefinitionUpsert) {
		s.UpdateValueType()
	})
}

// SetDefaultLimit sets the "default_limit" field.
func (u *FeatureDefinitionUpsertBulk) SetDefaultLimit(v int) *FeatureDefinitionUpsertBulk {
	return u.Update(func(s *FeatureDefinitionUpsert) {
		s.SetDefaultLimit(v)
	})
}

// AddDefaultLimit adds v to the "default_limit" field.
func (u *FeatureDefinitionUpsertBulk) AddDefaultLimit(v int) *FeatureDefinitionUpsertBulk {
	return u.Update(func(s *FeatureDefinitionUpsert) {
		s.AddDefaultLimit(v)
	})
}

// UpdateDefaultLimit sets the "default_limit" field to the value that was provided on create.
func (u *FeatureDefinitionUpsertBulk) UpdateDefaultLimit() *FeatureDefinitionUpsertBulk {
	return u.Update(func(s *FeatureDefinitionUpsert) {
		s.UpdateDefaultLimit()
	})
}

// ClearDefaultLimit clears the value of the "default_limit" field.
func (u *FeatureDefinitionUpsertBulk) ClearDefaultLimit() *FeatureDefinitionUpsertBulk {
	return u.Update(func(s *FeatureDefinitionUpsert) {
		s.ClearDefaultLimit()
	})
}

// SetIsRateLimited sets the "is_rate_limited" field.
func (u *FeatureDefinitionUpsertBulk) SetIsRateLimited(v bool) *FeatureDefinitionUpsertBulk {
	return u.Update(func(s *FeatureDefinitionUpsert) {
		s.SetIsRateLimited(v)
	})
}

// UpdateIsRateLimited sets the "is_rate_limited" field to the value that was provided on create.
func (u *FeatureDefinitionUpsertBulk) UpdateIsRateLimited() *FeatureDefinitionUpsertBulk {
	return u.Update(func(s *FeatureDefinitionUpsert) {
		s.UpdateIsRateLimited()
	})
}

// SetUnit sets the "unit" field.
func (u *FeatureDefinitionUpsertBulk) SetUnit(v string) *FeatureDefinitionUpsertBulk {
	return u.Update(func(s *FeatureDefinitionUpsert) {
		s.SetUnit(v)
	})
}

// UpdateUnit sets the "unit" field to the value that was provided on create.
func (u *FeatureDefinitionUpsertBulk) UpdateUnit() *FeatureDefinitionUpsertBulk {
	return u.Update(func(s *FeatureDefinitionUpsert) {
		s.UpdateUnit()
	})
}

// ClearUnit clears the value of the "unit" field.
func (u *FeatureDefinitionUpsertBulk) ClearUnit() *FeatureDefinitionUpsertBulk {
	return u.Update(func(s *FeatureDefinitionUpsert) {
		s.ClearUnit()
	})
}

// SetNatsEvent sets the "nats_event" field.
func (u *FeatureDefinitionUpsertBulk) SetNatsEvent(v string) *FeatureDefinitionUpsertBulk {
	return u.Update(func(s *FeatureDefinitionUpsert) {
		s.SetNatsEvent(v)
	})
}

// UpdateNatsEvent sets the "nats_event" field to the value that was provided on create.
func (u *FeatureDefinitionUpsertBulk) UpdateNatsEvent() *FeatureDefinitionUpsertBulk {
	return u.Update(func(s *FeatureDefinitionUpsert) {
		s.UpdateNatsEvent()
	})
}

// ClearNatsEvent clears the value of the "nats_event" field.
func (u *FeatureDefinitionUpsertBulk) ClearNatsEvent() *FeatureDefinitionUpsertBulk {
	return u.Update(func(s *FeatureDefinitionUpsert) {
		s.ClearNatsEvent()
	})
}

// SetSortOrder sets the "sort_order" field.
func (u *FeatureDefinitionUpsertBulk) SetSortOrder(v int) *FeatureDefinitionUpsertBulk {
	return u.Update(func(s *FeatureDefinitionUpsert) {
		s.SetSortOrder(v)
	})
}

// AddSortOrder adds v to the "sort_order" field.
func (u *FeatureDefinitionUpsertBulk) AddSortOrder(v int) *FeatureDefinitionUpsertBulk {
	return u.Update(func(s *FeatureDefinitionUpsert) {
		s.AddSortOrder(v)
	})
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *FeatureDefinitionUpsertBulk) UpdateSortOrder() *FeatureDefinitionUpsertBulk {
	return u.Update(func(s *FeatureDefinitionUpsert) {
		s.UpdateSortOrder()
	})
}

// SetIsActive sets the "is_active" field.
func (u *FeatureDefinitionUpsertBulk) SetIsActive(v bool) *FeatureDefinitionUpsertBulk {
	return u.Update(func(s *FeatureDefinitionUpsert) {
		s.SetIsActive(v)
	})
}

// UpdateIsActive sets the "is_active" field to the value that was provided on create.
func (u *FeatureDefinitionUpsertBulk) UpdateIsActive() *FeatureDefinitionUpsertBulk {
	return u.Update(func(s *FeatureDefinitionUpsert) {
		s.UpdateIsActive()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *FeatureDefinitionUpsertBulk) SetUpdatedAt(v time.Time) *FeatureDefinitionUpsertBulk {
	return u.Update(func(s *FeatureDefinitionUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *FeatureDefinitionUpsertBulk) UpdateUpdatedAt() *FeatureDefinitionUpsertBulk {
	return u.Update(func(s *FeatureDefinitionUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *FeatureDefinitionUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the FeatureDefinitionCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for FeatureDefinitionCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *FeatureDefinitionUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
