// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/bengobox/subscription-service/internal/ent/overagecharge"
	"github.com/bengobox/subscription-service/internal/ent/predicate"
)

// OverageChargeDelete is the builder for deleting a OverageCharge entity.
type OverageChargeDelete struct {
	config
	hooks    []Hook
	mutation *OverageChargeMutation
}

// Where appends a list predicates to the OverageChargeDelete builder.
func (_d *OverageChargeDelete) Where(ps ...predicate.OverageCharge) *OverageChargeDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *OverageChargeDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *OverageChargeDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *OverageChargeDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(overagecharge.Table, sqlgraph.NewFieldSpec(overagecharge.FieldID, field.TypeUUID))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// OverageChargeDeleteOne is the builder for deleting a single OverageCharge entity.
type OverageChargeDeleteOne struct {
	_d *OverageChargeDelete
}

// Where appends a list predicates to the OverageChargeDelete builder.
func (_d *OverageChargeDeleteOne) Where(ps ...predicate.OverageCharge) *OverageChargeDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *OverageChargeDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{overagecharge.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *OverageChargeDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
