// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/bengobox/subscription-service/internal/ent/planpricinghistory"
	"github.com/bengobox/subscription-service/internal/ent/subscriptionplan"
	"github.com/google/uuid"
)

// PlanPricingHistoryCreate is the builder for creating a PlanPricingHistory entity.
type PlanPricingHistoryCreate struct {
	config
	mutation *PlanPricingHistoryMutation
	hooks    []Hook
}

// SetPlanID sets the "plan_id" field.
func (pphc *PlanPricingHistoryCreate) SetPlanID(u uuid.UUID) *PlanPricingHistoryCreate {
	pphc.mutation.SetPlanID(u)
	return pphc
}

// SetBasePrice sets the "base_price" field.
func (pphc *PlanPricingHistoryCreate) SetBasePrice(f float64) *PlanPricingHistoryCreate {
	pphc.mutation.SetBasePrice(f)
	return pphc
}

// SetEffectiveFrom sets the "effective_from" field.
func (pphc *PlanPricingHistoryCreate) SetEffectiveFrom(t time.Time) *PlanPricingHistoryCreate {
	pphc.mutation.SetEffectiveFrom(t)
	return pphc
}

// SetEffectiveTo sets the "effective_to" field.
func (pphc *PlanPricingHistoryCreate) SetEffectiveTo(t time.Time) *PlanPricingHistoryCreate {
	pphc.mutation.SetEffectiveTo(t)
	return pphc
}

// SetNillableEffectiveTo sets the "effective_to" field if the given value is not nil.
func (pphc *PlanPricingHistoryCreate) SetNillableEffectiveTo(t *time.Time) *PlanPricingHistoryCreate {
	if t != nil {
		pphc.SetEffectiveTo(*t)
	}
	return pphc
}

// SetChangedBy sets the "changed_by" field.
func (pphc *PlanPricingHistoryCreate) SetChangedBy(u uuid.UUID) *PlanPricingHistoryCreate {
	pphc.mutation.SetChangedBy(u)
	return pphc
}

// SetNillableChangedBy sets the "changed_by" field if the given value is not nil.
func (pphc *PlanPricingHistoryCreate) SetNillableChangedBy(u *uuid.UUID) *PlanPricingHistoryCreate {
	if u != nil {
		pphc.SetChangedBy(*u)
	}
	return pphc
}

// SetChangeReason sets the "change_reason" field.
func (pphc *PlanPricingHistoryCreate) SetChangeReason(s string) *PlanPricingHistoryCreate {
	pphc.mutation.SetChangeReason(s)
	return pphc
}

// SetNillableChangeReason sets the "change_reason" field if the given value is not nil.
func (pphc *PlanPricingHistoryCreate) SetNillableChangeReason(s *string) *PlanPricingHistoryCreate {
	if s != nil {
		pphc.SetChangeReason(*s)
	}
	return pphc
}

// SetMetadata sets the "metadata" field.
func (pphc *PlanPricingHistoryCreate) SetMetadata(m map[string]interface{}) *PlanPricingHistoryCreate {
	pphc.mutation.SetMetadata(m)
	return pphc
}

// SetCreatedAt sets the "created_at" field.
func (pphc *PlanPricingHistoryCreate) SetCreatedAt(t time.Time) *PlanPricingHistoryCreate {
	pphc.mutation.SetCreatedAt(t)
	return pphc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (pphc *PlanPricingHistoryCreate) SetNillableCreatedAt(t *time.Time) *PlanPricingHistoryCreate {
	if t != nil {
		pphc.SetCreatedAt(*t)
	}
	return pphc
}

// SetID sets the "id" field.
func (pphc *PlanPricingHistoryCreate) SetID(u uuid.UUID) *PlanPricingHistoryCreate {
	pphc.mutation.SetID(u)
	return pphc
}

// SetNillableID sets the "id" field if the given value is not nil.
func (pphc *PlanPricingHistoryCreate) SetNillableID(u *uuid.UUID) *PlanPricingHistoryCreate {
	if u != nil {
		pphc.SetID(*u)
	}
	return pphc
}

// SetPlan sets the "plan" edge to the SubscriptionPlan entity.
func (pphc *PlanPricingHistoryCreate) SetPlan(s *SubscriptionPlan) *PlanPricingHistoryCreate {
	return pphc.SetPlanID(s.ID)
}

// Mutation returns the PlanPricingHistoryMutation object of the builder.
func (pphc *PlanPricingHistoryCreate) Mutation() *PlanPricingHistoryMutation {
	return pphc.mutation
}

// Save creates the PlanPricingHistory in the database.
func (pphc *PlanPricingHistoryCreate) Save(ctx context.Context) (*PlanPricingHistory, error) {
	pphc.defaults()
	return withHooks(ctx, pphc.sqlSave, pphc.mutation, pphc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (pphc *PlanPricingHistoryCreate) SaveX(ctx context.Context) *PlanPricingHistory {
	v, err := pphc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (pphc *PlanPricingHistoryCreate) Exec(ctx context.Context) error {
	_, err := pphc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pphc *PlanPricingHistoryCreate) ExecX(ctx context.Context) {
	if err := pphc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (pphc *PlanPricingHistoryCreate) defaults() {
	if _, ok := pphc.mutation.Metadata(); !ok {
		v := planpricinghistory.DefaultMetadata
		pphc.mutation.SetMetadata(v)
	}
	if _, ok := pphc.mutation.CreatedAt(); !ok {
		v := planpricinghistory.DefaultCreatedAt()
		pphc.mutation.SetCreatedAt(v)
	}
	if _, ok := pphc.mutation.ID(); !ok {
		v := planpricinghistory.DefaultID()
		pphc.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (pphc *PlanPricingHistoryCreate) check() error {
	if _, ok := pphc.mutation.PlanID(); !ok {
		return &ValidationError{Name: "plan_id", err: errors.New(`ent: missing required field "PlanPricingHistory.plan_id"`)}
	}
	if _, ok := pphc.mutation.BasePrice(); !ok {
		return &ValidationError{Name: "base_price", err: errors.New(`ent: missing required field "PlanPricingHistory.base_price"`)}
	}
	if _, ok := pphc.mutation.EffectiveFrom(); !ok {
		return &ValidationError{Name: "effective_from", err: errors.New(`ent: missing required field "PlanPricingHistory.effective_from"`)}
	}
	if _, ok := pphc.mutation.Metadata(); !ok {
		return &ValidationError{Name: "metadata", err: errors.New(`ent: missing required field "PlanPricingHistory.metadata"`)}
	}
	if _, ok := pphc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "PlanPricingHistory.created_at"`)}
	}
	if _, ok := pphc.mutation.PlanID(); !ok {
		return &ValidationError{Name: "plan", err: errors.New(`ent: missing required edge "PlanPricingHistory.plan"`)}
	}
	return nil
}

func (pphc *PlanPricingHistoryCreate) sqlSave(ctx context.Context) (*PlanPricingHistory, error) {
	if err := pphc.check(); err != nil {
		return nil, err
	}
	_node, _spec := pphc.createSpec()
	if err := sqlgraph.CreateNode(ctx, pphc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	pphc.mutation.id = &_node.ID
	pphc.mutation.done = true
	return _node, nil
}

func (pphc *PlanPricingHistoryCreate) createSpec() (*PlanPricingHistory, *sqlgraph.CreateSpec) {
	var (
		_node = &PlanPricingHistory{config: pphc.config}
		_spec = sqlgraph.NewCreateSpec(planpricinghistory.Table, sqlgraph.NewFieldSpec(planpricinghistory.FieldID, field.TypeUUID))
	)
	if id, ok := pphc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := pphc.mutation.BasePrice(); ok {
		_spec.SetField(planpricinghistory.FieldBasePrice, field.TypeFloat64, value)
		_node.BasePrice = value
	}
	if value, ok := pphc.mutation.EffectiveFrom(); ok {
		_spec.SetField(planpricinghistory.FieldEffectiveFrom, field.TypeTime, value)
		_node.EffectiveFrom = value
	}
	if value, ok := pphc.mutation.EffectiveTo(); ok {
		_spec.SetField(planpricinghistory.FieldEffectiveTo, field.TypeTime, value)
		_node.EffectiveTo = value
	}
	if value, ok := pphc.mutation.ChangedBy(); ok {
		_spec.SetField(planpricinghistory.FieldChangedBy, field.TypeUUID, value)
		_node.ChangedBy = value
	}
	if value, ok := pphc.mutation.ChangeReason(); ok {
		_spec.SetField(planpricinghistory.FieldChangeReason, field.TypeString, value)
		_node.ChangeReason = value
	}
	if value, ok := pphc.mutation.Metadata(); ok {
		_spec.SetField(planpricinghistory.FieldMetadata, field.TypeJSON, value)
		_node.Metadata = value
	}
	if value, ok := pphc.mutation.CreatedAt(); ok {
		_spec.SetField(planpricinghistory.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := pphc.mutation.PlanIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   planpricinghistory.PlanTable,
			Columns: []string{planpricinghistory.PlanColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscriptionplan.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.PlanID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// PlanPricingHistoryCreateBulk is the builder for creating many PlanPricingHistory entities in bulk.
type PlanPricingHistoryCreateBulk struct {
	config
	err      error
	builders []*PlanPricingHistoryCreate
}

// Save creates the PlanPricingHistory entities in the database.
func (pphcb *PlanPricingHistoryCreateBulk) Save(ctx context.Context) ([]*PlanPricingHistory, error) {
	if pphcb.err != nil {
		return nil, pphcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(pphcb.builders))
	nodes := make([]*PlanPricingHistory, len(pphcb.builders))
	mutators := make([]Mutator, len(pphcb.builders))
	for i := range pphcb.builders {
		func(i int, root context.Context) {
			builder := pphcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PlanPricingHistoryMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, pphcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, pphcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, pphcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (pphcb *PlanPricingHistoryCreateBulk) SaveX(ctx context.Context) []*PlanPricingHistory {
	v, err := pphcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (pphcb *PlanPricingHistoryCreateBulk) Exec(ctx context.Context) error {
	_, err := pphcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pphcb *PlanPricingHistoryCreateBulk) ExecX(ctx context.Context) {
	if err := pphcb.Exec(ctx); err != nil {
		panic(err)
	}
}
