// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/bengobox/subscription-service/internal/ent/planpricinghistory"
	"github.com/bengobox/subscription-service/internal/ent/predicate"
)

// PlanPricingHistoryDelete is the builder for deleting a PlanPricingHistory entity.
type PlanPricingHistoryDelete struct {
	config
	hooks    []Hook
	mutation *PlanPricingHistoryMutation
}

// Where appends a list predicates to the PlanPricingHistoryDelete builder.
func (_d *PlanPricingHistoryDelete) Where(ps ...predicate.PlanPricingHistory) *PlanPricingHistoryDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *PlanPricingHistoryDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *PlanPricingHistoryDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *PlanPricingHistoryDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(planpricinghistory.Table, sqlgraph.NewFieldSpec(planpricinghistory.FieldID, field.TypeUUID))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// PlanPricingHistoryDeleteOne is the builder for deleting a single PlanPricingHistory entity.
type PlanPricingHistoryDeleteOne struct {
	_d *PlanPricingHistoryDelete
}

// Where appends a list predicates to the PlanPricingHistoryDelete builder.
func (_d *PlanPricingHistoryDeleteOne) Where(ps ...predicate.PlanPricingHistory) *PlanPricingHistoryDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *PlanPricingHistoryDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{planpricinghistory.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *PlanPricingHistoryDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
