// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/bengobox/subscription-service/internal/ent/planfeature"
	"github.com/bengobox/subscription-service/internal/ent/subscriptionplan"
	"github.com/google/uuid"
)

// PlanFeature is the model entity for the PlanFeature schema.
type PlanFeature struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// Plan identifier
	PlanID uuid.UUID `json:"plan_id,omitempty"`
	// Feature code (loyalty_program, multi_outlet, pos_integration, etc.)
	FeatureCode string `json:"feature_code,omitempty"`
	// IsIncluded holds the value of the "is_included" field.
	IsIncluded bool `json:"is_included,omitempty"`
	// Feature-specific limit (e.g., max 5 outlets)
	LimitValue int `json:"limit_value,omitempty"`
	// Price per unit above the limit
	OverageUnitPrice float64 `json:"overage_unit_price,omitempty"`
	// Metadata holds the value of the "metadata" field.
	Metadata map[string]interface{} `json:"metadata,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the PlanFeatureQuery when eager-loading is set.
	Edges        PlanFeatureEdges `json:"edges"`
	selectValues sql.SelectValues
}

// PlanFeatureEdges holds the relations/edges for other nodes in the graph.
type PlanFeatureEdges struct {
	// Plan holds the value of the plan edge.
	Plan *SubscriptionPlan `json:"plan,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// PlanOrErr returns the Plan value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e PlanFeatureEdges) PlanOrErr() (*SubscriptionPlan, error) {
	if e.Plan != nil {
		return e.Plan, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: subscriptionplan.Label}
	}
	return nil, &NotLoadedError{edge: "plan"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*PlanFeature) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case planfeature.FieldMetadata:
			values[i] = new([]byte)
		case planfeature.FieldIsIncluded:
			values[i] = new(sql.NullBool)
		case planfeature.FieldOverageUnitPrice:
			values[i] = new(sql.NullFloat64)
		case planfeature.FieldLimitValue:
			values[i] = new(sql.NullInt64)
		case planfeature.FieldFeatureCode:
			values[i] = new(sql.NullString)
		case planfeature.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case planfeature.FieldID, planfeature.FieldPlanID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the PlanFeature fields.
func (_m *PlanFeature) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case planfeature.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case planfeature.FieldPlanID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field plan_id", values[i])
			} else if value != nil {
				_m.PlanID = *value
			}
		case planfeature.FieldFeatureCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field feature_code", values[i])
			} else if value.Valid {
				_m.FeatureCode = value.String
			}
		case planfeature.FieldIsIncluded:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_included", values[i])
			} else if value.Valid {
				_m.IsIncluded = value.Bool
			}
		case planfeature.FieldLimitValue:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field limit_value", values[i])
			} else if value.Valid {
				_m.LimitValue = int(value.Int64)
			}
		case planfeature.FieldOverageUnitPrice:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field overage_unit_price", values[i])
			} else if value.Valid {
				_m.OverageUnitPrice = value.Float64
			}
		case planfeature.FieldMetadata:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field metadata", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Metadata); err != nil {
					return fmt.Errorf("unmarshal field metadata: %w", err)
				}
			}
		case planfeature.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the PlanFeature.
// This includes values selected through modifiers, order, etc.
func (_m *PlanFeature) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryPlan queries the "plan" edge of the PlanFeature entity.
func (_m *PlanFeature) QueryPlan() *SubscriptionPlanQuery {
	return NewPlanFeatureClient(_m.config).QueryPlan(_m)
}

// Update returns a builder for updating this PlanFeature.
// Note that you need to call PlanFeature.Unwrap() before calling this method if this PlanFeature
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *PlanFeature) Update() *PlanFeatureUpdateOne {
	return NewPlanFeatureClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the PlanFeature entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *PlanFeature) Unwrap() *PlanFeature {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: PlanFeature is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *PlanFeature) String() string {
	var builder strings.Builder
	builder.WriteString("PlanFeature(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("plan_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.PlanID))
	builder.WriteString(", ")
	builder.WriteString("feature_code=")
	builder.WriteString(_m.FeatureCode)
	builder.WriteString(", ")
	builder.WriteString("is_included=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsIncluded))
	builder.WriteString(", ")
	builder.WriteString("limit_value=")
	builder.WriteString(fmt.Sprintf("%v", _m.LimitValue))
	builder.WriteString(", ")
	builder.WriteString("overage_unit_price=")
	builder.WriteString(fmt.Sprintf("%v", _m.OverageUnitPrice))
	builder.WriteString(", ")
	builder.WriteString("metadata=")
	builder.WriteString(fmt.Sprintf("%v", _m.Metadata))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// PlanFeatures is a parsable slice of PlanFeature.
type PlanFeatures []*PlanFeature
