// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/bengobox/subscription-service/internal/ent/product"
	"github.com/bengobox/subscription-service/internal/ent/productsubscription"
	"github.com/bengobox/subscription-service/internal/ent/tenantsubscription"
	"github.com/google/uuid"
)

// ProductSubscription is the model entity for the ProductSubscription schema.
type ProductSubscription struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// FK to tenant_subscriptions
	TenantSubscriptionID uuid.UUID `json:"tenant_subscription_id,omitempty"`
	// Product code (ordering, logistics, etc.)
	ProductCode string `json:"product_code,omitempty"`
	// FK to products
	ProductID uuid.UUID `json:"product_id,omitempty"`
	// Status holds the value of the "status" field.
	Status productsubscription.Status `json:"status,omitempty"`
	// End of product-level trial period
	TrialEndsAt *time.Time `json:"trial_ends_at,omitempty"`
	// When this product was activated
	ActivatedAt *time.Time `json:"activated_at,omitempty"`
	// When this product was deactivated
	DeactivatedAt *time.Time `json:"deactivated_at,omitempty"`
	// Metadata holds the value of the "metadata" field.
	Metadata map[string]interface{} `json:"metadata,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ProductSubscriptionQuery when eager-loading is set.
	Edges        ProductSubscriptionEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ProductSubscriptionEdges holds the relations/edges for other nodes in the graph.
type ProductSubscriptionEdges struct {
	// TenantSubscription holds the value of the tenant_subscription edge.
	TenantSubscription *TenantSubscription `json:"tenant_subscription,omitempty"`
	// Product holds the value of the product edge.
	Product *Product `json:"product,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// TenantSubscriptionOrErr returns the TenantSubscription value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ProductSubscriptionEdges) TenantSubscriptionOrErr() (*TenantSubscription, error) {
	if e.TenantSubscription != nil {
		return e.TenantSubscription, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: tenantsubscription.Label}
	}
	return nil, &NotLoadedError{edge: "tenant_subscription"}
}

// ProductOrErr returns the Product value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ProductSubscriptionEdges) ProductOrErr() (*Product, error) {
	if e.Product != nil {
		return e.Product, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: product.Label}
	}
	return nil, &NotLoadedError{edge: "product"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ProductSubscription) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case productsubscription.FieldMetadata:
			values[i] = new([]byte)
		case productsubscription.FieldProductCode, productsubscription.FieldStatus:
			values[i] = new(sql.NullString)
		case productsubscription.FieldTrialEndsAt, productsubscription.FieldActivatedAt, productsubscription.FieldDeactivatedAt, productsubscription.FieldCreatedAt, productsubscription.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case productsubscription.FieldID, productsubscription.FieldTenantSubscriptionID, productsubscription.FieldProductID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ProductSubscription fields.
func (ps *ProductSubscription) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case productsubscription.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				ps.ID = *value
			}
		case productsubscription.FieldTenantSubscriptionID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field tenant_subscription_id", values[i])
			} else if value != nil {
				ps.TenantSubscriptionID = *value
			}
		case productsubscription.FieldProductCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field product_code", values[i])
			} else if value.Valid {
				ps.ProductCode = value.String
			}
		case productsubscription.FieldProductID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field product_id", values[i])
			} else if value != nil {
				ps.ProductID = *value
			}
		case productsubscription.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				ps.Status = productsubscription.Status(value.String)
			}
		case productsubscription.FieldTrialEndsAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field trial_ends_at", values[i])
			} else if value.Valid {
				ps.TrialEndsAt = new(time.Time)
				*ps.TrialEndsAt = value.Time
			}
		case productsubscription.FieldActivatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field activated_at", values[i])
			} else if value.Valid {
				ps.ActivatedAt = new(time.Time)
				*ps.ActivatedAt = value.Time
			}
		case productsubscription.FieldDeactivatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deactivated_at", values[i])
			} else if value.Valid {
				ps.DeactivatedAt = new(time.Time)
				*ps.DeactivatedAt = value.Time
			}
		case productsubscription.FieldMetadata:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field metadata", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &ps.Metadata); err != nil {
					return fmt.Errorf("unmarshal field metadata: %w", err)
				}
			}
		case productsubscription.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				ps.CreatedAt = value.Time
			}
		case productsubscription.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				ps.UpdatedAt = value.Time
			}
		default:
			ps.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ProductSubscription.
// This includes values selected through modifiers, order, etc.
func (ps *ProductSubscription) Value(name string) (ent.Value, error) {
	return ps.selectValues.Get(name)
}

// QueryTenantSubscription queries the "tenant_subscription" edge of the ProductSubscription entity.
func (ps *ProductSubscription) QueryTenantSubscription() *TenantSubscriptionQuery {
	return NewProductSubscriptionClient(ps.config).QueryTenantSubscription(ps)
}

// QueryProduct queries the "product" edge of the ProductSubscription entity.
func (ps *ProductSubscription) QueryProduct() *ProductQuery {
	return NewProductSubscriptionClient(ps.config).QueryProduct(ps)
}

// Update returns a builder for updating this ProductSubscription.
// Note that you need to call ProductSubscription.Unwrap() before calling this method if this ProductSubscription
// was returned from a transaction, and the transaction was committed or rolled back.
func (ps *ProductSubscription) Update() *ProductSubscriptionUpdateOne {
	return NewProductSubscriptionClient(ps.config).UpdateOne(ps)
}

// Unwrap unwraps the ProductSubscription entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (ps *ProductSubscription) Unwrap() *ProductSubscription {
	_tx, ok := ps.config.driver.(*txDriver)
	if !ok {
		panic("ent: ProductSubscription is not a transactional entity")
	}
	ps.config.driver = _tx.drv
	return ps
}

// String implements the fmt.Stringer.
func (ps *ProductSubscription) String() string {
	var builder strings.Builder
	builder.WriteString("ProductSubscription(")
	builder.WriteString(fmt.Sprintf("id=%v, ", ps.ID))
	builder.WriteString("tenant_subscription_id=")
	builder.WriteString(fmt.Sprintf("%v", ps.TenantSubscriptionID))
	builder.WriteString(", ")
	builder.WriteString("product_code=")
	builder.WriteString(ps.ProductCode)
	builder.WriteString(", ")
	builder.WriteString("product_id=")
	builder.WriteString(fmt.Sprintf("%v", ps.ProductID))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", ps.Status))
	builder.WriteString(", ")
	if v := ps.TrialEndsAt; v != nil {
		builder.WriteString("trial_ends_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := ps.ActivatedAt; v != nil {
		builder.WriteString("activated_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := ps.DeactivatedAt; v != nil {
		builder.WriteString("deactivated_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("metadata=")
	builder.WriteString(fmt.Sprintf("%v", ps.Metadata))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(ps.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(ps.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// ProductSubscriptions is a parsable slice of ProductSubscription.
type ProductSubscriptions []*ProductSubscription
