// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/bengobox/subscription-service/internal/ent/product"
	"github.com/bengobox/subscription-service/internal/ent/productsubscription"
	"github.com/google/uuid"
)

// ProductCreate is the builder for creating a Product entity.
type ProductCreate struct {
	config
	mutation *ProductMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCode sets the "code" field.
func (pc *ProductCreate) SetCode(s string) *ProductCreate {
	pc.mutation.SetCode(s)
	return pc
}

// SetName sets the "name" field.
func (pc *ProductCreate) SetName(s string) *ProductCreate {
	pc.mutation.SetName(s)
	return pc
}

// SetDescription sets the "description" field.
func (pc *ProductCreate) SetDescription(s string) *ProductCreate {
	pc.mutation.SetDescription(s)
	return pc
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (pc *ProductCreate) SetNillableDescription(s *string) *ProductCreate {
	if s != nil {
		pc.SetDescription(*s)
	}
	return pc
}

// SetCategory sets the "category" field.
func (pc *ProductCreate) SetCategory(pr product.Category) *ProductCreate {
	pc.mutation.SetCategory(pr)
	return pc
}

// SetStatus sets the "status" field.
func (pc *ProductCreate) SetStatus(pr product.Status) *ProductCreate {
	pc.mutation.SetStatus(pr)
	return pc
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (pc *ProductCreate) SetNillableStatus(pr *product.Status) *ProductCreate {
	if pr != nil {
		pc.SetStatus(*pr)
	}
	return pc
}

// SetDependencies sets the "dependencies" field.
func (pc *ProductCreate) SetDependencies(s []string) *ProductCreate {
	pc.mutation.SetDependencies(s)
	return pc
}

// SetIsPlatform sets the "is_platform" field.
func (pc *ProductCreate) SetIsPlatform(b bool) *ProductCreate {
	pc.mutation.SetIsPlatform(b)
	return pc
}

// SetNillableIsPlatform sets the "is_platform" field if the given value is not nil.
func (pc *ProductCreate) SetNillableIsPlatform(b *bool) *ProductCreate {
	if b != nil {
		pc.SetIsPlatform(*b)
	}
	return pc
}

// SetMonthlyPrice sets the "monthly_price" field.
func (pc *ProductCreate) SetMonthlyPrice(f float64) *ProductCreate {
	pc.mutation.SetMonthlyPrice(f)
	return pc
}

// SetNillableMonthlyPrice sets the "monthly_price" field if the given value is not nil.
func (pc *ProductCreate) SetNillableMonthlyPrice(f *float64) *ProductCreate {
	if f != nil {
		pc.SetMonthlyPrice(*f)
	}
	return pc
}

// SetIncludedInBundle sets the "included_in_bundle" field.
func (pc *ProductCreate) SetIncludedInBundle(b bool) *ProductCreate {
	pc.mutation.SetIncludedInBundle(b)
	return pc
}

// SetNillableIncludedInBundle sets the "included_in_bundle" field if the given value is not nil.
func (pc *ProductCreate) SetNillableIncludedInBundle(b *bool) *ProductCreate {
	if b != nil {
		pc.SetIncludedInBundle(*b)
	}
	return pc
}

// SetSortOrder sets the "sort_order" field.
func (pc *ProductCreate) SetSortOrder(i int) *ProductCreate {
	pc.mutation.SetSortOrder(i)
	return pc
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (pc *ProductCreate) SetNillableSortOrder(i *int) *ProductCreate {
	if i != nil {
		pc.SetSortOrder(*i)
	}
	return pc
}

// SetMetadata sets the "metadata" field.
func (pc *ProductCreate) SetMetadata(m map[string]interface{}) *ProductCreate {
	pc.mutation.SetMetadata(m)
	return pc
}

// SetCreatedAt sets the "created_at" field.
func (pc *ProductCreate) SetCreatedAt(t time.Time) *ProductCreate {
	pc.mutation.SetCreatedAt(t)
	return pc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (pc *ProductCreate) SetNillableCreatedAt(t *time.Time) *ProductCreate {
	if t != nil {
		pc.SetCreatedAt(*t)
	}
	return pc
}

// SetUpdatedAt sets the "updated_at" field.
func (pc *ProductCreate) SetUpdatedAt(t time.Time) *ProductCreate {
	pc.mutation.SetUpdatedAt(t)
	return pc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (pc *ProductCreate) SetNillableUpdatedAt(t *time.Time) *ProductCreate {
	if t != nil {
		pc.SetUpdatedAt(*t)
	}
	return pc
}

// SetID sets the "id" field.
func (pc *ProductCreate) SetID(u uuid.UUID) *ProductCreate {
	pc.mutation.SetID(u)
	return pc
}

// SetNillableID sets the "id" field if the given value is not nil.
func (pc *ProductCreate) SetNillableID(u *uuid.UUID) *ProductCreate {
	if u != nil {
		pc.SetID(*u)
	}
	return pc
}

// AddProductSubscriptionIDs adds the "product_subscriptions" edge to the ProductSubscription entity by IDs.
func (pc *ProductCreate) AddProductSubscriptionIDs(ids ...uuid.UUID) *ProductCreate {
	pc.mutation.AddProductSubscriptionIDs(ids...)
	return pc
}

// AddProductSubscriptions adds the "product_subscriptions" edges to the ProductSubscription entity.
func (pc *ProductCreate) AddProductSubscriptions(p ...*ProductSubscription) *ProductCreate {
	ids := make([]uuid.UUID, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return pc.AddProductSubscriptionIDs(ids...)
}

// Mutation returns the ProductMutation object of the builder.
func (pc *ProductCreate) Mutation() *ProductMutation {
	return pc.mutation
}

// Save creates the Product in the database.
func (pc *ProductCreate) Save(ctx context.Context) (*Product, error) {
	pc.defaults()
	return withHooks(ctx, pc.sqlSave, pc.mutation, pc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (pc *ProductCreate) SaveX(ctx context.Context) *Product {
	v, err := pc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (pc *ProductCreate) Exec(ctx context.Context) error {
	_, err := pc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pc *ProductCreate) ExecX(ctx context.Context) {
	if err := pc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (pc *ProductCreate) defaults() {
	if _, ok := pc.mutation.Status(); !ok {
		v := product.DefaultStatus
		pc.mutation.SetStatus(v)
	}
	if _, ok := pc.mutation.IsPlatform(); !ok {
		v := product.DefaultIsPlatform
		pc.mutation.SetIsPlatform(v)
	}
	if _, ok := pc.mutation.MonthlyPrice(); !ok {
		v := product.DefaultMonthlyPrice
		pc.mutation.SetMonthlyPrice(v)
	}
	if _, ok := pc.mutation.IncludedInBundle(); !ok {
		v := product.DefaultIncludedInBundle
		pc.mutation.SetIncludedInBundle(v)
	}
	if _, ok := pc.mutation.SortOrder(); !ok {
		v := product.DefaultSortOrder
		pc.mutation.SetSortOrder(v)
	}
	if _, ok := pc.mutation.Metadata(); !ok {
		v := product.DefaultMetadata
		pc.mutation.SetMetadata(v)
	}
	if _, ok := pc.mutation.CreatedAt(); !ok {
		v := product.DefaultCreatedAt()
		pc.mutation.SetCreatedAt(v)
	}
	if _, ok := pc.mutation.UpdatedAt(); !ok {
		v := product.DefaultUpdatedAt()
		pc.mutation.SetUpdatedAt(v)
	}
	if _, ok := pc.mutation.ID(); !ok {
		v := product.DefaultID()
		pc.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (pc *ProductCreate) check() error {
	if _, ok := pc.mutation.Code(); !ok {
		return &ValidationError{Name: "code", err: errors.New(`ent: missing required field "Product.code"`)}
	}
	if v, ok := pc.mutation.Code(); ok {
		if err := product.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "Product.code": %w`, err)}
		}
	}
	if _, ok := pc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Product.name"`)}
	}
	if v, ok := pc.mutation.Name(); ok {
		if err := product.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Product.name": %w`, err)}
		}
	}
	if _, ok := pc.mutation.Category(); !ok {
		return &ValidationError{Name: "category", err: errors.New(`ent: missing required field "Product.category"`)}
	}
	if v, ok := pc.mutation.Category(); ok {
		if err := product.CategoryValidator(v); err != nil {
			return &ValidationError{Name: "category", err: fmt.Errorf(`ent: validator failed for field "Product.category": %w`, err)}
		}
	}
	if _, ok := pc.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Product.status"`)}
	}
	if v, ok := pc.mutation.Status(); ok {
		if err := product.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Product.status": %w`, err)}
		}
	}
	if _, ok := pc.mutation.IsPlatform(); !ok {
		return &ValidationError{Name: "is_platform", err: errors.New(`ent: missing required field "Product.is_platform"`)}
	}
	if _, ok := pc.mutation.MonthlyPrice(); !ok {
		return &ValidationError{Name: "monthly_price", err: errors.New(`ent: missing required field "Product.monthly_price"`)}
	}
	if _, ok := pc.mutation.IncludedInBundle(); !ok {
		return &ValidationError{Name: "included_in_bundle", err: errors.New(`ent: missing required field "Product.included_in_bundle"`)}
	}
	if _, ok := pc.mutation.SortOrder(); !ok {
		return &ValidationError{Name: "sort_order", err: errors.New(`ent: missing required field "Product.sort_order"`)}
	}
	if _, ok := pc.mutation.Metadata(); !ok {
		return &ValidationError{Name: "metadata", err: errors.New(`ent: missing required field "Product.metadata"`)}
	}
	if _, ok := pc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Product.created_at"`)}
	}
	if _, ok := pc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Product.updated_at"`)}
	}
	return nil
}

func (pc *ProductCreate) sqlSave(ctx context.Context) (*Product, error) {
	if err := pc.check(); err != nil {
		return nil, err
	}
	_node, _spec := pc.createSpec()
	if err := sqlgraph.CreateNode(ctx, pc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	pc.mutation.id = &_node.ID
	pc.mutation.done = true
	return _node, nil
}

func (pc *ProductCreate) createSpec() (*Product, *sqlgraph.CreateSpec) {
	var (
		_node = &Product{config: pc.config}
		_spec = sqlgraph.NewCreateSpec(product.Table, sqlgraph.NewFieldSpec(product.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = pc.conflict
	if id, ok := pc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := pc.mutation.Code(); ok {
		_spec.SetField(product.FieldCode, field.TypeString, value)
		_node.Code = value
	}
	if value, ok := pc.mutation.Name(); ok {
		_spec.SetField(product.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := pc.mutation.Description(); ok {
		_spec.SetField(product.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := pc.mutation.Category(); ok {
		_spec.SetField(product.FieldCategory, field.TypeEnum, value)
		_node.Category = value
	}
	if value, ok := pc.mutation.Status(); ok {
		_spec.SetField(product.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := pc.mutation.Dependencies(); ok {
		_spec.SetField(product.FieldDependencies, field.TypeJSON, value)
		_node.Dependencies = value
	}
	if value, ok := pc.mutation.IsPlatform(); ok {
		_spec.SetField(product.FieldIsPlatform, field.TypeBool, value)
		_node.IsPlatform = value
	}
	if value, ok := pc.mutation.MonthlyPrice(); ok {
		_spec.SetField(product.FieldMonthlyPrice, field.TypeFloat64, value)
		_node.MonthlyPrice = value
	}
	if value, ok := pc.mutation.IncludedInBundle(); ok {
		_spec.SetField(product.FieldIncludedInBundle, field.TypeBool, value)
		_node.IncludedInBundle = value
	}
	if value, ok := pc.mutation.SortOrder(); ok {
		_spec.SetField(product.FieldSortOrder, field.TypeInt, value)
		_node.SortOrder = value
	}
	if value, ok := pc.mutation.Metadata(); ok {
		_spec.SetField(product.FieldMetadata, field.TypeJSON, value)
		_node.Metadata = value
	}
	if value, ok := pc.mutation.CreatedAt(); ok {
		_spec.SetField(product.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := pc.mutation.UpdatedAt(); ok {
		_spec.SetField(product.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := pc.mutation.ProductSubscriptionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   product.ProductSubscriptionsTable,
			Columns: []string{product.ProductSubscriptionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(productsubscription.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Product.Create().
//		SetCode(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ProductUpsert) {
//			SetCode(v+v).
//		}).
//		Exec(ctx)
func (pc *ProductCreate) OnConflict(opts ...sql.ConflictOption) *ProductUpsertOne {
	pc.conflict = opts
	return &ProductUpsertOne{
		create: pc,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Product.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (pc *ProductCreate) OnConflictColumns(columns ...string) *ProductUpsertOne {
	pc.conflict = append(pc.conflict, sql.ConflictColumns(columns...))
	return &ProductUpsertOne{
		create: pc,
	}
}

type (
	// ProductUpsertOne is the builder for "upsert"-ing
	//  one Product node.
	ProductUpsertOne struct {
		create *ProductCreate
	}

	// ProductUpsert is the "OnConflict" setter.
	ProductUpsert struct {
		*sql.UpdateSet
	}
)

// SetCode sets the "code" field.
func (u *ProductUpsert) SetCode(v string) *ProductUpsert {
	u.Set(product.FieldCode, v)
	return u
}

// UpdateCode sets the "code" field to the value that was provided on create.
func (u *ProductUpsert) UpdateCode() *ProductUpsert {
	u.SetExcluded(product.FieldCode)
	return u
}

// SetName sets the "name" field.
func (u *ProductUpsert) SetName(v string) *ProductUpsert {
	u.Set(product.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *ProductUpsert) UpdateName() *ProductUpsert {
	u.SetExcluded(product.FieldName)
	return u
}

// SetDescription sets the "description" field.
func (u *ProductUpsert) SetDescription(v string) *ProductUpsert {
	u.Set(product.FieldDescription, v)
	return u
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *ProductUpsert) UpdateDescription() *ProductUpsert {
	u.SetExcluded(product.FieldDescription)
	return u
}

// ClearDescription clears the value of the "description" field.
func (u *ProductUpsert) ClearDescription() *ProductUpsert {
	u.SetNull(product.FieldDescription)
	return u
}

// SetCategory sets the "category" field.
func (u *ProductUpsert) SetCategory(v product.Category) *ProductUpsert {
	u.Set(product.FieldCategory, v)
	return u
}

// UpdateCategory sets the "category" field to the value that was provided on create.
func (u *ProductUpsert) UpdateCategory() *ProductUpsert {
	u.SetExcluded(product.FieldCategory)
	return u
}

// SetStatus sets the "status" field.
func (u *ProductUpsert) SetStatus(v product.Status) *ProductUpsert {
	u.Set(product.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ProductUpsert) UpdateStatus() *ProductUpsert {
	u.SetExcluded(product.FieldStatus)
	return u
}

// SetDependencies sets the "dependencies" field.
func (u *ProductUpsert) SetDependencies(v []string) *ProductUpsert {
	u.Set(product.FieldDependencies, v)
	return u
}

// UpdateDependencies sets the "dependencies" field to the value that was provided on create.
func (u *ProductUpsert) UpdateDependencies() *ProductUpsert {
	u.SetExcluded(product.FieldDependencies)
	return u
}

// ClearDependencies clears the value of the "dependencies" field.
func (u *ProductUpsert) ClearDependencies() *ProductUpsert {
	u.SetNull(product.FieldDependencies)
	return u
}

// SetIsPlatform sets the "is_platform" field.
func (u *ProductUpsert) SetIsPlatform(v bool) *ProductUpsert {
	u.Set(product.FieldIsPlatform, v)
	return u
}

// UpdateIsPlatform sets the "is_platform" field to the value that was provided on create.
func (u *ProductUpsert) UpdateIsPlatform() *ProductUpsert {
	u.SetExcluded(product.FieldIsPlatform)
	return u
}

// SetMonthlyPrice sets the "monthly_price" field.
func (u *ProductUpsert) SetMonthlyPrice(v float64) *ProductUpsert {
	u.Set(product.FieldMonthlyPrice, v)
	return u
}

// UpdateMonthlyPrice sets the "monthly_price" field to the value that was provided on create.
func (u *ProductUpsert) UpdateMonthlyPrice() *ProductUpsert {
	u.SetExcluded(product.FieldMonthlyPrice)
	return u
}

// AddMonthlyPrice adds v to the "monthly_price" field.
func (u *ProductUpsert) AddMonthlyPrice(v float64) *ProductUpsert {
	u.Add(product.FieldMonthlyPrice, v)
	return u
}

// SetIncludedInBundle sets the "included_in_bundle" field.
func (u *ProductUpsert) SetIncludedInBundle(v bool) *ProductUpsert {
	u.Set(product.FieldIncludedInBundle, v)
	return u
}

// UpdateIncludedInBundle sets the "included_in_bundle" field to the value that was provided on create.
func (u *ProductUpsert) UpdateIncludedInBundle() *ProductUpsert {
	u.SetExcluded(product.FieldIncludedInBundle)
	return u
}

// SetSortOrder sets the "sort_order" field.
func (u *ProductUpsert) SetSortOrder(v int) *ProductUpsert {
	u.Set(product.FieldSortOrder, v)
	return u
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *ProductUpsert) UpdateSortOrder() *ProductUpsert {
	u.SetExcluded(product.FieldSortOrder)
	return u
}

// AddSortOrder adds v to the "sort_order" field.
func (u *ProductUpsert) AddSortOrder(v int) *ProductUpsert {
	u.Add(product.FieldSortOrder, v)
	return u
}

// SetMetadata sets the "metadata" field.
func (u *ProductUpsert) SetMetadata(v map[string]interface{}) *ProductUpsert {
	u.Set(product.FieldMetadata, v)
	return u
}

// UpdateMetadata sets the "metadata" field to the value that was provided on create.
func (u *ProductUpsert) UpdateMetadata() *ProductUpsert {
	u.SetExcluded(product.FieldMetadata)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ProductUpsert) SetUpdatedAt(v time.Time) *ProductUpsert {
	u.Set(product.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ProductUpsert) UpdateUpdatedAt() *ProductUpsert {
	u.SetExcluded(product.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.Product.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(product.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ProductUpsertOne) UpdateNewValues() *ProductUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(product.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(product.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Product.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ProductUpsertOne) Ignore() *ProductUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ProductUpsertOne) DoNothing() *ProductUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ProductCreate.OnConflict
// documentation for more info.
func (u *ProductUpsertOne) Update(set func(*ProductUpsert)) *ProductUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ProductUpsert{UpdateSet: update})
	}))
	return u
}

// SetCode sets the "code" field.
func (u *ProductUpsertOne) SetCode(v string) *ProductUpsertOne {
	return u.Update(func(s *ProductUpsert) {
		s.SetCode(v)
	})
}

// UpdateCode sets the "code" field to the value that was provided on create.
func (u *ProductUpsertOne) UpdateCode() *ProductUpsertOne {
	return u.Update(func(s *ProductUpsert) {
		s.UpdateCode()
	})
}

// SetName sets the "name" field.
func (u *ProductUpsertOne) SetName(v string) *ProductUpsertOne {
	return u.Update(func(s *ProductUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *ProductUpsertOne) UpdateName() *ProductUpsertOne {
	return u.Update(func(s *ProductUpsert) {
		s.UpdateName()
	})
}

// SetDescription sets the "description" field.
func (u *ProductUpsertOne) SetDescription(v string) *ProductUpsertOne {
	return u.Update(func(s *ProductUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *ProductUpsertOne) UpdateDescription() *ProductUpsertOne {
	return u.Update(func(s *ProductUpsert) {
		s.UpdateDescription()
	})
}

// ClearDescription clears the value of the "description" field.
func (u *ProductUpsertOne) ClearDescription() *ProductUpsertOne {
	return u.Update(func(s *ProductUpsert) {
		s.ClearDescription()
	})
}

// SetCategory sets the "category" field.
func (u *ProductUpsertOne) SetCategory(v product.Category) *ProductUpsertOne {
	return u.Update(func(s *ProductUpsert) {
		s.SetCategory(v)
	})
}

// UpdateCategory sets the "category" field to the value that was provided on create.
func (u *ProductUpsertOne) UpdateCategory() *ProductUpsertOne {
	return u.Update(func(s *ProductUpsert) {
		s.UpdateCategory()
	})
}

// SetStatus sets the "status" field.
func (u *ProductUpsertOne) SetStatus(v product.Status) *ProductUpsertOne {
	return u.Update(func(s *ProductUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ProductUpsertOne) UpdateStatus() *ProductUpsertOne {
	return u.Update(func(s *ProductUpsert) {
		s.UpdateStatus()
	})
}

// SetDependencies sets the "dependencies" field.
func (u *ProductUpsertOne) SetDependencies(v []string) *ProductUpsertOne {
	return u.Update(func(s *ProductUpsert) {
		s.SetDependencies(v)
	})
}

// UpdateDependencies sets the "dependencies" field to the value that was provided on create.
func (u *ProductUpsertOne) UpdateDependencies() *ProductUpsertOne {
	return u.Update(func(s *ProductUpsert) {
		s.UpdateDependencies()
	})
}

// ClearDependencies clears the value of the "dependencies" field.
func (u *ProductUpsertOne) ClearDependencies() *ProductUpsertOne {
	return u.Update(func(s *ProductUpsert) {
		s.ClearDependencies()
	})
}

// SetIsPlatform sets the "is_platform" field.
func (u *ProductUpsertOne) SetIsPlatform(v bool) *ProductUpsertOne {
	return u.Update(func(s *ProductUpsert) {
		s.SetIsPlatform(v)
	})
}

// UpdateIsPlatform sets the "is_platform" field to the value that was provided on create.
func (u *ProductUpsertOne) UpdateIsPlatform() *ProductUpsertOne {
	return u.Update(func(s *ProductUpsert) {
		s.UpdateIsPlatform()
	})
}

// SetMonthlyPrice sets the "monthly_price" field.
func (u *ProductUpsertOne) SetMonthlyPrice(v float64) *ProductUpsertOne {
	return u.Update(func(s *ProductUpsert) {
		s.SetMonthlyPrice(v)
	})
}

// AddMonthlyPrice adds v to the "monthly_price" field.
func (u *ProductUpsertOne) AddMonthlyPrice(v float64) *ProductUpsertOne {
	return u.Update(func(s *ProductUpsert) {
		s.AddMonthlyPrice(v)
	})
}

// UpdateMonthlyPrice sets the "monthly_price" field to the value that was provided on create.
func (u *ProductUpsertOne) UpdateMonthlyPrice() *ProductUpsertOne {
	return u.Update(func(s *ProductUpsert) {
		s.UpdateMonthlyPrice()
	})
}

// SetIncludedInBundle sets the "included_in_bundle" field.
func (u *ProductUpsertOne) SetIncludedInBundle(v bool) *ProductUpsertOne {
	return u.Update(func(s *ProductUpsert) {
		s.SetIncludedInBundle(v)
	})
}

// UpdateIncludedInBundle sets the "included_in_bundle" field to the value that was provided on create.
func (u *ProductUpsertOne) UpdateIncludedInBundle() *ProductUpsertOne {
	return u.Update(func(s *ProductUpsert) {
		s.UpdateIncludedInBundle()
	})
}

// SetSortOrder sets the "sort_order" field.
func (u *ProductUpsertOne) SetSortOrder(v int) *ProductUpsertOne {
	return u.Update(func(s *ProductUpsert) {
		s.SetSortOrder(v)
	})
}

// AddSortOrder adds v to the "sort_order" field.
func (u *ProductUpsertOne) AddSortOrder(v int) *ProductUpsertOne {
	return u.Update(func(s *ProductUpsert) {
		s.AddSortOrder(v)
	})
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *ProductUpsertOne) UpdateSortOrder() *ProductUpsertOne {
	return u.Update(func(s *ProductUpsert) {
		s.UpdateSortOrder()
	})
}

// SetMetadata sets the "metadata" field.
func (u *ProductUpsertOne) SetMetadata(v map[string]interface{}) *ProductUpsertOne {
	return u.Update(func(s *ProductUpsert) {
		s.SetMetadata(v)
	})
}

// UpdateMetadata sets the "metadata" field to the value that was provided on create.
func (u *ProductUpsertOne) UpdateMetadata() *ProductUpsertOne {
	return u.Update(func(s *ProductUpsert) {
		s.UpdateMetadata()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ProductUpsertOne) SetUpdatedAt(v time.Time) *ProductUpsertOne {
	return u.Update(func(s *ProductUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ProductUpsertOne) UpdateUpdatedAt() *ProductUpsertOne {
	return u.Update(func(s *ProductUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *ProductUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ProductCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ProductUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ProductUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: ProductUpsertOne.ID is not supported by MySQL driver. Use ProductUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ProductUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ProductCreateBulk is the builder for creating many Product entities in bulk.
type ProductCreateBulk struct {
	config
	err      error
	builders []*ProductCreate
	conflict []sql.ConflictOption
}

// Save creates the Product entities in the database.
func (pcb *ProductCreateBulk) Save(ctx context.Context) ([]*Product, error) {
	if pcb.err != nil {
		return nil, pcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(pcb.builders))
	nodes := make([]*Product, len(pcb.builders))
	mutators := make([]Mutator, len(pcb.builders))
	for i := range pcb.builders {
		func(i int, root context.Context) {
			builder := pcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ProductMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, pcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = pcb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, pcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, pcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (pcb *ProductCreateBulk) SaveX(ctx context.Context) []*Product {
	v, err := pcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (pcb *ProductCreateBulk) Exec(ctx context.Context) error {
	_, err := pcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pcb *ProductCreateBulk) ExecX(ctx context.Context) {
	if err := pcb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Product.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ProductUpsert) {
//			SetCode(v+v).
//		}).
//		Exec(ctx)
func (pcb *ProductCreateBulk) OnConflict(opts ...sql.ConflictOption) *ProductUpsertBulk {
	pcb.conflict = opts
	return &ProductUpsertBulk{
		create: pcb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Product.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (pcb *ProductCreateBulk) OnConflictColumns(columns ...string) *ProductUpsertBulk {
	pcb.conflict = append(pcb.conflict, sql.ConflictColumns(columns...))
	return &ProductUpsertBulk{
		create: pcb,
	}
}

// ProductUpsertBulk is the builder for "upsert"-ing
// a bulk of Product nodes.
type ProductUpsertBulk struct {
	create *ProductCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Product.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(product.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ProductUpsertBulk) UpdateNewValues() *ProductUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(product.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(product.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Product.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ProductUpsertBulk) Ignore() *ProductUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ProductUpsertBulk) DoNothing() *ProductUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ProductCreateBulk.OnConflict
// documentation for more info.
func (u *ProductUpsertBulk) Update(set func(*ProductUpsert)) *ProductUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ProductUpsert{UpdateSet: update})
	}))
	return u
}

// SetCode sets the "code" field.
func (u *ProductUpsertBulk) SetCode(v string) *ProductUpsertBulk {
	return u.Update(func(s *ProductUpsert) {
		s.SetCode(v)
	})
}

// UpdateCode sets the "code" field to the value that was provided on create.
func (u *ProductUpsertBulk) UpdateCode() *ProductUpsertBulk {
	return u.Update(func(s *ProductUpsert) {
		s.UpdateCode()
	})
}

// SetName sets the "name" field.
func (u *ProductUpsertBulk) SetName(v string) *ProductUpsertBulk {
	return u.Update(func(s *ProductUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *ProductUpsertBulk) UpdateName() *ProductUpsertBulk {
	return u.Update(func(s *ProductUpsert) {
		s.UpdateName()
	})
}

// SetDescription sets the "description" field.
func (u *ProductUpsertBulk) SetDescription(v string) *ProductUpsertBulk {
	return u.Update(func(s *ProductUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *ProductUpsertBulk) UpdateDescription() *ProductUpsertBulk {
	return u.Update(func(s *ProductUpsert) {
		s.UpdateDescription()
	})
}

// ClearDescription clears the value of the "description" field.
func (u *ProductUpsertBulk) ClearDescription() *ProductUpsertBulk {
	return u.Update(func(s *ProductUpsert) {
		s.ClearDescription()
	})
}

// SetCategory sets the "category" field.
func (u *ProductUpsertBulk) SetCategory(v product.Category) *ProductUpsertBulk {
	return u.Update(func(s *ProductUpsert) {
		s.SetCategory(v)
	})
}

// UpdateCategory sets the "category" field to the value that was provided on create.
func (u *ProductUpsertBulk) UpdateCategory() *ProductUpsertBulk {
	return u.Update(func(s *ProductUpsert) {
		s.UpdateCategory()
	})
}

// SetStatus sets the "status" field.
func (u *ProductUpsertBulk) SetStatus(v product.Status) *ProductUpsertBulk {
	return u.Update(func(s *ProductUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ProductUpsertBulk) UpdateStatus() *ProductUpsertBulk {
	return u.Update(func(s *ProductUpsert) {
		s.UpdateStatus()
	})
}

// SetDependencies sets the "dependencies" field.
func (u *ProductUpsertBulk) SetDependencies(v []string) *ProductUpsertBulk {
	return u.Update(func(s *ProductUpsert) {
		s.SetDependencies(v)
	})
}

// UpdateDependencies sets the "dependencies" field to the value that was provided on create.
func (u *ProductUpsertBulk) UpdateDependencies() *ProductUpsertBulk {
	return u.Update(func(s *ProductUpsert) {
		s.UpdateDependencies()
	})
}

// ClearDependencies clears the value of the "dependencies" field.
func (u *ProductUpsertBulk) ClearDependencies() *ProductUpsertBulk {
	return u.Update(func(s *ProductUpsert) {
		s.ClearDependencies()
	})
}

// SetIsPlatform sets the "is_platform" field.
func (u *ProductUpsertBulk) SetIsPlatform(v bool) *ProductUpsertBulk {
	return u.Update(func(s *ProductUpsert) {
		s.SetIsPlatform(v)
	})
}

// UpdateIsPlatform sets the "is_platform" field to the value that was provided on create.
func (u *ProductUpsertBulk) UpdateIsPlatform() *ProductUpsertBulk {
	return u.Update(func(s *ProductUpsert) {
		s.UpdateIsPlatform()
	})
}

// SetMonthlyPrice sets the "monthly_price" field.
func (u *ProductUpsertBulk) SetMonthlyPrice(v float64) *ProductUpsertBulk {
	return u.Update(func(s *ProductUpsert) {
		s.SetMonthlyPrice(v)
	})
}

// AddMonthlyPrice adds v to the "monthly_price" field.
func (u *ProductUpsertBulk) AddMonthlyPrice(v float64) *ProductUpsertBulk {
	return u.Update(func(s *ProductUpsert) {
		s.AddMonthlyPrice(v)
	})
}

// UpdateMonthlyPrice sets the "monthly_price" field to the value that was provided on create.
func (u *ProductUpsertBulk) UpdateMonthlyPrice() *ProductUpsertBulk {
	return u.Update(func(s *ProductUpsert) {
		s.UpdateMonthlyPrice()
	})
}

// SetIncludedInBundle sets the "included_in_bundle" field.
func (u *ProductUpsertBulk) SetIncludedInBundle(v bool) *ProductUpsertBulk {
	return u.Update(func(s *ProductUpsert) {
		s.SetIncludedInBundle(v)
	})
}

// UpdateIncludedInBundle sets the "included_in_bundle" field to the value that was provided on create.
func (u *ProductUpsertBulk) UpdateIncludedInBundle() *ProductUpsertBulk {
	return u.Update(func(s *ProductUpsert) {
		s.UpdateIncludedInBundle()
	})
}

// SetSortOrder sets the "sort_order" field.
func (u *ProductUpsertBulk) SetSortOrder(v int) *ProductUpsertBulk {
	return u.Update(func(s *ProductUpsert) {
		s.SetSortOrder(v)
	})
}

// AddSortOrder adds v to the "sort_order" field.
func (u *ProductUpsertBulk) AddSortOrder(v int) *ProductUpsertBulk {
	return u.Update(func(s *ProductUpsert) {
		s.AddSortOrder(v)
	})
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *ProductUpsertBulk) UpdateSortOrder() *ProductUpsertBulk {
	return u.Update(func(s *ProductUpsert) {
		s.UpdateSortOrder()
	})
}

// SetMetadata sets the "metadata" field.
func (u *ProductUpsertBulk) SetMetadata(v map[string]interface{}) *ProductUpsertBulk {
	return u.Update(func(s *ProductUpsert) {
		s.SetMetadata(v)
	})
}

// UpdateMetadata sets the "metadata" field to the value that was provided on create.
func (u *ProductUpsertBulk) UpdateMetadata() *ProductUpsertBulk {
	return u.Update(func(s *ProductUpsert) {
		s.UpdateMetadata()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ProductUpsertBulk) SetUpdatedAt(v time.Time) *ProductUpsertBulk {
	return u.Update(func(s *ProductUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ProductUpsertBulk) UpdateUpdatedAt() *ProductUpsertBulk {
	return u.Update(func(s *ProductUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *ProductUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ProductCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ProductCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ProductUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
