// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/bengobox/subscription-service/internal/ent/bundle"
	"github.com/bengobox/subscription-service/internal/ent/outboxevent"
	"github.com/bengobox/subscription-service/internal/ent/planfeature"
	"github.com/bengobox/subscription-service/internal/ent/planpricinghistory"
	"github.com/bengobox/subscription-service/internal/ent/product"
	"github.com/bengobox/subscription-service/internal/ent/productsubscription"
	"github.com/bengobox/subscription-service/internal/ent/schema"
	"github.com/bengobox/subscription-service/internal/ent/servicechargeplan"
	"github.com/bengobox/subscription-service/internal/ent/subscriptionplan"
	"github.com/bengobox/subscription-service/internal/ent/tenant"
	"github.com/bengobox/subscription-service/internal/ent/tenantsubscription"
	"github.com/bengobox/subscription-service/internal/ent/usageevent"
	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	bundleFields := schema.Bundle{}.Fields()
	_ = bundleFields
	// bundleDescCode is the schema descriptor for code field.
	bundleDescCode := bundleFields[1].Descriptor()
	// bundle.CodeValidator is a validator for the "code" field. It is called by the builders before save.
	bundle.CodeValidator = bundleDescCode.Validators[0].(func(string) error)
	// bundleDescName is the schema descriptor for name field.
	bundleDescName := bundleFields[2].Descriptor()
	// bundle.NameValidator is a validator for the "name" field. It is called by the builders before save.
	bundle.NameValidator = bundleDescName.Validators[0].(func(string) error)
	// bundleDescDiscountValue is the schema descriptor for discount_value field.
	bundleDescDiscountValue := bundleFields[7].Descriptor()
	// bundle.DefaultDiscountValue holds the default value on creation for the discount_value field.
	bundle.DefaultDiscountValue = bundleDescDiscountValue.Default.(float64)
	// bundleDescIsActive is the schema descriptor for is_active field.
	bundleDescIsActive := bundleFields[8].Descriptor()
	// bundle.DefaultIsActive holds the default value on creation for the is_active field.
	bundle.DefaultIsActive = bundleDescIsActive.Default.(bool)
	// bundleDescIsDefault is the schema descriptor for is_default field.
	bundleDescIsDefault := bundleFields[9].Descriptor()
	// bundle.DefaultIsDefault holds the default value on creation for the is_default field.
	bundle.DefaultIsDefault = bundleDescIsDefault.Default.(bool)
	// bundleDescSortOrder is the schema descriptor for sort_order field.
	bundleDescSortOrder := bundleFields[10].Descriptor()
	// bundle.DefaultSortOrder holds the default value on creation for the sort_order field.
	bundle.DefaultSortOrder = bundleDescSortOrder.Default.(int)
	// bundleDescMetadata is the schema descriptor for metadata field.
	bundleDescMetadata := bundleFields[11].Descriptor()
	// bundle.DefaultMetadata holds the default value on creation for the metadata field.
	bundle.DefaultMetadata = bundleDescMetadata.Default.(map[string]interface{})
	// bundleDescCreatedAt is the schema descriptor for created_at field.
	bundleDescCreatedAt := bundleFields[12].Descriptor()
	// bundle.DefaultCreatedAt holds the default value on creation for the created_at field.
	bundle.DefaultCreatedAt = bundleDescCreatedAt.Default.(func() time.Time)
	// bundleDescUpdatedAt is the schema descriptor for updated_at field.
	bundleDescUpdatedAt := bundleFields[13].Descriptor()
	// bundle.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	bundle.DefaultUpdatedAt = bundleDescUpdatedAt.Default.(func() time.Time)
	// bundle.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	bundle.UpdateDefaultUpdatedAt = bundleDescUpdatedAt.UpdateDefault.(func() time.Time)
	// bundleDescID is the schema descriptor for id field.
	bundleDescID := bundleFields[0].Descriptor()
	// bundle.DefaultID holds the default value on creation for the id field.
	bundle.DefaultID = bundleDescID.Default.(func() uuid.UUID)
	outboxeventFields := schema.OutboxEvent{}.Fields()
	_ = outboxeventFields
	// outboxeventDescAggregateType is the schema descriptor for aggregate_type field.
	outboxeventDescAggregateType := outboxeventFields[2].Descriptor()
	// outboxevent.AggregateTypeValidator is a validator for the "aggregate_type" field. It is called by the builders before save.
	outboxevent.AggregateTypeValidator = outboxeventDescAggregateType.Validators[0].(func(string) error)
	// outboxeventDescEventType is the schema descriptor for event_type field.
	outboxeventDescEventType := outboxeventFields[4].Descriptor()
	// outboxevent.EventTypeValidator is a validator for the "event_type" field. It is called by the builders before save.
	outboxevent.EventTypeValidator = outboxeventDescEventType.Validators[0].(func(string) error)
	// outboxeventDescStatus is the schema descriptor for status field.
	outboxeventDescStatus := outboxeventFields[6].Descriptor()
	// outboxevent.DefaultStatus holds the default value on creation for the status field.
	outboxevent.DefaultStatus = outboxeventDescStatus.Default.(string)
	// outboxeventDescAttempts is the schema descriptor for attempts field.
	outboxeventDescAttempts := outboxeventFields[7].Descriptor()
	// outboxevent.DefaultAttempts holds the default value on creation for the attempts field.
	outboxevent.DefaultAttempts = outboxeventDescAttempts.Default.(int)
	// outboxeventDescCreatedAt is the schema descriptor for created_at field.
	outboxeventDescCreatedAt := outboxeventFields[11].Descriptor()
	// outboxevent.DefaultCreatedAt holds the default value on creation for the created_at field.
	outboxevent.DefaultCreatedAt = outboxeventDescCreatedAt.Default.(func() time.Time)
	// outboxeventDescID is the schema descriptor for id field.
	outboxeventDescID := outboxeventFields[0].Descriptor()
	// outboxevent.DefaultID holds the default value on creation for the id field.
	outboxevent.DefaultID = outboxeventDescID.Default.(func() uuid.UUID)
	planfeatureFields := schema.PlanFeature{}.Fields()
	_ = planfeatureFields
	// planfeatureDescFeatureCode is the schema descriptor for feature_code field.
	planfeatureDescFeatureCode := planfeatureFields[2].Descriptor()
	// planfeature.FeatureCodeValidator is a validator for the "feature_code" field. It is called by the builders before save.
	planfeature.FeatureCodeValidator = planfeatureDescFeatureCode.Validators[0].(func(string) error)
	// planfeatureDescIsIncluded is the schema descriptor for is_included field.
	planfeatureDescIsIncluded := planfeatureFields[3].Descriptor()
	// planfeature.DefaultIsIncluded holds the default value on creation for the is_included field.
	planfeature.DefaultIsIncluded = planfeatureDescIsIncluded.Default.(bool)
	// planfeatureDescOverageUnitPrice is the schema descriptor for overage_unit_price field.
	planfeatureDescOverageUnitPrice := planfeatureFields[5].Descriptor()
	// planfeature.DefaultOverageUnitPrice holds the default value on creation for the overage_unit_price field.
	planfeature.DefaultOverageUnitPrice = planfeatureDescOverageUnitPrice.Default.(float64)
	// planfeatureDescMetadata is the schema descriptor for metadata field.
	planfeatureDescMetadata := planfeatureFields[6].Descriptor()
	// planfeature.DefaultMetadata holds the default value on creation for the metadata field.
	planfeature.DefaultMetadata = planfeatureDescMetadata.Default.(map[string]interface{})
	// planfeatureDescCreatedAt is the schema descriptor for created_at field.
	planfeatureDescCreatedAt := planfeatureFields[7].Descriptor()
	// planfeature.DefaultCreatedAt holds the default value on creation for the created_at field.
	planfeature.DefaultCreatedAt = planfeatureDescCreatedAt.Default.(func() time.Time)
	// planfeatureDescID is the schema descriptor for id field.
	planfeatureDescID := planfeatureFields[0].Descriptor()
	// planfeature.DefaultID holds the default value on creation for the id field.
	planfeature.DefaultID = planfeatureDescID.Default.(func() uuid.UUID)
	planpricinghistoryFields := schema.PlanPricingHistory{}.Fields()
	_ = planpricinghistoryFields
	// planpricinghistoryDescMetadata is the schema descriptor for metadata field.
	planpricinghistoryDescMetadata := planpricinghistoryFields[7].Descriptor()
	// planpricinghistory.DefaultMetadata holds the default value on creation for the metadata field.
	planpricinghistory.DefaultMetadata = planpricinghistoryDescMetadata.Default.(map[string]interface{})
	// planpricinghistoryDescCreatedAt is the schema descriptor for created_at field.
	planpricinghistoryDescCreatedAt := planpricinghistoryFields[8].Descriptor()
	// planpricinghistory.DefaultCreatedAt holds the default value on creation for the created_at field.
	planpricinghistory.DefaultCreatedAt = planpricinghistoryDescCreatedAt.Default.(func() time.Time)
	// planpricinghistoryDescID is the schema descriptor for id field.
	planpricinghistoryDescID := planpricinghistoryFields[0].Descriptor()
	// planpricinghistory.DefaultID holds the default value on creation for the id field.
	planpricinghistory.DefaultID = planpricinghistoryDescID.Default.(func() uuid.UUID)
	productFields := schema.Product{}.Fields()
	_ = productFields
	// productDescCode is the schema descriptor for code field.
	productDescCode := productFields[1].Descriptor()
	// product.CodeValidator is a validator for the "code" field. It is called by the builders before save.
	product.CodeValidator = productDescCode.Validators[0].(func(string) error)
	// productDescName is the schema descriptor for name field.
	productDescName := productFields[2].Descriptor()
	// product.NameValidator is a validator for the "name" field. It is called by the builders before save.
	product.NameValidator = productDescName.Validators[0].(func(string) error)
	// productDescIsPlatform is the schema descriptor for is_platform field.
	productDescIsPlatform := productFields[7].Descriptor()
	// product.DefaultIsPlatform holds the default value on creation for the is_platform field.
	product.DefaultIsPlatform = productDescIsPlatform.Default.(bool)
	// productDescMonthlyPrice is the schema descriptor for monthly_price field.
	productDescMonthlyPrice := productFields[8].Descriptor()
	// product.DefaultMonthlyPrice holds the default value on creation for the monthly_price field.
	product.DefaultMonthlyPrice = productDescMonthlyPrice.Default.(float64)
	// productDescYearlyPrice is the schema descriptor for yearly_price field.
	productDescYearlyPrice := productFields[9].Descriptor()
	// product.DefaultYearlyPrice holds the default value on creation for the yearly_price field.
	product.DefaultYearlyPrice = productDescYearlyPrice.Default.(float64)
	// productDescOnetimePrice is the schema descriptor for onetime_price field.
	productDescOnetimePrice := productFields[10].Descriptor()
	// product.DefaultOnetimePrice holds the default value on creation for the onetime_price field.
	product.DefaultOnetimePrice = productDescOnetimePrice.Default.(float64)
	// productDescIncludedInBundle is the schema descriptor for included_in_bundle field.
	productDescIncludedInBundle := productFields[11].Descriptor()
	// product.DefaultIncludedInBundle holds the default value on creation for the included_in_bundle field.
	product.DefaultIncludedInBundle = productDescIncludedInBundle.Default.(bool)
	// productDescSortOrder is the schema descriptor for sort_order field.
	productDescSortOrder := productFields[12].Descriptor()
	// product.DefaultSortOrder holds the default value on creation for the sort_order field.
	product.DefaultSortOrder = productDescSortOrder.Default.(int)
	// productDescIsBaseService is the schema descriptor for is_base_service field.
	productDescIsBaseService := productFields[13].Descriptor()
	// product.DefaultIsBaseService holds the default value on creation for the is_base_service field.
	product.DefaultIsBaseService = productDescIsBaseService.Default.(bool)
	// productDescMetadata is the schema descriptor for metadata field.
	productDescMetadata := productFields[14].Descriptor()
	// product.DefaultMetadata holds the default value on creation for the metadata field.
	product.DefaultMetadata = productDescMetadata.Default.(map[string]interface{})
	// productDescCreatedAt is the schema descriptor for created_at field.
	productDescCreatedAt := productFields[15].Descriptor()
	// product.DefaultCreatedAt holds the default value on creation for the created_at field.
	product.DefaultCreatedAt = productDescCreatedAt.Default.(func() time.Time)
	// productDescUpdatedAt is the schema descriptor for updated_at field.
	productDescUpdatedAt := productFields[16].Descriptor()
	// product.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	product.DefaultUpdatedAt = productDescUpdatedAt.Default.(func() time.Time)
	// product.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	product.UpdateDefaultUpdatedAt = productDescUpdatedAt.UpdateDefault.(func() time.Time)
	// productDescID is the schema descriptor for id field.
	productDescID := productFields[0].Descriptor()
	// product.DefaultID holds the default value on creation for the id field.
	product.DefaultID = productDescID.Default.(func() uuid.UUID)
	productsubscriptionFields := schema.ProductSubscription{}.Fields()
	_ = productsubscriptionFields
	// productsubscriptionDescProductCode is the schema descriptor for product_code field.
	productsubscriptionDescProductCode := productsubscriptionFields[2].Descriptor()
	// productsubscription.ProductCodeValidator is a validator for the "product_code" field. It is called by the builders before save.
	productsubscription.ProductCodeValidator = productsubscriptionDescProductCode.Validators[0].(func(string) error)
	// productsubscriptionDescMetadata is the schema descriptor for metadata field.
	productsubscriptionDescMetadata := productsubscriptionFields[10].Descriptor()
	// productsubscription.DefaultMetadata holds the default value on creation for the metadata field.
	productsubscription.DefaultMetadata = productsubscriptionDescMetadata.Default.(map[string]interface{})
	// productsubscriptionDescCreatedAt is the schema descriptor for created_at field.
	productsubscriptionDescCreatedAt := productsubscriptionFields[11].Descriptor()
	// productsubscription.DefaultCreatedAt holds the default value on creation for the created_at field.
	productsubscription.DefaultCreatedAt = productsubscriptionDescCreatedAt.Default.(func() time.Time)
	// productsubscriptionDescUpdatedAt is the schema descriptor for updated_at field.
	productsubscriptionDescUpdatedAt := productsubscriptionFields[12].Descriptor()
	// productsubscription.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	productsubscription.DefaultUpdatedAt = productsubscriptionDescUpdatedAt.Default.(func() time.Time)
	// productsubscription.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	productsubscription.UpdateDefaultUpdatedAt = productsubscriptionDescUpdatedAt.UpdateDefault.(func() time.Time)
	// productsubscriptionDescID is the schema descriptor for id field.
	productsubscriptionDescID := productsubscriptionFields[0].Descriptor()
	// productsubscription.DefaultID holds the default value on creation for the id field.
	productsubscription.DefaultID = productsubscriptionDescID.Default.(func() uuid.UUID)
	servicechargeplanFields := schema.ServiceChargePlan{}.Fields()
	_ = servicechargeplanFields
	// servicechargeplanDescCode is the schema descriptor for code field.
	servicechargeplanDescCode := servicechargeplanFields[1].Descriptor()
	// servicechargeplan.CodeValidator is a validator for the "code" field. It is called by the builders before save.
	servicechargeplan.CodeValidator = servicechargeplanDescCode.Validators[0].(func(string) error)
	// servicechargeplanDescName is the schema descriptor for name field.
	servicechargeplanDescName := servicechargeplanFields[2].Descriptor()
	// servicechargeplan.NameValidator is a validator for the "name" field. It is called by the builders before save.
	servicechargeplan.NameValidator = servicechargeplanDescName.Validators[0].(func(string) error)
	// servicechargeplanDescChargeValue is the schema descriptor for charge_value field.
	servicechargeplanDescChargeValue := servicechargeplanFields[5].Descriptor()
	// servicechargeplan.DefaultChargeValue holds the default value on creation for the charge_value field.
	servicechargeplan.DefaultChargeValue = servicechargeplanDescChargeValue.Default.(float64)
	// servicechargeplanDescCurrency is the schema descriptor for currency field.
	servicechargeplanDescCurrency := servicechargeplanFields[6].Descriptor()
	// servicechargeplan.DefaultCurrency holds the default value on creation for the currency field.
	servicechargeplan.DefaultCurrency = servicechargeplanDescCurrency.Default.(string)
	// servicechargeplanDescIsActive is the schema descriptor for is_active field.
	servicechargeplanDescIsActive := servicechargeplanFields[11].Descriptor()
	// servicechargeplan.DefaultIsActive holds the default value on creation for the is_active field.
	servicechargeplan.DefaultIsActive = servicechargeplanDescIsActive.Default.(bool)
	// servicechargeplanDescIsDefault is the schema descriptor for is_default field.
	servicechargeplanDescIsDefault := servicechargeplanFields[12].Descriptor()
	// servicechargeplan.DefaultIsDefault holds the default value on creation for the is_default field.
	servicechargeplan.DefaultIsDefault = servicechargeplanDescIsDefault.Default.(bool)
	// servicechargeplanDescMetadata is the schema descriptor for metadata field.
	servicechargeplanDescMetadata := servicechargeplanFields[13].Descriptor()
	// servicechargeplan.DefaultMetadata holds the default value on creation for the metadata field.
	servicechargeplan.DefaultMetadata = servicechargeplanDescMetadata.Default.(map[string]interface{})
	// servicechargeplanDescCreatedAt is the schema descriptor for created_at field.
	servicechargeplanDescCreatedAt := servicechargeplanFields[14].Descriptor()
	// servicechargeplan.DefaultCreatedAt holds the default value on creation for the created_at field.
	servicechargeplan.DefaultCreatedAt = servicechargeplanDescCreatedAt.Default.(func() time.Time)
	// servicechargeplanDescUpdatedAt is the schema descriptor for updated_at field.
	servicechargeplanDescUpdatedAt := servicechargeplanFields[15].Descriptor()
	// servicechargeplan.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	servicechargeplan.DefaultUpdatedAt = servicechargeplanDescUpdatedAt.Default.(func() time.Time)
	// servicechargeplan.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	servicechargeplan.UpdateDefaultUpdatedAt = servicechargeplanDescUpdatedAt.UpdateDefault.(func() time.Time)
	// servicechargeplanDescID is the schema descriptor for id field.
	servicechargeplanDescID := servicechargeplanFields[0].Descriptor()
	// servicechargeplan.DefaultID holds the default value on creation for the id field.
	servicechargeplan.DefaultID = servicechargeplanDescID.Default.(func() uuid.UUID)
	subscriptionplanFields := schema.SubscriptionPlan{}.Fields()
	_ = subscriptionplanFields
	// subscriptionplanDescPlanCode is the schema descriptor for plan_code field.
	subscriptionplanDescPlanCode := subscriptionplanFields[1].Descriptor()
	// subscriptionplan.PlanCodeValidator is a validator for the "plan_code" field. It is called by the builders before save.
	subscriptionplan.PlanCodeValidator = subscriptionplanDescPlanCode.Validators[0].(func(string) error)
	// subscriptionplanDescName is the schema descriptor for name field.
	subscriptionplanDescName := subscriptionplanFields[2].Descriptor()
	// subscriptionplan.NameValidator is a validator for the "name" field. It is called by the builders before save.
	subscriptionplan.NameValidator = subscriptionplanDescName.Validators[0].(func(string) error)
	// subscriptionplanDescBillingCycle is the schema descriptor for billing_cycle field.
	subscriptionplanDescBillingCycle := subscriptionplanFields[4].Descriptor()
	// subscriptionplan.DefaultBillingCycle holds the default value on creation for the billing_cycle field.
	subscriptionplan.DefaultBillingCycle = subscriptionplanDescBillingCycle.Default.(string)
	// subscriptionplan.BillingCycleValidator is a validator for the "billing_cycle" field. It is called by the builders before save.
	subscriptionplan.BillingCycleValidator = subscriptionplanDescBillingCycle.Validators[0].(func(string) error)
	// subscriptionplanDescUseSumBasedPricing is the schema descriptor for use_sum_based_pricing field.
	subscriptionplanDescUseSumBasedPricing := subscriptionplanFields[7].Descriptor()
	// subscriptionplan.DefaultUseSumBasedPricing holds the default value on creation for the use_sum_based_pricing field.
	subscriptionplan.DefaultUseSumBasedPricing = subscriptionplanDescUseSumBasedPricing.Default.(bool)
	// subscriptionplanDescCurrency is the schema descriptor for currency field.
	subscriptionplanDescCurrency := subscriptionplanFields[8].Descriptor()
	// subscriptionplan.DefaultCurrency holds the default value on creation for the currency field.
	subscriptionplan.DefaultCurrency = subscriptionplanDescCurrency.Default.(string)
	// subscriptionplanDescIsActive is the schema descriptor for is_active field.
	subscriptionplanDescIsActive := subscriptionplanFields[9].Descriptor()
	// subscriptionplan.DefaultIsActive holds the default value on creation for the is_active field.
	subscriptionplan.DefaultIsActive = subscriptionplanDescIsActive.Default.(bool)
	// subscriptionplanDescIsPublic is the schema descriptor for is_public field.
	subscriptionplanDescIsPublic := subscriptionplanFields[10].Descriptor()
	// subscriptionplan.DefaultIsPublic holds the default value on creation for the is_public field.
	subscriptionplan.DefaultIsPublic = subscriptionplanDescIsPublic.Default.(bool)
	// subscriptionplanDescTierLimitsJSON is the schema descriptor for tier_limits_json field.
	subscriptionplanDescTierLimitsJSON := subscriptionplanFields[12].Descriptor()
	// subscriptionplan.DefaultTierLimitsJSON holds the default value on creation for the tier_limits_json field.
	subscriptionplan.DefaultTierLimitsJSON = subscriptionplanDescTierLimitsJSON.Default.(map[string]interface{})
	// subscriptionplanDescDiscountRules is the schema descriptor for discount_rules field.
	subscriptionplanDescDiscountRules := subscriptionplanFields[14].Descriptor()
	// subscriptionplan.DefaultDiscountRules holds the default value on creation for the discount_rules field.
	subscriptionplan.DefaultDiscountRules = subscriptionplanDescDiscountRules.Default.([]map[string]interface{})
	// subscriptionplanDescMetadata is the schema descriptor for metadata field.
	subscriptionplanDescMetadata := subscriptionplanFields[15].Descriptor()
	// subscriptionplan.DefaultMetadata holds the default value on creation for the metadata field.
	subscriptionplan.DefaultMetadata = subscriptionplanDescMetadata.Default.(map[string]interface{})
	// subscriptionplanDescCreatedAt is the schema descriptor for created_at field.
	subscriptionplanDescCreatedAt := subscriptionplanFields[16].Descriptor()
	// subscriptionplan.DefaultCreatedAt holds the default value on creation for the created_at field.
	subscriptionplan.DefaultCreatedAt = subscriptionplanDescCreatedAt.Default.(func() time.Time)
	// subscriptionplanDescUpdatedAt is the schema descriptor for updated_at field.
	subscriptionplanDescUpdatedAt := subscriptionplanFields[17].Descriptor()
	// subscriptionplan.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	subscriptionplan.DefaultUpdatedAt = subscriptionplanDescUpdatedAt.Default.(func() time.Time)
	// subscriptionplan.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	subscriptionplan.UpdateDefaultUpdatedAt = subscriptionplanDescUpdatedAt.UpdateDefault.(func() time.Time)
	// subscriptionplanDescID is the schema descriptor for id field.
	subscriptionplanDescID := subscriptionplanFields[0].Descriptor()
	// subscriptionplan.DefaultID holds the default value on creation for the id field.
	subscriptionplan.DefaultID = subscriptionplanDescID.Default.(func() uuid.UUID)
	tenantFields := schema.Tenant{}.Fields()
	_ = tenantFields
	// tenantDescName is the schema descriptor for name field.
	tenantDescName := tenantFields[1].Descriptor()
	// tenant.NameValidator is a validator for the "name" field. It is called by the builders before save.
	tenant.NameValidator = tenantDescName.Validators[0].(func(string) error)
	// tenantDescSlug is the schema descriptor for slug field.
	tenantDescSlug := tenantFields[2].Descriptor()
	// tenant.SlugValidator is a validator for the "slug" field. It is called by the builders before save.
	tenant.SlugValidator = tenantDescSlug.Validators[0].(func(string) error)
	// tenantDescStatus is the schema descriptor for status field.
	tenantDescStatus := tenantFields[3].Descriptor()
	// tenant.DefaultStatus holds the default value on creation for the status field.
	tenant.DefaultStatus = tenantDescStatus.Default.(string)
	// tenantDescCountry is the schema descriptor for country field.
	tenantDescCountry := tenantFields[8].Descriptor()
	// tenant.DefaultCountry holds the default value on creation for the country field.
	tenant.DefaultCountry = tenantDescCountry.Default.(string)
	// tenantDescTimezone is the schema descriptor for timezone field.
	tenantDescTimezone := tenantFields[9].Descriptor()
	// tenant.DefaultTimezone holds the default value on creation for the timezone field.
	tenant.DefaultTimezone = tenantDescTimezone.Default.(string)
	// tenantDescMetadata is the schema descriptor for metadata field.
	tenantDescMetadata := tenantFields[18].Descriptor()
	// tenant.DefaultMetadata holds the default value on creation for the metadata field.
	tenant.DefaultMetadata = tenantDescMetadata.Default.(map[string]interface{})
	// tenantDescCreatedAt is the schema descriptor for created_at field.
	tenantDescCreatedAt := tenantFields[19].Descriptor()
	// tenant.DefaultCreatedAt holds the default value on creation for the created_at field.
	tenant.DefaultCreatedAt = tenantDescCreatedAt.Default.(func() time.Time)
	// tenantDescUpdatedAt is the schema descriptor for updated_at field.
	tenantDescUpdatedAt := tenantFields[20].Descriptor()
	// tenant.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	tenant.DefaultUpdatedAt = tenantDescUpdatedAt.Default.(func() time.Time)
	// tenant.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	tenant.UpdateDefaultUpdatedAt = tenantDescUpdatedAt.UpdateDefault.(func() time.Time)
	// tenantDescID is the schema descriptor for id field.
	tenantDescID := tenantFields[0].Descriptor()
	// tenant.DefaultID holds the default value on creation for the id field.
	tenant.DefaultID = tenantDescID.Default.(func() uuid.UUID)
	tenantsubscriptionFields := schema.TenantSubscription{}.Fields()
	_ = tenantsubscriptionFields
	// tenantsubscriptionDescAppliedDiscount is the schema descriptor for applied_discount field.
	tenantsubscriptionDescAppliedDiscount := tenantsubscriptionFields[10].Descriptor()
	// tenantsubscription.DefaultAppliedDiscount holds the default value on creation for the applied_discount field.
	tenantsubscription.DefaultAppliedDiscount = tenantsubscriptionDescAppliedDiscount.Default.(float64)
	// tenantsubscriptionDescMetadata is the schema descriptor for metadata field.
	tenantsubscriptionDescMetadata := tenantsubscriptionFields[13].Descriptor()
	// tenantsubscription.DefaultMetadata holds the default value on creation for the metadata field.
	tenantsubscription.DefaultMetadata = tenantsubscriptionDescMetadata.Default.(map[string]interface{})
	// tenantsubscriptionDescCreatedAt is the schema descriptor for created_at field.
	tenantsubscriptionDescCreatedAt := tenantsubscriptionFields[14].Descriptor()
	// tenantsubscription.DefaultCreatedAt holds the default value on creation for the created_at field.
	tenantsubscription.DefaultCreatedAt = tenantsubscriptionDescCreatedAt.Default.(func() time.Time)
	// tenantsubscriptionDescUpdatedAt is the schema descriptor for updated_at field.
	tenantsubscriptionDescUpdatedAt := tenantsubscriptionFields[15].Descriptor()
	// tenantsubscription.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	tenantsubscription.DefaultUpdatedAt = tenantsubscriptionDescUpdatedAt.Default.(func() time.Time)
	// tenantsubscription.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	tenantsubscription.UpdateDefaultUpdatedAt = tenantsubscriptionDescUpdatedAt.UpdateDefault.(func() time.Time)
	// tenantsubscriptionDescID is the schema descriptor for id field.
	tenantsubscriptionDescID := tenantsubscriptionFields[0].Descriptor()
	// tenantsubscription.DefaultID holds the default value on creation for the id field.
	tenantsubscription.DefaultID = tenantsubscriptionDescID.Default.(func() uuid.UUID)
	usageeventFields := schema.UsageEvent{}.Fields()
	_ = usageeventFields
	// usageeventDescMetricType is the schema descriptor for metric_type field.
	usageeventDescMetricType := usageeventFields[2].Descriptor()
	// usageevent.MetricTypeValidator is a validator for the "metric_type" field. It is called by the builders before save.
	usageevent.MetricTypeValidator = func() func(string) error {
		validators := usageeventDescMetricType.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(metric_type string) error {
			for _, fn := range fns {
				if err := fn(metric_type); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// usageeventDescServiceName is the schema descriptor for service_name field.
	usageeventDescServiceName := usageeventFields[3].Descriptor()
	// usageevent.ServiceNameValidator is a validator for the "service_name" field. It is called by the builders before save.
	usageevent.ServiceNameValidator = func() func(string) error {
		validators := usageeventDescServiceName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(service_name string) error {
			for _, fn := range fns {
				if err := fn(service_name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// usageeventDescMetadata is the schema descriptor for metadata field.
	usageeventDescMetadata := usageeventFields[7].Descriptor()
	// usageevent.DefaultMetadata holds the default value on creation for the metadata field.
	usageevent.DefaultMetadata = usageeventDescMetadata.Default.(map[string]interface{})
	// usageeventDescCreatedAt is the schema descriptor for created_at field.
	usageeventDescCreatedAt := usageeventFields[8].Descriptor()
	// usageevent.DefaultCreatedAt holds the default value on creation for the created_at field.
	usageevent.DefaultCreatedAt = usageeventDescCreatedAt.Default.(func() time.Time)
	// usageeventDescID is the schema descriptor for id field.
	usageeventDescID := usageeventFields[0].Descriptor()
	// usageevent.DefaultID holds the default value on creation for the id field.
	usageevent.DefaultID = usageeventDescID.Default.(func() uuid.UUID)
}
