// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/bengobox/subscription-service/internal/ent/predicate"
	"github.com/bengobox/subscription-service/internal/ent/subscriptioncredit"
	"github.com/bengobox/subscription-service/internal/ent/subscriptioncredittransaction"
	"github.com/google/uuid"
)

// SubscriptionCreditUpdate is the builder for updating SubscriptionCredit entities.
type SubscriptionCreditUpdate struct {
	config
	hooks    []Hook
	mutation *SubscriptionCreditMutation
}

// Where appends a list predicates to the SubscriptionCreditUpdate builder.
func (_u *SubscriptionCreditUpdate) Where(ps ...predicate.SubscriptionCredit) *SubscriptionCreditUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTenantID sets the "tenant_id" field.
func (_u *SubscriptionCreditUpdate) SetTenantID(v uuid.UUID) *SubscriptionCreditUpdate {
	_u.mutation.SetTenantID(v)
	return _u
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_u *SubscriptionCreditUpdate) SetNillableTenantID(v *uuid.UUID) *SubscriptionCreditUpdate {
	if v != nil {
		_u.SetTenantID(*v)
	}
	return _u
}

// SetBalanceKes sets the "balance_kes" field.
func (_u *SubscriptionCreditUpdate) SetBalanceKes(v int) *SubscriptionCreditUpdate {
	_u.mutation.ResetBalanceKes()
	_u.mutation.SetBalanceKes(v)
	return _u
}

// SetNillableBalanceKes sets the "balance_kes" field if the given value is not nil.
func (_u *SubscriptionCreditUpdate) SetNillableBalanceKes(v *int) *SubscriptionCreditUpdate {
	if v != nil {
		_u.SetBalanceKes(*v)
	}
	return _u
}

// AddBalanceKes adds value to the "balance_kes" field.
func (_u *SubscriptionCreditUpdate) AddBalanceKes(v int) *SubscriptionCreditUpdate {
	_u.mutation.AddBalanceKes(v)
	return _u
}

// SetLifetimeEarnedKes sets the "lifetime_earned_kes" field.
func (_u *SubscriptionCreditUpdate) SetLifetimeEarnedKes(v int) *SubscriptionCreditUpdate {
	_u.mutation.ResetLifetimeEarnedKes()
	_u.mutation.SetLifetimeEarnedKes(v)
	return _u
}

// SetNillableLifetimeEarnedKes sets the "lifetime_earned_kes" field if the given value is not nil.
func (_u *SubscriptionCreditUpdate) SetNillableLifetimeEarnedKes(v *int) *SubscriptionCreditUpdate {
	if v != nil {
		_u.SetLifetimeEarnedKes(*v)
	}
	return _u
}

// AddLifetimeEarnedKes adds value to the "lifetime_earned_kes" field.
func (_u *SubscriptionCreditUpdate) AddLifetimeEarnedKes(v int) *SubscriptionCreditUpdate {
	_u.mutation.AddLifetimeEarnedKes(v)
	return _u
}

// SetLoyaltyRate sets the "loyalty_rate" field.
func (_u *SubscriptionCreditUpdate) SetLoyaltyRate(v float64) *SubscriptionCreditUpdate {
	_u.mutation.ResetLoyaltyRate()
	_u.mutation.SetLoyaltyRate(v)
	return _u
}

// SetNillableLoyaltyRate sets the "loyalty_rate" field if the given value is not nil.
func (_u *SubscriptionCreditUpdate) SetNillableLoyaltyRate(v *float64) *SubscriptionCreditUpdate {
	if v != nil {
		_u.SetLoyaltyRate(*v)
	}
	return _u
}

// AddLoyaltyRate adds value to the "loyalty_rate" field.
func (_u *SubscriptionCreditUpdate) AddLoyaltyRate(v float64) *SubscriptionCreditUpdate {
	_u.mutation.AddLoyaltyRate(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SubscriptionCreditUpdate) SetUpdatedAt(v time.Time) *SubscriptionCreditUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddTransactionIDs adds the "transactions" edge to the SubscriptionCreditTransaction entity by IDs.
func (_u *SubscriptionCreditUpdate) AddTransactionIDs(ids ...uuid.UUID) *SubscriptionCreditUpdate {
	_u.mutation.AddTransactionIDs(ids...)
	return _u
}

// AddTransactions adds the "transactions" edges to the SubscriptionCreditTransaction entity.
func (_u *SubscriptionCreditUpdate) AddTransactions(v ...*SubscriptionCreditTransaction) *SubscriptionCreditUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddTransactionIDs(ids...)
}

// Mutation returns the SubscriptionCreditMutation object of the builder.
func (_u *SubscriptionCreditUpdate) Mutation() *SubscriptionCreditMutation {
	return _u.mutation
}

// ClearTransactions clears all "transactions" edges to the SubscriptionCreditTransaction entity.
func (_u *SubscriptionCreditUpdate) ClearTransactions() *SubscriptionCreditUpdate {
	_u.mutation.ClearTransactions()
	return _u
}

// RemoveTransactionIDs removes the "transactions" edge to SubscriptionCreditTransaction entities by IDs.
func (_u *SubscriptionCreditUpdate) RemoveTransactionIDs(ids ...uuid.UUID) *SubscriptionCreditUpdate {
	_u.mutation.RemoveTransactionIDs(ids...)
	return _u
}

// RemoveTransactions removes "transactions" edges to SubscriptionCreditTransaction entities.
func (_u *SubscriptionCreditUpdate) RemoveTransactions(v ...*SubscriptionCreditTransaction) *SubscriptionCreditUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveTransactionIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SubscriptionCreditUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SubscriptionCreditUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SubscriptionCreditUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SubscriptionCreditUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SubscriptionCreditUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := subscriptioncredit.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *SubscriptionCreditUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(subscriptioncredit.Table, subscriptioncredit.Columns, sqlgraph.NewFieldSpec(subscriptioncredit.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TenantID(); ok {
		_spec.SetField(subscriptioncredit.FieldTenantID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.BalanceKes(); ok {
		_spec.SetField(subscriptioncredit.FieldBalanceKes, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedBalanceKes(); ok {
		_spec.AddField(subscriptioncredit.FieldBalanceKes, field.TypeInt, value)
	}
	if value, ok := _u.mutation.LifetimeEarnedKes(); ok {
		_spec.SetField(subscriptioncredit.FieldLifetimeEarnedKes, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedLifetimeEarnedKes(); ok {
		_spec.AddField(subscriptioncredit.FieldLifetimeEarnedKes, field.TypeInt, value)
	}
	if value, ok := _u.mutation.LoyaltyRate(); ok {
		_spec.SetField(subscriptioncredit.FieldLoyaltyRate, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedLoyaltyRate(); ok {
		_spec.AddField(subscriptioncredit.FieldLoyaltyRate, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(subscriptioncredit.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.TransactionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   subscriptioncredit.TransactionsTable,
			Columns: []string{subscriptioncredit.TransactionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscriptioncredittransaction.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTransactionsIDs(); len(nodes) > 0 && !_u.mutation.TransactionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   subscriptioncredit.TransactionsTable,
			Columns: []string{subscriptioncredit.TransactionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscriptioncredittransaction.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TransactionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   subscriptioncredit.TransactionsTable,
			Columns: []string{subscriptioncredit.TransactionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscriptioncredittransaction.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{subscriptioncredit.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SubscriptionCreditUpdateOne is the builder for updating a single SubscriptionCredit entity.
type SubscriptionCreditUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SubscriptionCreditMutation
}

// SetTenantID sets the "tenant_id" field.
func (_u *SubscriptionCreditUpdateOne) SetTenantID(v uuid.UUID) *SubscriptionCreditUpdateOne {
	_u.mutation.SetTenantID(v)
	return _u
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_u *SubscriptionCreditUpdateOne) SetNillableTenantID(v *uuid.UUID) *SubscriptionCreditUpdateOne {
	if v != nil {
		_u.SetTenantID(*v)
	}
	return _u
}

// SetBalanceKes sets the "balance_kes" field.
func (_u *SubscriptionCreditUpdateOne) SetBalanceKes(v int) *SubscriptionCreditUpdateOne {
	_u.mutation.ResetBalanceKes()
	_u.mutation.SetBalanceKes(v)
	return _u
}

// SetNillableBalanceKes sets the "balance_kes" field if the given value is not nil.
func (_u *SubscriptionCreditUpdateOne) SetNillableBalanceKes(v *int) *SubscriptionCreditUpdateOne {
	if v != nil {
		_u.SetBalanceKes(*v)
	}
	return _u
}

// AddBalanceKes adds value to the "balance_kes" field.
func (_u *SubscriptionCreditUpdateOne) AddBalanceKes(v int) *SubscriptionCreditUpdateOne {
	_u.mutation.AddBalanceKes(v)
	return _u
}

// SetLifetimeEarnedKes sets the "lifetime_earned_kes" field.
func (_u *SubscriptionCreditUpdateOne) SetLifetimeEarnedKes(v int) *SubscriptionCreditUpdateOne {
	_u.mutation.ResetLifetimeEarnedKes()
	_u.mutation.SetLifetimeEarnedKes(v)
	return _u
}

// SetNillableLifetimeEarnedKes sets the "lifetime_earned_kes" field if the given value is not nil.
func (_u *SubscriptionCreditUpdateOne) SetNillableLifetimeEarnedKes(v *int) *SubscriptionCreditUpdateOne {
	if v != nil {
		_u.SetLifetimeEarnedKes(*v)
	}
	return _u
}

// AddLifetimeEarnedKes adds value to the "lifetime_earned_kes" field.
func (_u *SubscriptionCreditUpdateOne) AddLifetimeEarnedKes(v int) *SubscriptionCreditUpdateOne {
	_u.mutation.AddLifetimeEarnedKes(v)
	return _u
}

// SetLoyaltyRate sets the "loyalty_rate" field.
func (_u *SubscriptionCreditUpdateOne) SetLoyaltyRate(v float64) *SubscriptionCreditUpdateOne {
	_u.mutation.ResetLoyaltyRate()
	_u.mutation.SetLoyaltyRate(v)
	return _u
}

// SetNillableLoyaltyRate sets the "loyalty_rate" field if the given value is not nil.
func (_u *SubscriptionCreditUpdateOne) SetNillableLoyaltyRate(v *float64) *SubscriptionCreditUpdateOne {
	if v != nil {
		_u.SetLoyaltyRate(*v)
	}
	return _u
}

// AddLoyaltyRate adds value to the "loyalty_rate" field.
func (_u *SubscriptionCreditUpdateOne) AddLoyaltyRate(v float64) *SubscriptionCreditUpdateOne {
	_u.mutation.AddLoyaltyRate(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SubscriptionCreditUpdateOne) SetUpdatedAt(v time.Time) *SubscriptionCreditUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddTransactionIDs adds the "transactions" edge to the SubscriptionCreditTransaction entity by IDs.
func (_u *SubscriptionCreditUpdateOne) AddTransactionIDs(ids ...uuid.UUID) *SubscriptionCreditUpdateOne {
	_u.mutation.AddTransactionIDs(ids...)
	return _u
}

// AddTransactions adds the "transactions" edges to the SubscriptionCreditTransaction entity.
func (_u *SubscriptionCreditUpdateOne) AddTransactions(v ...*SubscriptionCreditTransaction) *SubscriptionCreditUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddTransactionIDs(ids...)
}

// Mutation returns the SubscriptionCreditMutation object of the builder.
func (_u *SubscriptionCreditUpdateOne) Mutation() *SubscriptionCreditMutation {
	return _u.mutation
}

// ClearTransactions clears all "transactions" edges to the SubscriptionCreditTransaction entity.
func (_u *SubscriptionCreditUpdateOne) ClearTransactions() *SubscriptionCreditUpdateOne {
	_u.mutation.ClearTransactions()
	return _u
}

// RemoveTransactionIDs removes the "transactions" edge to SubscriptionCreditTransaction entities by IDs.
func (_u *SubscriptionCreditUpdateOne) RemoveTransactionIDs(ids ...uuid.UUID) *SubscriptionCreditUpdateOne {
	_u.mutation.RemoveTransactionIDs(ids...)
	return _u
}

// RemoveTransactions removes "transactions" edges to SubscriptionCreditTransaction entities.
func (_u *SubscriptionCreditUpdateOne) RemoveTransactions(v ...*SubscriptionCreditTransaction) *SubscriptionCreditUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveTransactionIDs(ids...)
}

// Where appends a list predicates to the SubscriptionCreditUpdate builder.
func (_u *SubscriptionCreditUpdateOne) Where(ps ...predicate.SubscriptionCredit) *SubscriptionCreditUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SubscriptionCreditUpdateOne) Select(field string, fields ...string) *SubscriptionCreditUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated SubscriptionCredit entity.
func (_u *SubscriptionCreditUpdateOne) Save(ctx context.Context) (*SubscriptionCredit, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SubscriptionCreditUpdateOne) SaveX(ctx context.Context) *SubscriptionCredit {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SubscriptionCreditUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SubscriptionCreditUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SubscriptionCreditUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := subscriptioncredit.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *SubscriptionCreditUpdateOne) sqlSave(ctx context.Context) (_node *SubscriptionCredit, err error) {
	_spec := sqlgraph.NewUpdateSpec(subscriptioncredit.Table, subscriptioncredit.Columns, sqlgraph.NewFieldSpec(subscriptioncredit.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SubscriptionCredit.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, subscriptioncredit.FieldID)
		for _, f := range fields {
			if !subscriptioncredit.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != subscriptioncredit.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TenantID(); ok {
		_spec.SetField(subscriptioncredit.FieldTenantID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.BalanceKes(); ok {
		_spec.SetField(subscriptioncredit.FieldBalanceKes, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedBalanceKes(); ok {
		_spec.AddField(subscriptioncredit.FieldBalanceKes, field.TypeInt, value)
	}
	if value, ok := _u.mutation.LifetimeEarnedKes(); ok {
		_spec.SetField(subscriptioncredit.FieldLifetimeEarnedKes, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedLifetimeEarnedKes(); ok {
		_spec.AddField(subscriptioncredit.FieldLifetimeEarnedKes, field.TypeInt, value)
	}
	if value, ok := _u.mutation.LoyaltyRate(); ok {
		_spec.SetField(subscriptioncredit.FieldLoyaltyRate, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedLoyaltyRate(); ok {
		_spec.AddField(subscriptioncredit.FieldLoyaltyRate, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(subscriptioncredit.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.TransactionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   subscriptioncredit.TransactionsTable,
			Columns: []string{subscriptioncredit.TransactionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscriptioncredittransaction.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTransactionsIDs(); len(nodes) > 0 && !_u.mutation.TransactionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   subscriptioncredit.TransactionsTable,
			Columns: []string{subscriptioncredit.TransactionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscriptioncredittransaction.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TransactionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   subscriptioncredit.TransactionsTable,
			Columns: []string{subscriptioncredit.TransactionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscriptioncredittransaction.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &SubscriptionCredit{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{subscriptioncredit.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
