// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/bengobox/subscription-service/internal/ent/subscriptionplan"
	"github.com/bengobox/subscription-service/internal/ent/supportagreement"
	"github.com/bengobox/subscription-service/internal/ent/supportfeecycle"
	"github.com/bengobox/subscription-service/internal/ent/tenantsubscription"
	"github.com/google/uuid"
)

// SupportFeeCycle is the model entity for the SupportFeeCycle schema.
type SupportFeeCycle struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// Denormalised for fast tenant-scoped queries (mirrors OverageCharge's pattern)
	TenantID uuid.UUID `json:"tenant_id,omitempty"`
	// FK to the tenant's ONE TenantSubscription row — the perpetual license this support fee accompanies
	TenantSubscriptionID uuid.UUID `json:"tenant_subscription_id,omitempty"`
	// SUPPORT_* catalog row for STANDARD agreement cycles; nil for SPECIAL agreements
	SupportPlanID *uuid.UUID `json:"support_plan_id,omitempty"`
	// The SupportAgreement this cycle bills. Rows created before agreements existed are linked by the enrollment job
	AgreementID *uuid.UUID `json:"agreement_id,omitempty"`
	// The agreement's starts_at when this cycle was generated (for STANDARD agreements, the license onboarding date)
	AnchorDate time.Time `json:"anchor_date,omitempty"`
	// 1-based sequence within the agreement
	CycleNumber int `json:"cycle_number,omitempty"`
	// Start of the billed period
	PeriodStart time.Time `json:"period_start,omitempty"`
	// End (exclusive) of the billed period
	PeriodEnd *time.Time `json:"period_end,omitempty"`
	// Payment due date: period_start for ADVANCE agreements, period_end for ARREARS
	DueDate time.Time `json:"due_date,omitempty"`
	// PENDING: not yet invoiced. INVOICED: invoice issued, not yet due. PAID: settled. OVERDUE: due_date passed unpaid; mutations are blocked fleet-wide by RequireSupportFeeCurrentForMutations once grace_until also passes, until paid or waived. WAIVED: excused by the platform owner (or cancelled with its agreement).
	Status supportfeecycle.Status `json:"status,omitempty"`
	// PaidAt holds the value of the "paid_at" field.
	PaidAt *time.Time `json:"paid_at,omitempty"`
	// due_date + 7 days, set the moment the cycle flips OVERDUE. Mutations stay allowed until this passes; reads are never blocked.
	GraceUntil *time.Time `json:"grace_until,omitempty"`
	// Charge for this period, snapshotted from the agreement when the cycle is generated so a later re-price never changes an issued cycle
	BasePrice float64 `json:"base_price,omitempty"`
	// Platform-admin sales-agreed override for THIS tenant's support fee. Nil = use base_price
	CustomPrice *float64 `json:"custom_price,omitempty"`
	// CustomPriceReason holds the value of the "custom_price_reason" field.
	CustomPriceReason *string `json:"custom_price_reason,omitempty"`
	// CustomPriceSetBy holds the value of the "custom_price_set_by" field.
	CustomPriceSetBy *uuid.UUID `json:"custom_price_set_by,omitempty"`
	// CustomPriceSetAt holds the value of the "custom_price_set_at" field.
	CustomPriceSetAt *time.Time `json:"custom_price_set_at,omitempty"`
	// last_invoice_id/number/pay_url/total, last_grace_reminder_date, waive/manual-payment audit
	Metadata map[string]interface{} `json:"metadata,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the SupportFeeCycleQuery when eager-loading is set.
	Edges        SupportFeeCycleEdges `json:"edges"`
	selectValues sql.SelectValues
}

// SupportFeeCycleEdges holds the relations/edges for other nodes in the graph.
type SupportFeeCycleEdges struct {
	// TenantSubscription holds the value of the tenant_subscription edge.
	TenantSubscription *TenantSubscription `json:"tenant_subscription,omitempty"`
	// SupportPlan holds the value of the support_plan edge.
	SupportPlan *SubscriptionPlan `json:"support_plan,omitempty"`
	// Agreement holds the value of the agreement edge.
	Agreement *SupportAgreement `json:"agreement,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// TenantSubscriptionOrErr returns the TenantSubscription value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SupportFeeCycleEdges) TenantSubscriptionOrErr() (*TenantSubscription, error) {
	if e.TenantSubscription != nil {
		return e.TenantSubscription, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: tenantsubscription.Label}
	}
	return nil, &NotLoadedError{edge: "tenant_subscription"}
}

// SupportPlanOrErr returns the SupportPlan value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SupportFeeCycleEdges) SupportPlanOrErr() (*SubscriptionPlan, error) {
	if e.SupportPlan != nil {
		return e.SupportPlan, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: subscriptionplan.Label}
	}
	return nil, &NotLoadedError{edge: "support_plan"}
}

// AgreementOrErr returns the Agreement value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SupportFeeCycleEdges) AgreementOrErr() (*SupportAgreement, error) {
	if e.Agreement != nil {
		return e.Agreement, nil
	} else if e.loadedTypes[2] {
		return nil, &NotFoundError{label: supportagreement.Label}
	}
	return nil, &NotLoadedError{edge: "agreement"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*SupportFeeCycle) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case supportfeecycle.FieldSupportPlanID, supportfeecycle.FieldAgreementID, supportfeecycle.FieldCustomPriceSetBy:
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case supportfeecycle.FieldMetadata:
			values[i] = new([]byte)
		case supportfeecycle.FieldBasePrice, supportfeecycle.FieldCustomPrice:
			values[i] = new(sql.NullFloat64)
		case supportfeecycle.FieldCycleNumber:
			values[i] = new(sql.NullInt64)
		case supportfeecycle.FieldStatus, supportfeecycle.FieldCustomPriceReason:
			values[i] = new(sql.NullString)
		case supportfeecycle.FieldAnchorDate, supportfeecycle.FieldPeriodStart, supportfeecycle.FieldPeriodEnd, supportfeecycle.FieldDueDate, supportfeecycle.FieldPaidAt, supportfeecycle.FieldGraceUntil, supportfeecycle.FieldCustomPriceSetAt, supportfeecycle.FieldCreatedAt, supportfeecycle.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case supportfeecycle.FieldID, supportfeecycle.FieldTenantID, supportfeecycle.FieldTenantSubscriptionID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the SupportFeeCycle fields.
func (_m *SupportFeeCycle) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case supportfeecycle.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case supportfeecycle.FieldTenantID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field tenant_id", values[i])
			} else if value != nil {
				_m.TenantID = *value
			}
		case supportfeecycle.FieldTenantSubscriptionID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field tenant_subscription_id", values[i])
			} else if value != nil {
				_m.TenantSubscriptionID = *value
			}
		case supportfeecycle.FieldSupportPlanID:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field support_plan_id", values[i])
			} else if value.Valid {
				_m.SupportPlanID = new(uuid.UUID)
				*_m.SupportPlanID = *value.S.(*uuid.UUID)
			}
		case supportfeecycle.FieldAgreementID:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field agreement_id", values[i])
			} else if value.Valid {
				_m.AgreementID = new(uuid.UUID)
				*_m.AgreementID = *value.S.(*uuid.UUID)
			}
		case supportfeecycle.FieldAnchorDate:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field anchor_date", values[i])
			} else if value.Valid {
				_m.AnchorDate = value.Time
			}
		case supportfeecycle.FieldCycleNumber:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field cycle_number", values[i])
			} else if value.Valid {
				_m.CycleNumber = int(value.Int64)
			}
		case supportfeecycle.FieldPeriodStart:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field period_start", values[i])
			} else if value.Valid {
				_m.PeriodStart = value.Time
			}
		case supportfeecycle.FieldPeriodEnd:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field period_end", values[i])
			} else if value.Valid {
				_m.PeriodEnd = new(time.Time)
				*_m.PeriodEnd = value.Time
			}
		case supportfeecycle.FieldDueDate:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field due_date", values[i])
			} else if value.Valid {
				_m.DueDate = value.Time
			}
		case supportfeecycle.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = supportfeecycle.Status(value.String)
			}
		case supportfeecycle.FieldPaidAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field paid_at", values[i])
			} else if value.Valid {
				_m.PaidAt = new(time.Time)
				*_m.PaidAt = value.Time
			}
		case supportfeecycle.FieldGraceUntil:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field grace_until", values[i])
			} else if value.Valid {
				_m.GraceUntil = new(time.Time)
				*_m.GraceUntil = value.Time
			}
		case supportfeecycle.FieldBasePrice:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field base_price", values[i])
			} else if value.Valid {
				_m.BasePrice = value.Float64
			}
		case supportfeecycle.FieldCustomPrice:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field custom_price", values[i])
			} else if value.Valid {
				_m.CustomPrice = new(float64)
				*_m.CustomPrice = value.Float64
			}
		case supportfeecycle.FieldCustomPriceReason:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field custom_price_reason", values[i])
			} else if value.Valid {
				_m.CustomPriceReason = new(string)
				*_m.CustomPriceReason = value.String
			}
		case supportfeecycle.FieldCustomPriceSetBy:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field custom_price_set_by", values[i])
			} else if value.Valid {
				_m.CustomPriceSetBy = new(uuid.UUID)
				*_m.CustomPriceSetBy = *value.S.(*uuid.UUID)
			}
		case supportfeecycle.FieldCustomPriceSetAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field custom_price_set_at", values[i])
			} else if value.Valid {
				_m.CustomPriceSetAt = new(time.Time)
				*_m.CustomPriceSetAt = value.Time
			}
		case supportfeecycle.FieldMetadata:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field metadata", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Metadata); err != nil {
					return fmt.Errorf("unmarshal field metadata: %w", err)
				}
			}
		case supportfeecycle.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case supportfeecycle.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the SupportFeeCycle.
// This includes values selected through modifiers, order, etc.
func (_m *SupportFeeCycle) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryTenantSubscription queries the "tenant_subscription" edge of the SupportFeeCycle entity.
func (_m *SupportFeeCycle) QueryTenantSubscription() *TenantSubscriptionQuery {
	return NewSupportFeeCycleClient(_m.config).QueryTenantSubscription(_m)
}

// QuerySupportPlan queries the "support_plan" edge of the SupportFeeCycle entity.
func (_m *SupportFeeCycle) QuerySupportPlan() *SubscriptionPlanQuery {
	return NewSupportFeeCycleClient(_m.config).QuerySupportPlan(_m)
}

// QueryAgreement queries the "agreement" edge of the SupportFeeCycle entity.
func (_m *SupportFeeCycle) QueryAgreement() *SupportAgreementQuery {
	return NewSupportFeeCycleClient(_m.config).QueryAgreement(_m)
}

// Update returns a builder for updating this SupportFeeCycle.
// Note that you need to call SupportFeeCycle.Unwrap() before calling this method if this SupportFeeCycle
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *SupportFeeCycle) Update() *SupportFeeCycleUpdateOne {
	return NewSupportFeeCycleClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the SupportFeeCycle entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *SupportFeeCycle) Unwrap() *SupportFeeCycle {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: SupportFeeCycle is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *SupportFeeCycle) String() string {
	var builder strings.Builder
	builder.WriteString("SupportFeeCycle(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("tenant_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.TenantID))
	builder.WriteString(", ")
	builder.WriteString("tenant_subscription_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.TenantSubscriptionID))
	builder.WriteString(", ")
	if v := _m.SupportPlanID; v != nil {
		builder.WriteString("support_plan_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.AgreementID; v != nil {
		builder.WriteString("agreement_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("anchor_date=")
	builder.WriteString(_m.AnchorDate.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("cycle_number=")
	builder.WriteString(fmt.Sprintf("%v", _m.CycleNumber))
	builder.WriteString(", ")
	builder.WriteString("period_start=")
	builder.WriteString(_m.PeriodStart.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.PeriodEnd; v != nil {
		builder.WriteString("period_end=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("due_date=")
	builder.WriteString(_m.DueDate.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	if v := _m.PaidAt; v != nil {
		builder.WriteString("paid_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.GraceUntil; v != nil {
		builder.WriteString("grace_until=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("base_price=")
	builder.WriteString(fmt.Sprintf("%v", _m.BasePrice))
	builder.WriteString(", ")
	if v := _m.CustomPrice; v != nil {
		builder.WriteString("custom_price=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.CustomPriceReason; v != nil {
		builder.WriteString("custom_price_reason=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.CustomPriceSetBy; v != nil {
		builder.WriteString("custom_price_set_by=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.CustomPriceSetAt; v != nil {
		builder.WriteString("custom_price_set_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("metadata=")
	builder.WriteString(fmt.Sprintf("%v", _m.Metadata))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// SupportFeeCycles is a parsable slice of SupportFeeCycle.
type SupportFeeCycles []*SupportFeeCycle
