// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/bengobox/subscription-service/internal/ent/predicate"
	"github.com/bengobox/subscription-service/internal/ent/tenantemaildomain"
	"github.com/bengobox/subscription-service/internal/ent/tenantsubscription"
	"github.com/google/uuid"
)

// TenantEmailDomainUpdate is the builder for updating TenantEmailDomain entities.
type TenantEmailDomainUpdate struct {
	config
	hooks    []Hook
	mutation *TenantEmailDomainMutation
}

// Where appends a list predicates to the TenantEmailDomainUpdate builder.
func (_u *TenantEmailDomainUpdate) Where(ps ...predicate.TenantEmailDomain) *TenantEmailDomainUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTenantSubscriptionID sets the "tenant_subscription_id" field.
func (_u *TenantEmailDomainUpdate) SetTenantSubscriptionID(v uuid.UUID) *TenantEmailDomainUpdate {
	_u.mutation.SetTenantSubscriptionID(v)
	return _u
}

// SetNillableTenantSubscriptionID sets the "tenant_subscription_id" field if the given value is not nil.
func (_u *TenantEmailDomainUpdate) SetNillableTenantSubscriptionID(v *uuid.UUID) *TenantEmailDomainUpdate {
	if v != nil {
		_u.SetTenantSubscriptionID(*v)
	}
	return _u
}

// SetDomain sets the "domain" field.
func (_u *TenantEmailDomainUpdate) SetDomain(v string) *TenantEmailDomainUpdate {
	_u.mutation.SetDomain(v)
	return _u
}

// SetNillableDomain sets the "domain" field if the given value is not nil.
func (_u *TenantEmailDomainUpdate) SetNillableDomain(v *string) *TenantEmailDomainUpdate {
	if v != nil {
		_u.SetDomain(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *TenantEmailDomainUpdate) SetStatus(v tenantemaildomain.Status) *TenantEmailDomainUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *TenantEmailDomainUpdate) SetNillableStatus(v *tenantemaildomain.Status) *TenantEmailDomainUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetDkimSelector sets the "dkim_selector" field.
func (_u *TenantEmailDomainUpdate) SetDkimSelector(v string) *TenantEmailDomainUpdate {
	_u.mutation.SetDkimSelector(v)
	return _u
}

// SetNillableDkimSelector sets the "dkim_selector" field if the given value is not nil.
func (_u *TenantEmailDomainUpdate) SetNillableDkimSelector(v *string) *TenantEmailDomainUpdate {
	if v != nil {
		_u.SetDkimSelector(*v)
	}
	return _u
}

// ClearDkimSelector clears the value of the "dkim_selector" field.
func (_u *TenantEmailDomainUpdate) ClearDkimSelector() *TenantEmailDomainUpdate {
	_u.mutation.ClearDkimSelector()
	return _u
}

// SetStalwartDomainID sets the "stalwart_domain_id" field.
func (_u *TenantEmailDomainUpdate) SetStalwartDomainID(v string) *TenantEmailDomainUpdate {
	_u.mutation.SetStalwartDomainID(v)
	return _u
}

// SetNillableStalwartDomainID sets the "stalwart_domain_id" field if the given value is not nil.
func (_u *TenantEmailDomainUpdate) SetNillableStalwartDomainID(v *string) *TenantEmailDomainUpdate {
	if v != nil {
		_u.SetStalwartDomainID(*v)
	}
	return _u
}

// ClearStalwartDomainID clears the value of the "stalwart_domain_id" field.
func (_u *TenantEmailDomainUpdate) ClearStalwartDomainID() *TenantEmailDomainUpdate {
	_u.mutation.ClearStalwartDomainID()
	return _u
}

// SetVerifiedAt sets the "verified_at" field.
func (_u *TenantEmailDomainUpdate) SetVerifiedAt(v time.Time) *TenantEmailDomainUpdate {
	_u.mutation.SetVerifiedAt(v)
	return _u
}

// SetNillableVerifiedAt sets the "verified_at" field if the given value is not nil.
func (_u *TenantEmailDomainUpdate) SetNillableVerifiedAt(v *time.Time) *TenantEmailDomainUpdate {
	if v != nil {
		_u.SetVerifiedAt(*v)
	}
	return _u
}

// ClearVerifiedAt clears the value of the "verified_at" field.
func (_u *TenantEmailDomainUpdate) ClearVerifiedAt() *TenantEmailDomainUpdate {
	_u.mutation.ClearVerifiedAt()
	return _u
}

// SetLastCheckedAt sets the "last_checked_at" field.
func (_u *TenantEmailDomainUpdate) SetLastCheckedAt(v time.Time) *TenantEmailDomainUpdate {
	_u.mutation.SetLastCheckedAt(v)
	return _u
}

// SetNillableLastCheckedAt sets the "last_checked_at" field if the given value is not nil.
func (_u *TenantEmailDomainUpdate) SetNillableLastCheckedAt(v *time.Time) *TenantEmailDomainUpdate {
	if v != nil {
		_u.SetLastCheckedAt(*v)
	}
	return _u
}

// ClearLastCheckedAt clears the value of the "last_checked_at" field.
func (_u *TenantEmailDomainUpdate) ClearLastCheckedAt() *TenantEmailDomainUpdate {
	_u.mutation.ClearLastCheckedAt()
	return _u
}

// SetFailureReason sets the "failure_reason" field.
func (_u *TenantEmailDomainUpdate) SetFailureReason(v string) *TenantEmailDomainUpdate {
	_u.mutation.SetFailureReason(v)
	return _u
}

// SetNillableFailureReason sets the "failure_reason" field if the given value is not nil.
func (_u *TenantEmailDomainUpdate) SetNillableFailureReason(v *string) *TenantEmailDomainUpdate {
	if v != nil {
		_u.SetFailureReason(*v)
	}
	return _u
}

// ClearFailureReason clears the value of the "failure_reason" field.
func (_u *TenantEmailDomainUpdate) ClearFailureReason() *TenantEmailDomainUpdate {
	_u.mutation.ClearFailureReason()
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *TenantEmailDomainUpdate) SetMetadata(v map[string]interface{}) *TenantEmailDomainUpdate {
	_u.mutation.SetMetadata(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TenantEmailDomainUpdate) SetUpdatedAt(v time.Time) *TenantEmailDomainUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetTenantSubscription sets the "tenant_subscription" edge to the TenantSubscription entity.
func (_u *TenantEmailDomainUpdate) SetTenantSubscription(v *TenantSubscription) *TenantEmailDomainUpdate {
	return _u.SetTenantSubscriptionID(v.ID)
}

// Mutation returns the TenantEmailDomainMutation object of the builder.
func (_u *TenantEmailDomainUpdate) Mutation() *TenantEmailDomainMutation {
	return _u.mutation
}

// ClearTenantSubscription clears the "tenant_subscription" edge to the TenantSubscription entity.
func (_u *TenantEmailDomainUpdate) ClearTenantSubscription() *TenantEmailDomainUpdate {
	_u.mutation.ClearTenantSubscription()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TenantEmailDomainUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TenantEmailDomainUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TenantEmailDomainUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TenantEmailDomainUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *TenantEmailDomainUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := tenantemaildomain.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TenantEmailDomainUpdate) check() error {
	if v, ok := _u.mutation.Domain(); ok {
		if err := tenantemaildomain.DomainValidator(v); err != nil {
			return &ValidationError{Name: "domain", err: fmt.Errorf(`ent: validator failed for field "TenantEmailDomain.domain": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := tenantemaildomain.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "TenantEmailDomain.status": %w`, err)}
		}
	}
	if _u.mutation.TenantSubscriptionCleared() && len(_u.mutation.TenantSubscriptionIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "TenantEmailDomain.tenant_subscription"`)
	}
	return nil
}

func (_u *TenantEmailDomainUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(tenantemaildomain.Table, tenantemaildomain.Columns, sqlgraph.NewFieldSpec(tenantemaildomain.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Domain(); ok {
		_spec.SetField(tenantemaildomain.FieldDomain, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(tenantemaildomain.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.DkimSelector(); ok {
		_spec.SetField(tenantemaildomain.FieldDkimSelector, field.TypeString, value)
	}
	if _u.mutation.DkimSelectorCleared() {
		_spec.ClearField(tenantemaildomain.FieldDkimSelector, field.TypeString)
	}
	if value, ok := _u.mutation.StalwartDomainID(); ok {
		_spec.SetField(tenantemaildomain.FieldStalwartDomainID, field.TypeString, value)
	}
	if _u.mutation.StalwartDomainIDCleared() {
		_spec.ClearField(tenantemaildomain.FieldStalwartDomainID, field.TypeString)
	}
	if value, ok := _u.mutation.VerifiedAt(); ok {
		_spec.SetField(tenantemaildomain.FieldVerifiedAt, field.TypeTime, value)
	}
	if _u.mutation.VerifiedAtCleared() {
		_spec.ClearField(tenantemaildomain.FieldVerifiedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastCheckedAt(); ok {
		_spec.SetField(tenantemaildomain.FieldLastCheckedAt, field.TypeTime, value)
	}
	if _u.mutation.LastCheckedAtCleared() {
		_spec.ClearField(tenantemaildomain.FieldLastCheckedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.FailureReason(); ok {
		_spec.SetField(tenantemaildomain.FieldFailureReason, field.TypeString, value)
	}
	if _u.mutation.FailureReasonCleared() {
		_spec.ClearField(tenantemaildomain.FieldFailureReason, field.TypeString)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(tenantemaildomain.FieldMetadata, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(tenantemaildomain.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.TenantSubscriptionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   tenantemaildomain.TenantSubscriptionTable,
			Columns: []string{tenantemaildomain.TenantSubscriptionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenantsubscription.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TenantSubscriptionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   tenantemaildomain.TenantSubscriptionTable,
			Columns: []string{tenantemaildomain.TenantSubscriptionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenantsubscription.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{tenantemaildomain.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// TenantEmailDomainUpdateOne is the builder for updating a single TenantEmailDomain entity.
type TenantEmailDomainUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TenantEmailDomainMutation
}

// SetTenantSubscriptionID sets the "tenant_subscription_id" field.
func (_u *TenantEmailDomainUpdateOne) SetTenantSubscriptionID(v uuid.UUID) *TenantEmailDomainUpdateOne {
	_u.mutation.SetTenantSubscriptionID(v)
	return _u
}

// SetNillableTenantSubscriptionID sets the "tenant_subscription_id" field if the given value is not nil.
func (_u *TenantEmailDomainUpdateOne) SetNillableTenantSubscriptionID(v *uuid.UUID) *TenantEmailDomainUpdateOne {
	if v != nil {
		_u.SetTenantSubscriptionID(*v)
	}
	return _u
}

// SetDomain sets the "domain" field.
func (_u *TenantEmailDomainUpdateOne) SetDomain(v string) *TenantEmailDomainUpdateOne {
	_u.mutation.SetDomain(v)
	return _u
}

// SetNillableDomain sets the "domain" field if the given value is not nil.
func (_u *TenantEmailDomainUpdateOne) SetNillableDomain(v *string) *TenantEmailDomainUpdateOne {
	if v != nil {
		_u.SetDomain(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *TenantEmailDomainUpdateOne) SetStatus(v tenantemaildomain.Status) *TenantEmailDomainUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *TenantEmailDomainUpdateOne) SetNillableStatus(v *tenantemaildomain.Status) *TenantEmailDomainUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetDkimSelector sets the "dkim_selector" field.
func (_u *TenantEmailDomainUpdateOne) SetDkimSelector(v string) *TenantEmailDomainUpdateOne {
	_u.mutation.SetDkimSelector(v)
	return _u
}

// SetNillableDkimSelector sets the "dkim_selector" field if the given value is not nil.
func (_u *TenantEmailDomainUpdateOne) SetNillableDkimSelector(v *string) *TenantEmailDomainUpdateOne {
	if v != nil {
		_u.SetDkimSelector(*v)
	}
	return _u
}

// ClearDkimSelector clears the value of the "dkim_selector" field.
func (_u *TenantEmailDomainUpdateOne) ClearDkimSelector() *TenantEmailDomainUpdateOne {
	_u.mutation.ClearDkimSelector()
	return _u
}

// SetStalwartDomainID sets the "stalwart_domain_id" field.
func (_u *TenantEmailDomainUpdateOne) SetStalwartDomainID(v string) *TenantEmailDomainUpdateOne {
	_u.mutation.SetStalwartDomainID(v)
	return _u
}

// SetNillableStalwartDomainID sets the "stalwart_domain_id" field if the given value is not nil.
func (_u *TenantEmailDomainUpdateOne) SetNillableStalwartDomainID(v *string) *TenantEmailDomainUpdateOne {
	if v != nil {
		_u.SetStalwartDomainID(*v)
	}
	return _u
}

// ClearStalwartDomainID clears the value of the "stalwart_domain_id" field.
func (_u *TenantEmailDomainUpdateOne) ClearStalwartDomainID() *TenantEmailDomainUpdateOne {
	_u.mutation.ClearStalwartDomainID()
	return _u
}

// SetVerifiedAt sets the "verified_at" field.
func (_u *TenantEmailDomainUpdateOne) SetVerifiedAt(v time.Time) *TenantEmailDomainUpdateOne {
	_u.mutation.SetVerifiedAt(v)
	return _u
}

// SetNillableVerifiedAt sets the "verified_at" field if the given value is not nil.
func (_u *TenantEmailDomainUpdateOne) SetNillableVerifiedAt(v *time.Time) *TenantEmailDomainUpdateOne {
	if v != nil {
		_u.SetVerifiedAt(*v)
	}
	return _u
}

// ClearVerifiedAt clears the value of the "verified_at" field.
func (_u *TenantEmailDomainUpdateOne) ClearVerifiedAt() *TenantEmailDomainUpdateOne {
	_u.mutation.ClearVerifiedAt()
	return _u
}

// SetLastCheckedAt sets the "last_checked_at" field.
func (_u *TenantEmailDomainUpdateOne) SetLastCheckedAt(v time.Time) *TenantEmailDomainUpdateOne {
	_u.mutation.SetLastCheckedAt(v)
	return _u
}

// SetNillableLastCheckedAt sets the "last_checked_at" field if the given value is not nil.
func (_u *TenantEmailDomainUpdateOne) SetNillableLastCheckedAt(v *time.Time) *TenantEmailDomainUpdateOne {
	if v != nil {
		_u.SetLastCheckedAt(*v)
	}
	return _u
}

// ClearLastCheckedAt clears the value of the "last_checked_at" field.
func (_u *TenantEmailDomainUpdateOne) ClearLastCheckedAt() *TenantEmailDomainUpdateOne {
	_u.mutation.ClearLastCheckedAt()
	return _u
}

// SetFailureReason sets the "failure_reason" field.
func (_u *TenantEmailDomainUpdateOne) SetFailureReason(v string) *TenantEmailDomainUpdateOne {
	_u.mutation.SetFailureReason(v)
	return _u
}

// SetNillableFailureReason sets the "failure_reason" field if the given value is not nil.
func (_u *TenantEmailDomainUpdateOne) SetNillableFailureReason(v *string) *TenantEmailDomainUpdateOne {
	if v != nil {
		_u.SetFailureReason(*v)
	}
	return _u
}

// ClearFailureReason clears the value of the "failure_reason" field.
func (_u *TenantEmailDomainUpdateOne) ClearFailureReason() *TenantEmailDomainUpdateOne {
	_u.mutation.ClearFailureReason()
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *TenantEmailDomainUpdateOne) SetMetadata(v map[string]interface{}) *TenantEmailDomainUpdateOne {
	_u.mutation.SetMetadata(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TenantEmailDomainUpdateOne) SetUpdatedAt(v time.Time) *TenantEmailDomainUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetTenantSubscription sets the "tenant_subscription" edge to the TenantSubscription entity.
func (_u *TenantEmailDomainUpdateOne) SetTenantSubscription(v *TenantSubscription) *TenantEmailDomainUpdateOne {
	return _u.SetTenantSubscriptionID(v.ID)
}

// Mutation returns the TenantEmailDomainMutation object of the builder.
func (_u *TenantEmailDomainUpdateOne) Mutation() *TenantEmailDomainMutation {
	return _u.mutation
}

// ClearTenantSubscription clears the "tenant_subscription" edge to the TenantSubscription entity.
func (_u *TenantEmailDomainUpdateOne) ClearTenantSubscription() *TenantEmailDomainUpdateOne {
	_u.mutation.ClearTenantSubscription()
	return _u
}

// Where appends a list predicates to the TenantEmailDomainUpdate builder.
func (_u *TenantEmailDomainUpdateOne) Where(ps ...predicate.TenantEmailDomain) *TenantEmailDomainUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *TenantEmailDomainUpdateOne) Select(field string, fields ...string) *TenantEmailDomainUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated TenantEmailDomain entity.
func (_u *TenantEmailDomainUpdateOne) Save(ctx context.Context) (*TenantEmailDomain, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TenantEmailDomainUpdateOne) SaveX(ctx context.Context) *TenantEmailDomain {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TenantEmailDomainUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TenantEmailDomainUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *TenantEmailDomainUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := tenantemaildomain.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TenantEmailDomainUpdateOne) check() error {
	if v, ok := _u.mutation.Domain(); ok {
		if err := tenantemaildomain.DomainValidator(v); err != nil {
			return &ValidationError{Name: "domain", err: fmt.Errorf(`ent: validator failed for field "TenantEmailDomain.domain": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := tenantemaildomain.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "TenantEmailDomain.status": %w`, err)}
		}
	}
	if _u.mutation.TenantSubscriptionCleared() && len(_u.mutation.TenantSubscriptionIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "TenantEmailDomain.tenant_subscription"`)
	}
	return nil
}

func (_u *TenantEmailDomainUpdateOne) sqlSave(ctx context.Context) (_node *TenantEmailDomain, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(tenantemaildomain.Table, tenantemaildomain.Columns, sqlgraph.NewFieldSpec(tenantemaildomain.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "TenantEmailDomain.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, tenantemaildomain.FieldID)
		for _, f := range fields {
			if !tenantemaildomain.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != tenantemaildomain.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Domain(); ok {
		_spec.SetField(tenantemaildomain.FieldDomain, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(tenantemaildomain.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.DkimSelector(); ok {
		_spec.SetField(tenantemaildomain.FieldDkimSelector, field.TypeString, value)
	}
	if _u.mutation.DkimSelectorCleared() {
		_spec.ClearField(tenantemaildomain.FieldDkimSelector, field.TypeString)
	}
	if value, ok := _u.mutation.StalwartDomainID(); ok {
		_spec.SetField(tenantemaildomain.FieldStalwartDomainID, field.TypeString, value)
	}
	if _u.mutation.StalwartDomainIDCleared() {
		_spec.ClearField(tenantemaildomain.FieldStalwartDomainID, field.TypeString)
	}
	if value, ok := _u.mutation.VerifiedAt(); ok {
		_spec.SetField(tenantemaildomain.FieldVerifiedAt, field.TypeTime, value)
	}
	if _u.mutation.VerifiedAtCleared() {
		_spec.ClearField(tenantemaildomain.FieldVerifiedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastCheckedAt(); ok {
		_spec.SetField(tenantemaildomain.FieldLastCheckedAt, field.TypeTime, value)
	}
	if _u.mutation.LastCheckedAtCleared() {
		_spec.ClearField(tenantemaildomain.FieldLastCheckedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.FailureReason(); ok {
		_spec.SetField(tenantemaildomain.FieldFailureReason, field.TypeString, value)
	}
	if _u.mutation.FailureReasonCleared() {
		_spec.ClearField(tenantemaildomain.FieldFailureReason, field.TypeString)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(tenantemaildomain.FieldMetadata, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(tenantemaildomain.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.TenantSubscriptionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   tenantemaildomain.TenantSubscriptionTable,
			Columns: []string{tenantemaildomain.TenantSubscriptionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenantsubscription.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TenantSubscriptionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   tenantemaildomain.TenantSubscriptionTable,
			Columns: []string{tenantemaildomain.TenantSubscriptionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenantsubscription.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &TenantEmailDomain{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{tenantemaildomain.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
