// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/bengobox/subscription-service/internal/ent/overagecharge"
	"github.com/bengobox/subscription-service/internal/ent/productsubscription"
	"github.com/bengobox/subscription-service/internal/ent/subscriptionplan"
	"github.com/bengobox/subscription-service/internal/ent/tenant"
	"github.com/bengobox/subscription-service/internal/ent/tenantsubscription"
	"github.com/google/uuid"
)

// TenantSubscriptionCreate is the builder for creating a TenantSubscription entity.
type TenantSubscriptionCreate struct {
	config
	mutation *TenantSubscriptionMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetTenantID sets the "tenant_id" field.
func (_c *TenantSubscriptionCreate) SetTenantID(v uuid.UUID) *TenantSubscriptionCreate {
	_c.mutation.SetTenantID(v)
	return _c
}

// SetPlanID sets the "plan_id" field.
func (_c *TenantSubscriptionCreate) SetPlanID(v uuid.UUID) *TenantSubscriptionCreate {
	_c.mutation.SetPlanID(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *TenantSubscriptionCreate) SetStatus(v tenantsubscription.Status) *TenantSubscriptionCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *TenantSubscriptionCreate) SetNillableStatus(v *tenantsubscription.Status) *TenantSubscriptionCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetTrialEndsAt sets the "trial_ends_at" field.
func (_c *TenantSubscriptionCreate) SetTrialEndsAt(v time.Time) *TenantSubscriptionCreate {
	_c.mutation.SetTrialEndsAt(v)
	return _c
}

// SetNillableTrialEndsAt sets the "trial_ends_at" field if the given value is not nil.
func (_c *TenantSubscriptionCreate) SetNillableTrialEndsAt(v *time.Time) *TenantSubscriptionCreate {
	if v != nil {
		_c.SetTrialEndsAt(*v)
	}
	return _c
}

// SetCurrentPeriodStart sets the "current_period_start" field.
func (_c *TenantSubscriptionCreate) SetCurrentPeriodStart(v time.Time) *TenantSubscriptionCreate {
	_c.mutation.SetCurrentPeriodStart(v)
	return _c
}

// SetCurrentPeriodEnd sets the "current_period_end" field.
func (_c *TenantSubscriptionCreate) SetCurrentPeriodEnd(v time.Time) *TenantSubscriptionCreate {
	_c.mutation.SetCurrentPeriodEnd(v)
	return _c
}

// SetCancelledAt sets the "cancelled_at" field.
func (_c *TenantSubscriptionCreate) SetCancelledAt(v time.Time) *TenantSubscriptionCreate {
	_c.mutation.SetCancelledAt(v)
	return _c
}

// SetNillableCancelledAt sets the "cancelled_at" field if the given value is not nil.
func (_c *TenantSubscriptionCreate) SetNillableCancelledAt(v *time.Time) *TenantSubscriptionCreate {
	if v != nil {
		_c.SetCancelledAt(*v)
	}
	return _c
}

// SetCancelReason sets the "cancel_reason" field.
func (_c *TenantSubscriptionCreate) SetCancelReason(v string) *TenantSubscriptionCreate {
	_c.mutation.SetCancelReason(v)
	return _c
}

// SetNillableCancelReason sets the "cancel_reason" field if the given value is not nil.
func (_c *TenantSubscriptionCreate) SetNillableCancelReason(v *string) *TenantSubscriptionCreate {
	if v != nil {
		_c.SetCancelReason(*v)
	}
	return _c
}

// SetBillingCycle sets the "billing_cycle" field.
func (_c *TenantSubscriptionCreate) SetBillingCycle(v tenantsubscription.BillingCycle) *TenantSubscriptionCreate {
	_c.mutation.SetBillingCycle(v)
	return _c
}

// SetNillableBillingCycle sets the "billing_cycle" field if the given value is not nil.
func (_c *TenantSubscriptionCreate) SetNillableBillingCycle(v *tenantsubscription.BillingCycle) *TenantSubscriptionCreate {
	if v != nil {
		_c.SetBillingCycle(*v)
	}
	return _c
}

// SetAppliedDiscount sets the "applied_discount" field.
func (_c *TenantSubscriptionCreate) SetAppliedDiscount(v float64) *TenantSubscriptionCreate {
	_c.mutation.SetAppliedDiscount(v)
	return _c
}

// SetNillableAppliedDiscount sets the "applied_discount" field if the given value is not nil.
func (_c *TenantSubscriptionCreate) SetNillableAppliedDiscount(v *float64) *TenantSubscriptionCreate {
	if v != nil {
		_c.SetAppliedDiscount(*v)
	}
	return _c
}

// SetBundleCode sets the "bundle_code" field.
func (_c *TenantSubscriptionCreate) SetBundleCode(v string) *TenantSubscriptionCreate {
	_c.mutation.SetBundleCode(v)
	return _c
}

// SetNillableBundleCode sets the "bundle_code" field if the given value is not nil.
func (_c *TenantSubscriptionCreate) SetNillableBundleCode(v *string) *TenantSubscriptionCreate {
	if v != nil {
		_c.SetBundleCode(*v)
	}
	return _c
}

// SetPaymentMethodID sets the "payment_method_id" field.
func (_c *TenantSubscriptionCreate) SetPaymentMethodID(v uuid.UUID) *TenantSubscriptionCreate {
	_c.mutation.SetPaymentMethodID(v)
	return _c
}

// SetNillablePaymentMethodID sets the "payment_method_id" field if the given value is not nil.
func (_c *TenantSubscriptionCreate) SetNillablePaymentMethodID(v *uuid.UUID) *TenantSubscriptionCreate {
	if v != nil {
		_c.SetPaymentMethodID(*v)
	}
	return _c
}

// SetMetadata sets the "metadata" field.
func (_c *TenantSubscriptionCreate) SetMetadata(v map[string]interface{}) *TenantSubscriptionCreate {
	_c.mutation.SetMetadata(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *TenantSubscriptionCreate) SetCreatedAt(v time.Time) *TenantSubscriptionCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *TenantSubscriptionCreate) SetNillableCreatedAt(v *time.Time) *TenantSubscriptionCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *TenantSubscriptionCreate) SetUpdatedAt(v time.Time) *TenantSubscriptionCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *TenantSubscriptionCreate) SetNillableUpdatedAt(v *time.Time) *TenantSubscriptionCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *TenantSubscriptionCreate) SetID(v uuid.UUID) *TenantSubscriptionCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *TenantSubscriptionCreate) SetNillableID(v *uuid.UUID) *TenantSubscriptionCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetTenant sets the "tenant" edge to the Tenant entity.
func (_c *TenantSubscriptionCreate) SetTenant(v *Tenant) *TenantSubscriptionCreate {
	return _c.SetTenantID(v.ID)
}

// SetPlan sets the "plan" edge to the SubscriptionPlan entity.
func (_c *TenantSubscriptionCreate) SetPlan(v *SubscriptionPlan) *TenantSubscriptionCreate {
	return _c.SetPlanID(v.ID)
}

// AddProductSubscriptionIDs adds the "product_subscriptions" edge to the ProductSubscription entity by IDs.
func (_c *TenantSubscriptionCreate) AddProductSubscriptionIDs(ids ...uuid.UUID) *TenantSubscriptionCreate {
	_c.mutation.AddProductSubscriptionIDs(ids...)
	return _c
}

// AddProductSubscriptions adds the "product_subscriptions" edges to the ProductSubscription entity.
func (_c *TenantSubscriptionCreate) AddProductSubscriptions(v ...*ProductSubscription) *TenantSubscriptionCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddProductSubscriptionIDs(ids...)
}

// AddOverageChargeIDs adds the "overage_charges" edge to the OverageCharge entity by IDs.
func (_c *TenantSubscriptionCreate) AddOverageChargeIDs(ids ...uuid.UUID) *TenantSubscriptionCreate {
	_c.mutation.AddOverageChargeIDs(ids...)
	return _c
}

// AddOverageCharges adds the "overage_charges" edges to the OverageCharge entity.
func (_c *TenantSubscriptionCreate) AddOverageCharges(v ...*OverageCharge) *TenantSubscriptionCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddOverageChargeIDs(ids...)
}

// Mutation returns the TenantSubscriptionMutation object of the builder.
func (_c *TenantSubscriptionCreate) Mutation() *TenantSubscriptionMutation {
	return _c.mutation
}

// Save creates the TenantSubscription in the database.
func (_c *TenantSubscriptionCreate) Save(ctx context.Context) (*TenantSubscription, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *TenantSubscriptionCreate) SaveX(ctx context.Context) *TenantSubscription {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TenantSubscriptionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TenantSubscriptionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *TenantSubscriptionCreate) defaults() {
	if _, ok := _c.mutation.Status(); !ok {
		v := tenantsubscription.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.BillingCycle(); !ok {
		v := tenantsubscription.DefaultBillingCycle
		_c.mutation.SetBillingCycle(v)
	}
	if _, ok := _c.mutation.AppliedDiscount(); !ok {
		v := tenantsubscription.DefaultAppliedDiscount
		_c.mutation.SetAppliedDiscount(v)
	}
	if _, ok := _c.mutation.Metadata(); !ok {
		v := tenantsubscription.DefaultMetadata
		_c.mutation.SetMetadata(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := tenantsubscription.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := tenantsubscription.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := tenantsubscription.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *TenantSubscriptionCreate) check() error {
	if _, ok := _c.mutation.TenantID(); !ok {
		return &ValidationError{Name: "tenant_id", err: errors.New(`ent: missing required field "TenantSubscription.tenant_id"`)}
	}
	if _, ok := _c.mutation.PlanID(); !ok {
		return &ValidationError{Name: "plan_id", err: errors.New(`ent: missing required field "TenantSubscription.plan_id"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "TenantSubscription.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := tenantsubscription.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "TenantSubscription.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CurrentPeriodStart(); !ok {
		return &ValidationError{Name: "current_period_start", err: errors.New(`ent: missing required field "TenantSubscription.current_period_start"`)}
	}
	if _, ok := _c.mutation.CurrentPeriodEnd(); !ok {
		return &ValidationError{Name: "current_period_end", err: errors.New(`ent: missing required field "TenantSubscription.current_period_end"`)}
	}
	if _, ok := _c.mutation.BillingCycle(); !ok {
		return &ValidationError{Name: "billing_cycle", err: errors.New(`ent: missing required field "TenantSubscription.billing_cycle"`)}
	}
	if v, ok := _c.mutation.BillingCycle(); ok {
		if err := tenantsubscription.BillingCycleValidator(v); err != nil {
			return &ValidationError{Name: "billing_cycle", err: fmt.Errorf(`ent: validator failed for field "TenantSubscription.billing_cycle": %w`, err)}
		}
	}
	if _, ok := _c.mutation.AppliedDiscount(); !ok {
		return &ValidationError{Name: "applied_discount", err: errors.New(`ent: missing required field "TenantSubscription.applied_discount"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "TenantSubscription.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "TenantSubscription.updated_at"`)}
	}
	if len(_c.mutation.TenantIDs()) == 0 {
		return &ValidationError{Name: "tenant", err: errors.New(`ent: missing required edge "TenantSubscription.tenant"`)}
	}
	if len(_c.mutation.PlanIDs()) == 0 {
		return &ValidationError{Name: "plan", err: errors.New(`ent: missing required edge "TenantSubscription.plan"`)}
	}
	return nil
}

func (_c *TenantSubscriptionCreate) sqlSave(ctx context.Context) (*TenantSubscription, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *TenantSubscriptionCreate) createSpec() (*TenantSubscription, *sqlgraph.CreateSpec) {
	var (
		_node = &TenantSubscription{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(tenantsubscription.Table, sqlgraph.NewFieldSpec(tenantsubscription.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(tenantsubscription.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.TrialEndsAt(); ok {
		_spec.SetField(tenantsubscription.FieldTrialEndsAt, field.TypeTime, value)
		_node.TrialEndsAt = &value
	}
	if value, ok := _c.mutation.CurrentPeriodStart(); ok {
		_spec.SetField(tenantsubscription.FieldCurrentPeriodStart, field.TypeTime, value)
		_node.CurrentPeriodStart = value
	}
	if value, ok := _c.mutation.CurrentPeriodEnd(); ok {
		_spec.SetField(tenantsubscription.FieldCurrentPeriodEnd, field.TypeTime, value)
		_node.CurrentPeriodEnd = value
	}
	if value, ok := _c.mutation.CancelledAt(); ok {
		_spec.SetField(tenantsubscription.FieldCancelledAt, field.TypeTime, value)
		_node.CancelledAt = &value
	}
	if value, ok := _c.mutation.CancelReason(); ok {
		_spec.SetField(tenantsubscription.FieldCancelReason, field.TypeString, value)
		_node.CancelReason = &value
	}
	if value, ok := _c.mutation.BillingCycle(); ok {
		_spec.SetField(tenantsubscription.FieldBillingCycle, field.TypeEnum, value)
		_node.BillingCycle = value
	}
	if value, ok := _c.mutation.AppliedDiscount(); ok {
		_spec.SetField(tenantsubscription.FieldAppliedDiscount, field.TypeFloat64, value)
		_node.AppliedDiscount = value
	}
	if value, ok := _c.mutation.BundleCode(); ok {
		_spec.SetField(tenantsubscription.FieldBundleCode, field.TypeString, value)
		_node.BundleCode = &value
	}
	if value, ok := _c.mutation.PaymentMethodID(); ok {
		_spec.SetField(tenantsubscription.FieldPaymentMethodID, field.TypeUUID, value)
		_node.PaymentMethodID = &value
	}
	if value, ok := _c.mutation.Metadata(); ok {
		_spec.SetField(tenantsubscription.FieldMetadata, field.TypeJSON, value)
		_node.Metadata = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(tenantsubscription.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(tenantsubscription.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.TenantIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   tenantsubscription.TenantTable,
			Columns: []string{tenantsubscription.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.TenantID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.PlanIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   tenantsubscription.PlanTable,
			Columns: []string{tenantsubscription.PlanColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscriptionplan.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.PlanID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ProductSubscriptionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenantsubscription.ProductSubscriptionsTable,
			Columns: []string{tenantsubscription.ProductSubscriptionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(productsubscription.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.OverageChargesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenantsubscription.OverageChargesTable,
			Columns: []string{tenantsubscription.OverageChargesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(overagecharge.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.TenantSubscription.Create().
//		SetTenantID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.TenantSubscriptionUpsert) {
//			SetTenantID(v+v).
//		}).
//		Exec(ctx)
func (_c *TenantSubscriptionCreate) OnConflict(opts ...sql.ConflictOption) *TenantSubscriptionUpsertOne {
	_c.conflict = opts
	return &TenantSubscriptionUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.TenantSubscription.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *TenantSubscriptionCreate) OnConflictColumns(columns ...string) *TenantSubscriptionUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &TenantSubscriptionUpsertOne{
		create: _c,
	}
}

type (
	// TenantSubscriptionUpsertOne is the builder for "upsert"-ing
	//  one TenantSubscription node.
	TenantSubscriptionUpsertOne struct {
		create *TenantSubscriptionCreate
	}

	// TenantSubscriptionUpsert is the "OnConflict" setter.
	TenantSubscriptionUpsert struct {
		*sql.UpdateSet
	}
)

// SetTenantID sets the "tenant_id" field.
func (u *TenantSubscriptionUpsert) SetTenantID(v uuid.UUID) *TenantSubscriptionUpsert {
	u.Set(tenantsubscription.FieldTenantID, v)
	return u
}

// UpdateTenantID sets the "tenant_id" field to the value that was provided on create.
func (u *TenantSubscriptionUpsert) UpdateTenantID() *TenantSubscriptionUpsert {
	u.SetExcluded(tenantsubscription.FieldTenantID)
	return u
}

// SetPlanID sets the "plan_id" field.
func (u *TenantSubscriptionUpsert) SetPlanID(v uuid.UUID) *TenantSubscriptionUpsert {
	u.Set(tenantsubscription.FieldPlanID, v)
	return u
}

// UpdatePlanID sets the "plan_id" field to the value that was provided on create.
func (u *TenantSubscriptionUpsert) UpdatePlanID() *TenantSubscriptionUpsert {
	u.SetExcluded(tenantsubscription.FieldPlanID)
	return u
}

// SetStatus sets the "status" field.
func (u *TenantSubscriptionUpsert) SetStatus(v tenantsubscription.Status) *TenantSubscriptionUpsert {
	u.Set(tenantsubscription.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *TenantSubscriptionUpsert) UpdateStatus() *TenantSubscriptionUpsert {
	u.SetExcluded(tenantsubscription.FieldStatus)
	return u
}

// SetTrialEndsAt sets the "trial_ends_at" field.
func (u *TenantSubscriptionUpsert) SetTrialEndsAt(v time.Time) *TenantSubscriptionUpsert {
	u.Set(tenantsubscription.FieldTrialEndsAt, v)
	return u
}

// UpdateTrialEndsAt sets the "trial_ends_at" field to the value that was provided on create.
func (u *TenantSubscriptionUpsert) UpdateTrialEndsAt() *TenantSubscriptionUpsert {
	u.SetExcluded(tenantsubscription.FieldTrialEndsAt)
	return u
}

// ClearTrialEndsAt clears the value of the "trial_ends_at" field.
func (u *TenantSubscriptionUpsert) ClearTrialEndsAt() *TenantSubscriptionUpsert {
	u.SetNull(tenantsubscription.FieldTrialEndsAt)
	return u
}

// SetCurrentPeriodStart sets the "current_period_start" field.
func (u *TenantSubscriptionUpsert) SetCurrentPeriodStart(v time.Time) *TenantSubscriptionUpsert {
	u.Set(tenantsubscription.FieldCurrentPeriodStart, v)
	return u
}

// UpdateCurrentPeriodStart sets the "current_period_start" field to the value that was provided on create.
func (u *TenantSubscriptionUpsert) UpdateCurrentPeriodStart() *TenantSubscriptionUpsert {
	u.SetExcluded(tenantsubscription.FieldCurrentPeriodStart)
	return u
}

// SetCurrentPeriodEnd sets the "current_period_end" field.
func (u *TenantSubscriptionUpsert) SetCurrentPeriodEnd(v time.Time) *TenantSubscriptionUpsert {
	u.Set(tenantsubscription.FieldCurrentPeriodEnd, v)
	return u
}

// UpdateCurrentPeriodEnd sets the "current_period_end" field to the value that was provided on create.
func (u *TenantSubscriptionUpsert) UpdateCurrentPeriodEnd() *TenantSubscriptionUpsert {
	u.SetExcluded(tenantsubscription.FieldCurrentPeriodEnd)
	return u
}

// SetCancelledAt sets the "cancelled_at" field.
func (u *TenantSubscriptionUpsert) SetCancelledAt(v time.Time) *TenantSubscriptionUpsert {
	u.Set(tenantsubscription.FieldCancelledAt, v)
	return u
}

// UpdateCancelledAt sets the "cancelled_at" field to the value that was provided on create.
func (u *TenantSubscriptionUpsert) UpdateCancelledAt() *TenantSubscriptionUpsert {
	u.SetExcluded(tenantsubscription.FieldCancelledAt)
	return u
}

// ClearCancelledAt clears the value of the "cancelled_at" field.
func (u *TenantSubscriptionUpsert) ClearCancelledAt() *TenantSubscriptionUpsert {
	u.SetNull(tenantsubscription.FieldCancelledAt)
	return u
}

// SetCancelReason sets the "cancel_reason" field.
func (u *TenantSubscriptionUpsert) SetCancelReason(v string) *TenantSubscriptionUpsert {
	u.Set(tenantsubscription.FieldCancelReason, v)
	return u
}

// UpdateCancelReason sets the "cancel_reason" field to the value that was provided on create.
func (u *TenantSubscriptionUpsert) UpdateCancelReason() *TenantSubscriptionUpsert {
	u.SetExcluded(tenantsubscription.FieldCancelReason)
	return u
}

// ClearCancelReason clears the value of the "cancel_reason" field.
func (u *TenantSubscriptionUpsert) ClearCancelReason() *TenantSubscriptionUpsert {
	u.SetNull(tenantsubscription.FieldCancelReason)
	return u
}

// SetBillingCycle sets the "billing_cycle" field.
func (u *TenantSubscriptionUpsert) SetBillingCycle(v tenantsubscription.BillingCycle) *TenantSubscriptionUpsert {
	u.Set(tenantsubscription.FieldBillingCycle, v)
	return u
}

// UpdateBillingCycle sets the "billing_cycle" field to the value that was provided on create.
func (u *TenantSubscriptionUpsert) UpdateBillingCycle() *TenantSubscriptionUpsert {
	u.SetExcluded(tenantsubscription.FieldBillingCycle)
	return u
}

// SetAppliedDiscount sets the "applied_discount" field.
func (u *TenantSubscriptionUpsert) SetAppliedDiscount(v float64) *TenantSubscriptionUpsert {
	u.Set(tenantsubscription.FieldAppliedDiscount, v)
	return u
}

// UpdateAppliedDiscount sets the "applied_discount" field to the value that was provided on create.
func (u *TenantSubscriptionUpsert) UpdateAppliedDiscount() *TenantSubscriptionUpsert {
	u.SetExcluded(tenantsubscription.FieldAppliedDiscount)
	return u
}

// AddAppliedDiscount adds v to the "applied_discount" field.
func (u *TenantSubscriptionUpsert) AddAppliedDiscount(v float64) *TenantSubscriptionUpsert {
	u.Add(tenantsubscription.FieldAppliedDiscount, v)
	return u
}

// SetBundleCode sets the "bundle_code" field.
func (u *TenantSubscriptionUpsert) SetBundleCode(v string) *TenantSubscriptionUpsert {
	u.Set(tenantsubscription.FieldBundleCode, v)
	return u
}

// UpdateBundleCode sets the "bundle_code" field to the value that was provided on create.
func (u *TenantSubscriptionUpsert) UpdateBundleCode() *TenantSubscriptionUpsert {
	u.SetExcluded(tenantsubscription.FieldBundleCode)
	return u
}

// ClearBundleCode clears the value of the "bundle_code" field.
func (u *TenantSubscriptionUpsert) ClearBundleCode() *TenantSubscriptionUpsert {
	u.SetNull(tenantsubscription.FieldBundleCode)
	return u
}

// SetPaymentMethodID sets the "payment_method_id" field.
func (u *TenantSubscriptionUpsert) SetPaymentMethodID(v uuid.UUID) *TenantSubscriptionUpsert {
	u.Set(tenantsubscription.FieldPaymentMethodID, v)
	return u
}

// UpdatePaymentMethodID sets the "payment_method_id" field to the value that was provided on create.
func (u *TenantSubscriptionUpsert) UpdatePaymentMethodID() *TenantSubscriptionUpsert {
	u.SetExcluded(tenantsubscription.FieldPaymentMethodID)
	return u
}

// ClearPaymentMethodID clears the value of the "payment_method_id" field.
func (u *TenantSubscriptionUpsert) ClearPaymentMethodID() *TenantSubscriptionUpsert {
	u.SetNull(tenantsubscription.FieldPaymentMethodID)
	return u
}

// SetMetadata sets the "metadata" field.
func (u *TenantSubscriptionUpsert) SetMetadata(v map[string]interface{}) *TenantSubscriptionUpsert {
	u.Set(tenantsubscription.FieldMetadata, v)
	return u
}

// UpdateMetadata sets the "metadata" field to the value that was provided on create.
func (u *TenantSubscriptionUpsert) UpdateMetadata() *TenantSubscriptionUpsert {
	u.SetExcluded(tenantsubscription.FieldMetadata)
	return u
}

// ClearMetadata clears the value of the "metadata" field.
func (u *TenantSubscriptionUpsert) ClearMetadata() *TenantSubscriptionUpsert {
	u.SetNull(tenantsubscription.FieldMetadata)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *TenantSubscriptionUpsert) SetUpdatedAt(v time.Time) *TenantSubscriptionUpsert {
	u.Set(tenantsubscription.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *TenantSubscriptionUpsert) UpdateUpdatedAt() *TenantSubscriptionUpsert {
	u.SetExcluded(tenantsubscription.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.TenantSubscription.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(tenantsubscription.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *TenantSubscriptionUpsertOne) UpdateNewValues() *TenantSubscriptionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(tenantsubscription.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(tenantsubscription.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.TenantSubscription.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *TenantSubscriptionUpsertOne) Ignore() *TenantSubscriptionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *TenantSubscriptionUpsertOne) DoNothing() *TenantSubscriptionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the TenantSubscriptionCreate.OnConflict
// documentation for more info.
func (u *TenantSubscriptionUpsertOne) Update(set func(*TenantSubscriptionUpsert)) *TenantSubscriptionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&TenantSubscriptionUpsert{UpdateSet: update})
	}))
	return u
}

// SetTenantID sets the "tenant_id" field.
func (u *TenantSubscriptionUpsertOne) SetTenantID(v uuid.UUID) *TenantSubscriptionUpsertOne {
	return u.Update(func(s *TenantSubscriptionUpsert) {
		s.SetTenantID(v)
	})
}

// UpdateTenantID sets the "tenant_id" field to the value that was provided on create.
func (u *TenantSubscriptionUpsertOne) UpdateTenantID() *TenantSubscriptionUpsertOne {
	return u.Update(func(s *TenantSubscriptionUpsert) {
		s.UpdateTenantID()
	})
}

// SetPlanID sets the "plan_id" field.
func (u *TenantSubscriptionUpsertOne) SetPlanID(v uuid.UUID) *TenantSubscriptionUpsertOne {
	return u.Update(func(s *TenantSubscriptionUpsert) {
		s.SetPlanID(v)
	})
}

// UpdatePlanID sets the "plan_id" field to the value that was provided on create.
func (u *TenantSubscriptionUpsertOne) UpdatePlanID() *TenantSubscriptionUpsertOne {
	return u.Update(func(s *TenantSubscriptionUpsert) {
		s.UpdatePlanID()
	})
}

// SetStatus sets the "status" field.
func (u *TenantSubscriptionUpsertOne) SetStatus(v tenantsubscription.Status) *TenantSubscriptionUpsertOne {
	return u.Update(func(s *TenantSubscriptionUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *TenantSubscriptionUpsertOne) UpdateStatus() *TenantSubscriptionUpsertOne {
	return u.Update(func(s *TenantSubscriptionUpsert) {
		s.UpdateStatus()
	})
}

// SetTrialEndsAt sets the "trial_ends_at" field.
func (u *TenantSubscriptionUpsertOne) SetTrialEndsAt(v time.Time) *TenantSubscriptionUpsertOne {
	return u.Update(func(s *TenantSubscriptionUpsert) {
		s.SetTrialEndsAt(v)
	})
}

// UpdateTrialEndsAt sets the "trial_ends_at" field to the value that was provided on create.
func (u *TenantSubscriptionUpsertOne) UpdateTrialEndsAt() *TenantSubscriptionUpsertOne {
	return u.Update(func(s *TenantSubscriptionUpsert) {
		s.UpdateTrialEndsAt()
	})
}

// ClearTrialEndsAt clears the value of the "trial_ends_at" field.
func (u *TenantSubscriptionUpsertOne) ClearTrialEndsAt() *TenantSubscriptionUpsertOne {
	return u.Update(func(s *TenantSubscriptionUpsert) {
		s.ClearTrialEndsAt()
	})
}

// SetCurrentPeriodStart sets the "current_period_start" field.
func (u *TenantSubscriptionUpsertOne) SetCurrentPeriodStart(v time.Time) *TenantSubscriptionUpsertOne {
	return u.Update(func(s *TenantSubscriptionUpsert) {
		s.SetCurrentPeriodStart(v)
	})
}

// UpdateCurrentPeriodStart sets the "current_period_start" field to the value that was provided on create.
func (u *TenantSubscriptionUpsertOne) UpdateCurrentPeriodStart() *TenantSubscriptionUpsertOne {
	return u.Update(func(s *TenantSubscriptionUpsert) {
		s.UpdateCurrentPeriodStart()
	})
}

// SetCurrentPeriodEnd sets the "current_period_end" field.
func (u *TenantSubscriptionUpsertOne) SetCurrentPeriodEnd(v time.Time) *TenantSubscriptionUpsertOne {
	return u.Update(func(s *TenantSubscriptionUpsert) {
		s.SetCurrentPeriodEnd(v)
	})
}

// UpdateCurrentPeriodEnd sets the "current_period_end" field to the value that was provided on create.
func (u *TenantSubscriptionUpsertOne) UpdateCurrentPeriodEnd() *TenantSubscriptionUpsertOne {
	return u.Update(func(s *TenantSubscriptionUpsert) {
		s.UpdateCurrentPeriodEnd()
	})
}

// SetCancelledAt sets the "cancelled_at" field.
func (u *TenantSubscriptionUpsertOne) SetCancelledAt(v time.Time) *TenantSubscriptionUpsertOne {
	return u.Update(func(s *TenantSubscriptionUpsert) {
		s.SetCancelledAt(v)
	})
}

// UpdateCancelledAt sets the "cancelled_at" field to the value that was provided on create.
func (u *TenantSubscriptionUpsertOne) UpdateCancelledAt() *TenantSubscriptionUpsertOne {
	return u.Update(func(s *TenantSubscriptionUpsert) {
		s.UpdateCancelledAt()
	})
}

// ClearCancelledAt clears the value of the "cancelled_at" field.
func (u *TenantSubscriptionUpsertOne) ClearCancelledAt() *TenantSubscriptionUpsertOne {
	return u.Update(func(s *TenantSubscriptionUpsert) {
		s.ClearCancelledAt()
	})
}

// SetCancelReason sets the "cancel_reason" field.
func (u *TenantSubscriptionUpsertOne) SetCancelReason(v string) *TenantSubscriptionUpsertOne {
	return u.Update(func(s *TenantSubscriptionUpsert) {
		s.SetCancelReason(v)
	})
}

// UpdateCancelReason sets the "cancel_reason" field to the value that was provided on create.
func (u *TenantSubscriptionUpsertOne) UpdateCancelReason() *TenantSubscriptionUpsertOne {
	return u.Update(func(s *TenantSubscriptionUpsert) {
		s.UpdateCancelReason()
	})
}

// ClearCancelReason clears the value of the "cancel_reason" field.
func (u *TenantSubscriptionUpsertOne) ClearCancelReason() *TenantSubscriptionUpsertOne {
	return u.Update(func(s *TenantSubscriptionUpsert) {
		s.ClearCancelReason()
	})
}

// SetBillingCycle sets the "billing_cycle" field.
func (u *TenantSubscriptionUpsertOne) SetBillingCycle(v tenantsubscription.BillingCycle) *TenantSubscriptionUpsertOne {
	return u.Update(func(s *TenantSubscriptionUpsert) {
		s.SetBillingCycle(v)
	})
}

// UpdateBillingCycle sets the "billing_cycle" field to the value that was provided on create.
func (u *TenantSubscriptionUpsertOne) UpdateBillingCycle() *TenantSubscriptionUpsertOne {
	return u.Update(func(s *TenantSubscriptionUpsert) {
		s.UpdateBillingCycle()
	})
}

// SetAppliedDiscount sets the "applied_discount" field.
func (u *TenantSubscriptionUpsertOne) SetAppliedDiscount(v float64) *TenantSubscriptionUpsertOne {
	return u.Update(func(s *TenantSubscriptionUpsert) {
		s.SetAppliedDiscount(v)
	})
}

// AddAppliedDiscount adds v to the "applied_discount" field.
func (u *TenantSubscriptionUpsertOne) AddAppliedDiscount(v float64) *TenantSubscriptionUpsertOne {
	return u.Update(func(s *TenantSubscriptionUpsert) {
		s.AddAppliedDiscount(v)
	})
}

// UpdateAppliedDiscount sets the "applied_discount" field to the value that was provided on create.
func (u *TenantSubscriptionUpsertOne) UpdateAppliedDiscount() *TenantSubscriptionUpsertOne {
	return u.Update(func(s *TenantSubscriptionUpsert) {
		s.UpdateAppliedDiscount()
	})
}

// SetBundleCode sets the "bundle_code" field.
func (u *TenantSubscriptionUpsertOne) SetBundleCode(v string) *TenantSubscriptionUpsertOne {
	return u.Update(func(s *TenantSubscriptionUpsert) {
		s.SetBundleCode(v)
	})
}

// UpdateBundleCode sets the "bundle_code" field to the value that was provided on create.
func (u *TenantSubscriptionUpsertOne) UpdateBundleCode() *TenantSubscriptionUpsertOne {
	return u.Update(func(s *TenantSubscriptionUpsert) {
		s.UpdateBundleCode()
	})
}

// ClearBundleCode clears the value of the "bundle_code" field.
func (u *TenantSubscriptionUpsertOne) ClearBundleCode() *TenantSubscriptionUpsertOne {
	return u.Update(func(s *TenantSubscriptionUpsert) {
		s.ClearBundleCode()
	})
}

// SetPaymentMethodID sets the "payment_method_id" field.
func (u *TenantSubscriptionUpsertOne) SetPaymentMethodID(v uuid.UUID) *TenantSubscriptionUpsertOne {
	return u.Update(func(s *TenantSubscriptionUpsert) {
		s.SetPaymentMethodID(v)
	})
}

// UpdatePaymentMethodID sets the "payment_method_id" field to the value that was provided on create.
func (u *TenantSubscriptionUpsertOne) UpdatePaymentMethodID() *TenantSubscriptionUpsertOne {
	return u.Update(func(s *TenantSubscriptionUpsert) {
		s.UpdatePaymentMethodID()
	})
}

// ClearPaymentMethodID clears the value of the "payment_method_id" field.
func (u *TenantSubscriptionUpsertOne) ClearPaymentMethodID() *TenantSubscriptionUpsertOne {
	return u.Update(func(s *TenantSubscriptionUpsert) {
		s.ClearPaymentMethodID()
	})
}

// SetMetadata sets the "metadata" field.
func (u *TenantSubscriptionUpsertOne) SetMetadata(v map[string]interface{}) *TenantSubscriptionUpsertOne {
	return u.Update(func(s *TenantSubscriptionUpsert) {
		s.SetMetadata(v)
	})
}

// UpdateMetadata sets the "metadata" field to the value that was provided on create.
func (u *TenantSubscriptionUpsertOne) UpdateMetadata() *TenantSubscriptionUpsertOne {
	return u.Update(func(s *TenantSubscriptionUpsert) {
		s.UpdateMetadata()
	})
}

// ClearMetadata clears the value of the "metadata" field.
func (u *TenantSubscriptionUpsertOne) ClearMetadata() *TenantSubscriptionUpsertOne {
	return u.Update(func(s *TenantSubscriptionUpsert) {
		s.ClearMetadata()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *TenantSubscriptionUpsertOne) SetUpdatedAt(v time.Time) *TenantSubscriptionUpsertOne {
	return u.Update(func(s *TenantSubscriptionUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *TenantSubscriptionUpsertOne) UpdateUpdatedAt() *TenantSubscriptionUpsertOne {
	return u.Update(func(s *TenantSubscriptionUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *TenantSubscriptionUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for TenantSubscriptionCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *TenantSubscriptionUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *TenantSubscriptionUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: TenantSubscriptionUpsertOne.ID is not supported by MySQL driver. Use TenantSubscriptionUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *TenantSubscriptionUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// TenantSubscriptionCreateBulk is the builder for creating many TenantSubscription entities in bulk.
type TenantSubscriptionCreateBulk struct {
	config
	err      error
	builders []*TenantSubscriptionCreate
	conflict []sql.ConflictOption
}

// Save creates the TenantSubscription entities in the database.
func (_c *TenantSubscriptionCreateBulk) Save(ctx context.Context) ([]*TenantSubscription, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*TenantSubscription, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TenantSubscriptionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *TenantSubscriptionCreateBulk) SaveX(ctx context.Context) []*TenantSubscription {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TenantSubscriptionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TenantSubscriptionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.TenantSubscription.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.TenantSubscriptionUpsert) {
//			SetTenantID(v+v).
//		}).
//		Exec(ctx)
func (_c *TenantSubscriptionCreateBulk) OnConflict(opts ...sql.ConflictOption) *TenantSubscriptionUpsertBulk {
	_c.conflict = opts
	return &TenantSubscriptionUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.TenantSubscription.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *TenantSubscriptionCreateBulk) OnConflictColumns(columns ...string) *TenantSubscriptionUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &TenantSubscriptionUpsertBulk{
		create: _c,
	}
}

// TenantSubscriptionUpsertBulk is the builder for "upsert"-ing
// a bulk of TenantSubscription nodes.
type TenantSubscriptionUpsertBulk struct {
	create *TenantSubscriptionCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.TenantSubscription.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(tenantsubscription.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *TenantSubscriptionUpsertBulk) UpdateNewValues() *TenantSubscriptionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(tenantsubscription.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(tenantsubscription.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.TenantSubscription.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *TenantSubscriptionUpsertBulk) Ignore() *TenantSubscriptionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *TenantSubscriptionUpsertBulk) DoNothing() *TenantSubscriptionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the TenantSubscriptionCreateBulk.OnConflict
// documentation for more info.
func (u *TenantSubscriptionUpsertBulk) Update(set func(*TenantSubscriptionUpsert)) *TenantSubscriptionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&TenantSubscriptionUpsert{UpdateSet: update})
	}))
	return u
}

// SetTenantID sets the "tenant_id" field.
func (u *TenantSubscriptionUpsertBulk) SetTenantID(v uuid.UUID) *TenantSubscriptionUpsertBulk {
	return u.Update(func(s *TenantSubscriptionUpsert) {
		s.SetTenantID(v)
	})
}

// UpdateTenantID sets the "tenant_id" field to the value that was provided on create.
func (u *TenantSubscriptionUpsertBulk) UpdateTenantID() *TenantSubscriptionUpsertBulk {
	return u.Update(func(s *TenantSubscriptionUpsert) {
		s.UpdateTenantID()
	})
}

// SetPlanID sets the "plan_id" field.
func (u *TenantSubscriptionUpsertBulk) SetPlanID(v uuid.UUID) *TenantSubscriptionUpsertBulk {
	return u.Update(func(s *TenantSubscriptionUpsert) {
		s.SetPlanID(v)
	})
}

// UpdatePlanID sets the "plan_id" field to the value that was provided on create.
func (u *TenantSubscriptionUpsertBulk) UpdatePlanID() *TenantSubscriptionUpsertBulk {
	return u.Update(func(s *TenantSubscriptionUpsert) {
		s.UpdatePlanID()
	})
}

// SetStatus sets the "status" field.
func (u *TenantSubscriptionUpsertBulk) SetStatus(v tenantsubscription.Status) *TenantSubscriptionUpsertBulk {
	return u.Update(func(s *TenantSubscriptionUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *TenantSubscriptionUpsertBulk) UpdateStatus() *TenantSubscriptionUpsertBulk {
	return u.Update(func(s *TenantSubscriptionUpsert) {
		s.UpdateStatus()
	})
}

// SetTrialEndsAt sets the "trial_ends_at" field.
func (u *TenantSubscriptionUpsertBulk) SetTrialEndsAt(v time.Time) *TenantSubscriptionUpsertBulk {
	return u.Update(func(s *TenantSubscriptionUpsert) {
		s.SetTrialEndsAt(v)
	})
}

// UpdateTrialEndsAt sets the "trial_ends_at" field to the value that was provided on create.
func (u *TenantSubscriptionUpsertBulk) UpdateTrialEndsAt() *TenantSubscriptionUpsertBulk {
	return u.Update(func(s *TenantSubscriptionUpsert) {
		s.UpdateTrialEndsAt()
	})
}

// ClearTrialEndsAt clears the value of the "trial_ends_at" field.
func (u *TenantSubscriptionUpsertBulk) ClearTrialEndsAt() *TenantSubscriptionUpsertBulk {
	return u.Update(func(s *TenantSubscriptionUpsert) {
		s.ClearTrialEndsAt()
	})
}

// SetCurrentPeriodStart sets the "current_period_start" field.
func (u *TenantSubscriptionUpsertBulk) SetCurrentPeriodStart(v time.Time) *TenantSubscriptionUpsertBulk {
	return u.Update(func(s *TenantSubscriptionUpsert) {
		s.SetCurrentPeriodStart(v)
	})
}

// UpdateCurrentPeriodStart sets the "current_period_start" field to the value that was provided on create.
func (u *TenantSubscriptionUpsertBulk) UpdateCurrentPeriodStart() *TenantSubscriptionUpsertBulk {
	return u.Update(func(s *TenantSubscriptionUpsert) {
		s.UpdateCurrentPeriodStart()
	})
}

// SetCurrentPeriodEnd sets the "current_period_end" field.
func (u *TenantSubscriptionUpsertBulk) SetCurrentPeriodEnd(v time.Time) *TenantSubscriptionUpsertBulk {
	return u.Update(func(s *TenantSubscriptionUpsert) {
		s.SetCurrentPeriodEnd(v)
	})
}

// UpdateCurrentPeriodEnd sets the "current_period_end" field to the value that was provided on create.
func (u *TenantSubscriptionUpsertBulk) UpdateCurrentPeriodEnd() *TenantSubscriptionUpsertBulk {
	return u.Update(func(s *TenantSubscriptionUpsert) {
		s.UpdateCurrentPeriodEnd()
	})
}

// SetCancelledAt sets the "cancelled_at" field.
func (u *TenantSubscriptionUpsertBulk) SetCancelledAt(v time.Time) *TenantSubscriptionUpsertBulk {
	return u.Update(func(s *TenantSubscriptionUpsert) {
		s.SetCancelledAt(v)
	})
}

// UpdateCancelledAt sets the "cancelled_at" field to the value that was provided on create.
func (u *TenantSubscriptionUpsertBulk) UpdateCancelledAt() *TenantSubscriptionUpsertBulk {
	return u.Update(func(s *TenantSubscriptionUpsert) {
		s.UpdateCancelledAt()
	})
}

// ClearCancelledAt clears the value of the "cancelled_at" field.
func (u *TenantSubscriptionUpsertBulk) ClearCancelledAt() *TenantSubscriptionUpsertBulk {
	return u.Update(func(s *TenantSubscriptionUpsert) {
		s.ClearCancelledAt()
	})
}

// SetCancelReason sets the "cancel_reason" field.
func (u *TenantSubscriptionUpsertBulk) SetCancelReason(v string) *TenantSubscriptionUpsertBulk {
	return u.Update(func(s *TenantSubscriptionUpsert) {
		s.SetCancelReason(v)
	})
}

// UpdateCancelReason sets the "cancel_reason" field to the value that was provided on create.
func (u *TenantSubscriptionUpsertBulk) UpdateCancelReason() *TenantSubscriptionUpsertBulk {
	return u.Update(func(s *TenantSubscriptionUpsert) {
		s.UpdateCancelReason()
	})
}

// ClearCancelReason clears the value of the "cancel_reason" field.
func (u *TenantSubscriptionUpsertBulk) ClearCancelReason() *TenantSubscriptionUpsertBulk {
	return u.Update(func(s *TenantSubscriptionUpsert) {
		s.ClearCancelReason()
	})
}

// SetBillingCycle sets the "billing_cycle" field.
func (u *TenantSubscriptionUpsertBulk) SetBillingCycle(v tenantsubscription.BillingCycle) *TenantSubscriptionUpsertBulk {
	return u.Update(func(s *TenantSubscriptionUpsert) {
		s.SetBillingCycle(v)
	})
}

// UpdateBillingCycle sets the "billing_cycle" field to the value that was provided on create.
func (u *TenantSubscriptionUpsertBulk) UpdateBillingCycle() *TenantSubscriptionUpsertBulk {
	return u.Update(func(s *TenantSubscriptionUpsert) {
		s.UpdateBillingCycle()
	})
}

// SetAppliedDiscount sets the "applied_discount" field.
func (u *TenantSubscriptionUpsertBulk) SetAppliedDiscount(v float64) *TenantSubscriptionUpsertBulk {
	return u.Update(func(s *TenantSubscriptionUpsert) {
		s.SetAppliedDiscount(v)
	})
}

// AddAppliedDiscount adds v to the "applied_discount" field.
func (u *TenantSubscriptionUpsertBulk) AddAppliedDiscount(v float64) *TenantSubscriptionUpsertBulk {
	return u.Update(func(s *TenantSubscriptionUpsert) {
		s.AddAppliedDiscount(v)
	})
}

// UpdateAppliedDiscount sets the "applied_discount" field to the value that was provided on create.
func (u *TenantSubscriptionUpsertBulk) UpdateAppliedDiscount() *TenantSubscriptionUpsertBulk {
	return u.Update(func(s *TenantSubscriptionUpsert) {
		s.UpdateAppliedDiscount()
	})
}

// SetBundleCode sets the "bundle_code" field.
func (u *TenantSubscriptionUpsertBulk) SetBundleCode(v string) *TenantSubscriptionUpsertBulk {
	return u.Update(func(s *TenantSubscriptionUpsert) {
		s.SetBundleCode(v)
	})
}

// UpdateBundleCode sets the "bundle_code" field to the value that was provided on create.
func (u *TenantSubscriptionUpsertBulk) UpdateBundleCode() *TenantSubscriptionUpsertBulk {
	return u.Update(func(s *TenantSubscriptionUpsert) {
		s.UpdateBundleCode()
	})
}

// ClearBundleCode clears the value of the "bundle_code" field.
func (u *TenantSubscriptionUpsertBulk) ClearBundleCode() *TenantSubscriptionUpsertBulk {
	return u.Update(func(s *TenantSubscriptionUpsert) {
		s.ClearBundleCode()
	})
}

// SetPaymentMethodID sets the "payment_method_id" field.
func (u *TenantSubscriptionUpsertBulk) SetPaymentMethodID(v uuid.UUID) *TenantSubscriptionUpsertBulk {
	return u.Update(func(s *TenantSubscriptionUpsert) {
		s.SetPaymentMethodID(v)
	})
}

// UpdatePaymentMethodID sets the "payment_method_id" field to the value that was provided on create.
func (u *TenantSubscriptionUpsertBulk) UpdatePaymentMethodID() *TenantSubscriptionUpsertBulk {
	return u.Update(func(s *TenantSubscriptionUpsert) {
		s.UpdatePaymentMethodID()
	})
}

// ClearPaymentMethodID clears the value of the "payment_method_id" field.
func (u *TenantSubscriptionUpsertBulk) ClearPaymentMethodID() *TenantSubscriptionUpsertBulk {
	return u.Update(func(s *TenantSubscriptionUpsert) {
		s.ClearPaymentMethodID()
	})
}

// SetMetadata sets the "metadata" field.
func (u *TenantSubscriptionUpsertBulk) SetMetadata(v map[string]interface{}) *TenantSubscriptionUpsertBulk {
	return u.Update(func(s *TenantSubscriptionUpsert) {
		s.SetMetadata(v)
	})
}

// UpdateMetadata sets the "metadata" field to the value that was provided on create.
func (u *TenantSubscriptionUpsertBulk) UpdateMetadata() *TenantSubscriptionUpsertBulk {
	return u.Update(func(s *TenantSubscriptionUpsert) {
		s.UpdateMetadata()
	})
}

// ClearMetadata clears the value of the "metadata" field.
func (u *TenantSubscriptionUpsertBulk) ClearMetadata() *TenantSubscriptionUpsertBulk {
	return u.Update(func(s *TenantSubscriptionUpsert) {
		s.ClearMetadata()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *TenantSubscriptionUpsertBulk) SetUpdatedAt(v time.Time) *TenantSubscriptionUpsertBulk {
	return u.Update(func(s *TenantSubscriptionUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *TenantSubscriptionUpsertBulk) UpdateUpdatedAt() *TenantSubscriptionUpsertBulk {
	return u.Update(func(s *TenantSubscriptionUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *TenantSubscriptionUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the TenantSubscriptionCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for TenantSubscriptionCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *TenantSubscriptionUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
