// Code generated by ent, DO NOT EDIT.

package ratelimitconfig

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the ratelimitconfig type in the database.
	Label = "rate_limit_config"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldServiceName holds the string denoting the service_name field in the database.
	FieldServiceName = "service_name"
	// FieldKeyType holds the string denoting the key_type field in the database.
	FieldKeyType = "key_type"
	// FieldEndpointPattern holds the string denoting the endpoint_pattern field in the database.
	FieldEndpointPattern = "endpoint_pattern"
	// FieldRequestsPerWindow holds the string denoting the requests_per_window field in the database.
	FieldRequestsPerWindow = "requests_per_window"
	// FieldWindowSeconds holds the string denoting the window_seconds field in the database.
	FieldWindowSeconds = "window_seconds"
	// FieldBurstMultiplier holds the string denoting the burst_multiplier field in the database.
	FieldBurstMultiplier = "burst_multiplier"
	// FieldIsActive holds the string denoting the is_active field in the database.
	FieldIsActive = "is_active"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the ratelimitconfig in the database.
	Table = "rate_limit_configs"
)

// Columns holds all SQL columns for ratelimitconfig fields.
var Columns = []string{
	FieldID,
	FieldServiceName,
	FieldKeyType,
	FieldEndpointPattern,
	FieldRequestsPerWindow,
	FieldWindowSeconds,
	FieldBurstMultiplier,
	FieldIsActive,
	FieldDescription,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// ServiceNameValidator is a validator for the "service_name" field. It is called by the builders before save.
	ServiceNameValidator func(string) error
	// KeyTypeValidator is a validator for the "key_type" field. It is called by the builders before save.
	KeyTypeValidator func(string) error
	// DefaultEndpointPattern holds the default value on creation for the "endpoint_pattern" field.
	DefaultEndpointPattern string
	// DefaultRequestsPerWindow holds the default value on creation for the "requests_per_window" field.
	DefaultRequestsPerWindow int
	// RequestsPerWindowValidator is a validator for the "requests_per_window" field. It is called by the builders before save.
	RequestsPerWindowValidator func(int) error
	// DefaultWindowSeconds holds the default value on creation for the "window_seconds" field.
	DefaultWindowSeconds int
	// WindowSecondsValidator is a validator for the "window_seconds" field. It is called by the builders before save.
	WindowSecondsValidator func(int) error
	// DefaultBurstMultiplier holds the default value on creation for the "burst_multiplier" field.
	DefaultBurstMultiplier float64
	// DefaultIsActive holds the default value on creation for the "is_active" field.
	DefaultIsActive bool
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the RateLimitConfig queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByServiceName orders the results by the service_name field.
func ByServiceName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldServiceName, opts...).ToFunc()
}

// ByKeyType orders the results by the key_type field.
func ByKeyType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldKeyType, opts...).ToFunc()
}

// ByEndpointPattern orders the results by the endpoint_pattern field.
func ByEndpointPattern(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEndpointPattern, opts...).ToFunc()
}

// ByRequestsPerWindow orders the results by the requests_per_window field.
func ByRequestsPerWindow(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRequestsPerWindow, opts...).ToFunc()
}

// ByWindowSeconds orders the results by the window_seconds field.
func ByWindowSeconds(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWindowSeconds, opts...).ToFunc()
}

// ByBurstMultiplier orders the results by the burst_multiplier field.
func ByBurstMultiplier(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBurstMultiplier, opts...).ToFunc()
}

// ByIsActive orders the results by the is_active field.
func ByIsActive(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsActive, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
